### ISSUE TITLE
Error in outcome history vector

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1]
It doesn't seem to report the status of the just previous trial in the vector for the overall outcome history. It is as if the last value is recorded after the probability function runs (I think that is what happens).

**Comment by andrewtackett** [comment]
Should be solved with commit: ac3e42879bde62cadbfdb0635a0705285abc50de

Please test and let me know.

Andrew

**Comment by imrryr** [comment]
Is it possible this small delay is needed for other accounting processes.... I seem to see occasional irregularities in the last trial record....
