### ISSUE TITLE
Stimulus file for survey won't upload

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1012]
**Describe the bug**
I don't think it has changed....
[IESsurveystims.zip](https://github.com/memphis-iis/mofacts-ies/files/9972698/IESsurveystims.zip)

![Screenshot (50)](https://user-images.githubusercontent.com/13023147/200876727-e8d6b310-b777-40b3-b489-9bb7973f8dc3.png)

**Comment by imrryr** [comment]
This issue is late and super important.

**Comment by MegaGeese** [comment]
Seems like this didn't get closed when it was completed. The stim file upload works.
