### ISSUE TITLE
User cloze edit is invalid json

### ISSUE THREAD

**Issue by aolney** [memphis-iis/mofacts-ies#102]
The json obtained from

## User Cloze Edits
...
Download: ambanker@southwest.tn.edu

is invalid. I appears that it is intended to be a list of subobjects having structure

- id
- original clozes
- ending clozes
- cloze edits
- user
- timestamp

However, there are no `[]` enclosing the list or commas between the subobjects.

Side question: in `clozeEdits` if `endingCloze` is {}, does that mean the item was deleted rather than modified? If so, it appears that Amanda never edited and always deleted. I can confirm that in my own test data, `endingCloze` is nonempty when I modified it, so I'm just confirming Amanda's use of the feature rather than implying there is data loss

**Comment by andrewtackett** [comment]
If you mean the fact that the entire file is not valid json then yes, I mentioned this before.  Each line is a single json object taken directly from the database.  If you mean each line is not valid json...I'm not sure I understand as the database stores it fine.

Re: your sidequestion, yes an empty endingCloze means the item was deleted.

**Comment by aolney** [comment]
Gotcha. If it is possible to output a list of json objects that would be ideal. Thank you for the clarification on endingCloze

**Comment by imrryr** [comment]
How should I classify this?

**Comment by andrewtackett** [comment]
@imrryr Seems like low priority for later easier data analysis, but @aolney may have other thoughts

**Comment by aolney** [comment]
I'd say it's a documentation issue. I can imagine outputting valid json would remove some of the documentation need.

**Comment by andrewtackett** [comment]
Documentation issues only pertain to actual documentation.  All code *should* be documented ideally.  But if it involves code changes then it's not really about documentation.

**Comment by imrryr** [comment]
We are not using teacher edits anymore for the project
