### ISSUE TITLE
Demo images not showing

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1033]
**Describe the bug**
Looks like the path might be wrong. I wonder if the package attached was correctly set up, or perhaps the creation of URLs from the package is wrong.
[TNPlants.zip](https://github.com/memphis-iis/mofacts-ies/files/10169044/TNPlants.zip)

**Comment by MegaGeese** [comment]
@imrryr this was caused by an old bug that has been resolved. Bug has been cleaned from the DB and package reuploaded. Images now appear without issue. You might want to reupload the package so that you get set as the owner
