### ISSUE TITLE
TDF optimzied practice won't start

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1058]
**Describe the bug**
Fails with blank screen on first optimized practice in the unit after the survey.

![image](https://user-images.githubusercontent.com/13023147/215188805-4274de7e-33d1-44ba-a381-26f70f6c32b1.png)
[periodicstims1.zip](https://github.com/memphis-iis/mofacts-ies/files/10522815/periodicstims1.zip)

**Comment by imrryr** [comment]
Can I get a vague sense of what caused this, please? No need for all the details, but some would be nice.

**Comment by MegaGeese** [comment]
One of the session variables was unset somehow. Wrote some code to make sure that it can't be unset anymore
