### ISSUE TITLE
shuffleclusters not working

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1065]
**Describe the bug**
No indication of shuffleclusters in tdf4, also, there are 2 versions of the stimuli file.... This doesn't make sense and can't be permitted. Files must be overwritten or something it seems... It should at least block upload if filenames match.
![image](https://user-images.githubusercontent.com/13023147/218545536-c0c08149-3bd6-4a78-bd30-96ec13434501.png)

**Comment by imrryr** [comment]
shuffleclusters is not working that is. The items were not randomized before the scheduling... this used to work fine. Maybe an old tdf without shuffleclusters (TDF 3 (1)) was firing despite the different link

**Comment by MegaGeese** [comment]
@imrryr do you have a copy of TDF 3 that I can use to debug this?

**Comment by MegaGeese** [comment]
was it uploaded to mofacts? Im not seeing it on either the DB or the file list

**Comment by imrryr** [comment]
I'm checking with Blake, but it is running on mofacts, so I can't make sense of why we can't find it...

**Comment by MegaGeese** [comment]
I'll look into that in the meantime and open a bug report if needed

**Comment by imrryr** [comment]
I emailed Blake to get his ID... then (in theory) there is an impersonate button that can be used to download it from his account for an admin

**Comment by imrryr** [comment]
See email. problem is still happening
