### ISSUE TITLE
Experiment crashes at optimized practice unit

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1082]
**Describe the bug**
Everything appeared to be working, then it crashed as practice started, before showing any stimuli with a blank green screen. Here is a paste from console. You can try it here: https://staging.optimallearning.org/experiment/indradicals

calculateCardProbabilities [0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33,0.33]
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 findMinProbDistCard
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 displayReadyFalse, prepareCard
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 Model practice check 0.95 > 120
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 selectNextCard unitMode: distance
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 selectNextCard indices: 0 0 0 Object
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 MODEL UNIT card selection =>  cluster-idx: 0 whichStim: 0 whichHintLevel: 0 parameter Array(2)
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 select next card: 0 0 0
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 currentCardInfo: Object
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 setUpCardQuestionAndAnswerGlobals 0 0 Object Object Object 0
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 setUpCardQuestionSyllables:  乙 in English undefined second Object
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 getSubClozeAnswerSyllables, displaySyllableIndices/hintsylls:  undefined , this.cachedSyllables:  null
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 replaceClozeWithSyllables1:  乙 in English Object second
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 setUpCardQuestionSyllables: 乙 in English undefined Object undefined second
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 HintLevel: setUpCardQuestionAndAnswerGlobals 0
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 setUpCardQuestionAndAnswerGlobals2: 乙 in English undefined
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 setUpCardQuestionAndAnswerGlobals3: Object undefined second
39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'find')
    at Object.setUpCardQuestionAndAnswerGlobals (39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284:106854)
    at async Object.selectNextCard (39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284:130725)
    at async Qe (39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284:69063)
    at async vt (39b63f86004b4f13d7f494f51283fd9ef8410877.js?meteor_js_resource=true:284:89278)

**Comment by JRustyHaner** [comment]
Looks like it's trying to read the property 'find' of an variable that doesn't exist.
