### ISSUE TITLE
Score showing for improper unit types (also it is not really resetting)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1087]
**Describe the bug**
Screenshot shows it 
![Screenshot (65)](https://user-images.githubusercontent.com/13023147/227961352-198560ba-ef27-4a7e-b99f-aa21b5b44ed4.png)

Score should not occur during assessment sessions. Also, the Count here leaped up from the previous unit, suggesting that the reset of the score only worked for the unit itself... that is odd...

**Comment by JRustyHaner** [comment]
@imrryr I have a PR for fixing the display issue

**Comment by MegaGeese** [comment]
@imrryr Currently i have it written where when the score gets reset it will still keep track of overall score. If the user starts a unit that resets their score then starts a unit that doesnt reset score it will display their overall score. 
Do you want the reset score to be carried over to later units?

**Comment by imrryr** [comment]
@MegaGeese Yes, please. Otherwise, there are essentially two different scores at times, which I think is confusing.

**Comment by MegaGeese** [comment]
do you want the displayed time to be the overall time or should that reset with the score

**Comment by imrryr** [comment]
great question. I think we should have all 3 of the top indicators be reset. that seems reasonably easy for people to understand when it happens at the beginning of a unit. If it were inconsistent it might be less clear I think.

**Comment by imrryr** [comment]
Yes, that is a cumulative report. Another good question
