### ISSUE TITLE
Multiple files downloading under content uploads

### ISSUE THREAD

**Issue by Brtelfer** [memphis-iis/mofacts-ies#1098]
**The Bug**
After downloading certain files, multiple files under the same name will be automatically downloaded.

**To Reproduce**
1. Go to 'https://staging.optimallearning.org/contentUpload'
2. Click on the download button for 'teststimuli3.json'

**Expected behavior**
Approximately 18 files under the name 'teststimuli3.json' will be downloaded. These files correspond to previously uploaded and deleted files that were also under the name 'teststimuli3.json'

**Comment by MegaGeese** [comment]
Fixed in a previous deploy. Multiple old files may appear in the content upload page. In order to get rid of them simply upload the latest version of that file to mofacts. It will automatically remove the duplicates now.
