### ISSUE TITLE
Countries Test: No images, no countdown

### ISSUE THREAD

**Issue by lizrose17** [memphis-iis/mofacts-ies#1104]
The images for several items did not load, just a picture icon.

On items the user got incorrect, the countdown timer was not there.

Package Countries Tutor.zip uploaded
![Screenshot (16)](https://user-images.githubusercontent.com/88344486/230991708-1679caa4-4e40-483c-8fd8-26a7f8662e80.png)
![Screenshot (17)](https://user-images.githubusercontent.com/88344486/230991725-16155bc3-03ea-484f-a7c0-86b9555b86c5.png)

**Comment by imrryr** [comment]
Liz will reupload to confirm the files are actually still present on the server.

**Comment by MegaGeese** [comment]
For the tooltips, they can easily be removed

**Comment by MegaGeese** [comment]
Looking at the zip file it does look like certain pictures are missing such as: "AC-locator-map.jpg"

**Comment by imrryr** [comment]
That's too bad that some are missing. I see that Liz does not have the one you mention, however, why is Croatia not working... In the zip and stim file it is HR-locator-map.jpg... Do you have any easy way to determine which files are missing from the directory that were present in the stim file?

**Comment by MegaGeese** [comment]
I wrote a script for finding all the missing files. Here are the referenced files that don't appear in the package
AC-locator-map.jpg
XQ-locator-map.jpg
XO-locator-map.jpg
UM-locator-map.jpg

**Comment by imrryr** [comment]
Great, then I can retrieve them from the CIA website; however, as noted, Croatia is not on the list.

**Comment by MegaGeese** [comment]
That part I'm still looking into. From the console its actually looking for a 'gif' file but there are no gifs uploaded in the package.
