### ISSUE TITLE
Theme button is unstable

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1106]
**Describe the bug**
Meng reports one problem is that the "theme" bar is always jumping up and down in the middle of the screen which is annoying.

Please make an additional change, which is not to allow the theme button when a user is at any of these links with 
https://staging.optimallearning.org/experiment/
in the URL. The experiments should not have this teacher. Ideally, the theme could be set in the tdf setspec in such cases if it were used.

**Comment by JRustyHaner** [comment]
@imrryr The theme button is being moved a settings menu in the next iteration, but that can be implemented as well.

**Comment by imrryr** [comment]
The main thing is we need it fixed ASAP (highest priority ) for the experiment. It is also nice to have it in the setspec, but that can be another issue if it takes more time. Also, there should not be a signup button on this page. There is no signing up for /experiment/ links like this.

Finally, I also note that the instruction for participants... enter your "Amazon Turk ID or User ID"... has gone missing... the old text should still appear in the field like on this page: https://mofacts.optimallearning.org/experiment/indradicals
