### ISSUE TITLE
No images for some items, no countdown if gotten wrong

### ISSUE THREAD

**Issue by lizrose17** [memphis-iis/mofacts-ies#1111]
Package Countries Tutor 1.zip uploaded

Images did not load for some items; it either showed a picture icon, or a link. Additionally, when I got items wrong, the countdown did not show.
![Screenshot (18)](https://user-images.githubusercontent.com/88344486/232352948-ec4fe8e0-d1c5-41da-8d50-3fe663b5b9ed.png)
![Screenshot (19)](https://user-images.githubusercontent.com/88344486/232352966-f430ddd8-bf14-4a1f-ba47-264ad19795a2.png)
![Screenshot (20)](https://user-images.githubusercontent.com/88344486/232352970-21d45a15-c35c-4b65-b548-fe5aac52c020.png)
![Screenshot (21)](https://user-images.githubusercontent.com/88344486/232352974-58d2d7fd-4436-43e5-8917-942425c63bcb.png)
![Screenshot (22)](https://user-images.githubusercontent.com/88344486/232352979-72213750-4a2b-4648-9c4d-69059d40fb44.png)

**Comment by MegaGeese** [comment]
@lizrose17 this fix will require you to re-upload the package. 
Also as i cannot find the bug causing the timer to break, I made it so that it will create an error in console when it happens. If you can upload that here when it happens I would appreciate it

**Comment by lizrose17** [comment]
@MegaGeese I re-uploaded the package Countries Tutor1.zip. When I tried to practice, nothing showed up on the screen and I got this error report in the Console.
![Screenshot (27)](https://user-images.githubusercontent.com/88344486/232842155-c84981d6-973e-4673-9294-1c11ab7888f5.png)

**Comment by MegaGeese** [comment]
@lizrose17 I've fixed this however the countdown bug might still be present. Can you take a look when you have a chance?

**Comment by imrryr** [comment]
@MegaGeese So the fix for this is on staging now? Or ready for the next release?

**Comment by imrryr** [comment]
@MegaGeese Also Liz informed me yesterday her tests were all showing the countdown now.

**Comment by MegaGeese** [comment]
@imrryr thank you for letting me know. The problem was that when a package is uploaded with fewer stims than a previous version then the cluster mapping (generated by shuffleclusters) becomes invalid. This is something Im still working on but i had fixed it in the database for liz's so she could continue testing while I looked into it.

**Comment by imrryr** [comment]
OK, but I still don't know whether the fix for the new error is live or ready for code review exactly... @MegaGeese
