### ISSUE TITLE
Bug in study recording

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1120]
**Describe the bug**
As shown below, study trials during model practice (maybe always) are getting marked as "correct" this is clearly not correct, since only tests and drills have a value for Outcome. There is no outcome to measure for a study trial... How was it originally marked? Don't recall, but it should be blank or "study" I think. 

This error is currently propagating into the model since the correct responses are getting counted in both the score AND the model statistics used to compute practice. This makes the optimization wrong also, and the score... Not sure if there are any secondary problems since bad data is being fed into the processes.

Anon Student Id	Session ID	Condition Name	Condition Type	Condition Name	Condition Type	Condition Name	Condition Type	Condition Name	Condition Type	Level (Unit)	Level (Unitname)	Level (Unittype)	Problem Name	Step Name	Time	Selection	Action	Input	Outcome	Student Response Type	Student Response Subtype	Tutor Response Type	Tutor Response Subtype	Hint Level	Feedback Type	Feedback Text	KC (Default)	KC Category(Default)	KC (Cluster)	KC Category(Cluster)	CF (Dialogue History)	CF (Audio Input Enabled)	CF (Audio Output Enabled)	CF (Display Order)	CF (Stim File Index)	CF (Set Shuffled Index)	CF (Alternate Display Index)	CF (Stimulus Version)	CF (Correct Answer)	CF (Correct Answer Syllables)	CF (Correct Answer Syllables Count)	CF (Display Syllable Indices)	CF (Overlearning)	CF (Response Time)	CF (Start Latency)	CF (End Latency)	CF (Feedback Latency)	CF (Review Entry)	CF (Button Order)	CF (Item Removed)	CF (Note)	CF (Entry Point)
A68OW6A2KBYSC	Thu, 20 Apr 2023 IndividualOptimChineseRadicalsPhilv2.json	tdf file	IndividualOptimChineseRadicalsPhilv2.json	xcondition		schedule condition	N/A	how answered	timeout	1	Learning unit 1	model	{"text":"","clozeText":"è€ in English"}	{"text":"","clozeText":"è€ in English"}	1.682E+12			[timeout]	correct	HINT_REQUEST	C	HINT_MSG		0	simple				530115		null	FALSE	FALSE	0	0	0		0	old	old	1		FALSE	1.682E+12	-1	-1	6002			FALSE		undefined/undefined
A68OW6A2KBYSC	Thu, 20 Apr 2023 IndividualOptimChineseRadicalsPhilv2.json	tdf file	IndividualOptimChineseRadicalsPhilv2.json	xcondition		schedule condition	N/A	how answered	timeout	1	Learning unit 1	model	{"text":"","clozeText":"çŽ‰ in English"}	{"text":"","clozeText":"çŽ‰ in English"}	1.682E+12			[timeout]	correct	HINT_REQUEST	C	HINT_MSG		0	simple				530087		null	FALSE	FALSE	0	1	1		0	jade	jade	1		FALSE	1.682E+12	-1	-1	6008			FALSE		undefined/undefined
A68OW6A2KBYSC	Thu, 20 Apr 2023 IndividualOptimChineseRadicalsPhilv2.json	tdf file	IndividualOptimChineseRadicalsPhilv2.json	xcondition		schedule condition	N/A	how answered	timeout	1	Learning unit 1	model	{"text":"","clozeText":"ç”Ÿ in English"}	{"text":"","clozeText":"ç”Ÿ in English"}	1.682E+12			[timeout]	correct	HINT_REQUEST	C	HINT_MSG		0	simple				530091		null	FALSE	FALSE	0	2	2		0	life	life	1		FALSE	1.682E+12	-1	-1	6001			FALSE		undefined/undefined
A68OW6A2KBYSC	Thu, 20 Apr 2023 IndividualOptimChineseRadicalsPhilv2.json	tdf file	IndividualOptimChineseRadicalsPhilv2.json	xcondition		schedule condition	N/A	how answered	keypress	1	Learning unit 1	model	{"text":"","clozeText":"è€ in English"}	{"text":"","clozeText":"è€ in English"}	1.682E+12			old	correct	ATTEMPT	C	RESULT		0	simple	Correct.			530115		null	FALSE	FALSE	0	0	0		0	old	old	1		FALSE	1.682E+12	8595	9907	754			FALSE		undefined/undefined
A68OW6A2KBYSC	Thu, 20 Apr 2023 IndividualOptimChineseRadicalsPhilv2.json	tdf file	IndividualOptimChineseRadicalsPhilv2.json	xcondition		schedule condition	N/A	how answered	keypress	1	Learning unit 1	model	{"text":"","clozeText":"çŽ‰ in English"}	{"text":"","clozeText":"çŽ‰ in English"}	1.682E+12			jade	correct	ATTEMPT	C	RESULT		0	simple	Correct.			530087		null	FALSE	FALSE	0	1	1		0	jade	jade	1		FALSE	1.682E+12	1859	2445	753			FALSE		undefined/undefined

**Comment by MegaGeese** [comment]
Looking back through the code changes I can see that study trials have always been recorded with the outcome as 'correct'. They are differentiated by the 'studentResponseType' being set to 'HINT_REQUEST' and 'tutorResponseType' to 'HINT_MSG' as opposed to 'ATTEMPT' and 'RESULT'. 

I can change how it is reported to be more accurate in the history and in the performance report. 

It looks like the probability calculations are still correct as they are calculated from the component state instead of the history.

**Comment by imrryr** [comment]
Okay well this is a long-standing bug then. Thanks for evaluating things.
We probably haven't used initial studies since it's been put in JavaScript.
Let's just leave the outcome blank for now when it is a study since
semantically a study cannot be correct.

**Comment by MegaGeese** [comment]
For the performance report. Do you want the Time and Count to increment with studies?

**Comment by imrryr** [comment]
Definitely. The time is just the time in the unit, it should always count
everything. Similarly the count is a count of all trial types. They are not
sensitive to the outcome. Thanks for asking.

**Comment by imrryr** [comment]
I guess I shouldn't say for all in the unit I should say for all so far
unless there's a reset...
