### ISSUE TITLE
MoFACTs doesn't gracefully deal with server storage management

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1129]
**Describe the bug**
Can't login with either method

**Comment by MegaGeese** [comment]
Its back up now. Looks like the 50GB disk had filled up and crashed mongo. I'm investigating where the majority of space is being used.

**Comment by MegaGeese** [comment]
I've cleared about 10GB of data from outdated log files and old builds so it is stable now.

**Comment by imrryr** [comment]
Excellent

**Comment by imrryr** [comment]
Long term solution ideas?

**Comment by imrryr** [comment]
Chron job for log removal.... Email warning to admin

**Comment by imrryr** [comment]
Admin control panel show remaining storage
