### ISSUE TITLE
Upgrade error reporting/logging

### ISSUE THREAD

**Issue by andrewtackett** [memphis-iis/mofacts-ies#113]
- Prune unnecessary console logging for error reports
  - Possibly set up multiple logging levels
- Create second stream of logs for general navigation/user feature tracing

**Comment by imrryr** [comment]
isn't this a refactor item?

**Comment by andrewtackett** [comment]
@imrryr 

Technically yes.  Though most of the items in the running refactor list are fairly low priority and are more for code health than performance.  This directly affects performance and should be more highly prioritized

**Comment by andrewtackett** [comment]
@imrryr Actually scratch the last post.  I thought this was a different issue.  I'll merge this into the refactoring list.
