### ISSUE TITLE
Login fails here: https://staging.optimallearning.org/experiment/indradicals

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1139]
**Describe the bug**
It doesn't seem to matter what I login with.... Screenshot after the attempt, appears to be looping back...
![Inbox (1) - imrryr@gmail com - Gmail - Google Chrome 5_9_2023 4_46_00 PM](https://github.com/memphis-iis/mofacts-ies/assets/13023147/8acde31e-adfd-4e5a-86a5-32bc1e46146c)

**Comment by MegaGeese** [comment]
fix deployed
