### ISSUE TITLE
Study trial does not work and get stuck on first trial

### ISSUE THREAD

**Issue by mengcaopsy** [memphis-iis/mofacts-ies#1143]
I tested the he radicals experiment at [https://mofacts.optimallearning.org]. The first trial is a study trial which should show the English meaning of the stimulus but it does not. It also gets stuck on the first trial and can't go on to the next trial.

![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/fce17e41-2b2c-4cd9-a183-5318bd75025d)

**Comment by MegaGeese** [comment]
@mengcaopsy this should be fixed now. Can you reupload the tdf/stim set and try again?

**Comment by mengcaopsy** [comment]
Yes, it works now. The participant mode (testing using experiment link) is fine. But the teacher mode has a window comes out each trial like below. After I click OK, it can go to the next trial. 
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/71b584e6-155b-4815-8921-81f6e0fdab5e)

**Comment by mengcaopsy** [comment]
Another problem is when it came to the survey questions. After the first training session and the instruction about 4 survey questions, the page shows loading or nothing. It seems that it can't load survey questions. Below are the screenshots I tried twice.

![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/c2efd143-95aa-46ba-8856-07a6dd1cf13b)

![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/f0b8a9ee-e6d4-499a-898b-b4dd45a86e33)

**Comment by imrryr** [comment]
@MegaGeese Please tell us if we need multiple issues.
