### ISSUE TITLE
User Progress Errors Out Sometimes

### ISSUE THREAD

**Issue by andrewtackett** [memphis-iis/mofacts-ies#115]
getStimCluster currentTestingHelpers.js:77
    fastGetStimCluster unitEngine.js:197
    initializeActRModel unitEngine.js:383
    initImpl unitEngine.js:724
    init unitEngine.js:122
    create unitEngine.js:78
    createModelUnit unitEngine.js:97
    getcardProbs studentReporting.js:228
    drawCharts studentReporting.js:660
    updateDataAndCharts studentReporting.js:564
    change #tdf-select studentReporting.js:520

Selected a new multiTdf

**Comment by imrryr** [comment]
This may be related to the tasks I just posted on 7/21

**Comment by andrewtackett** [comment]
It was related.

Fixed with commit: 7baf65f835a20c6be797135907255d7f45be79d1

The student reporting page wasn't setting up cluster mapping in the right order with respect to engine initialization which often, though not always wouldn't matter.
