### ISSUE TITLE
Can't load images correctly on MoFaCTS

### ISSUE THREAD

**Issue by mengcaopsy** [memphis-iis/mofacts-ies#1165]
I uploaded the image files in the zipped folder and call out it in the tdf using code like below.
 "unitinstructions": " <p>Below is a figure showing the pitch contours of the tones. <strong>Please wait for a few seconds if it does not appear immediately.</strong><br><img src=\"tones.jpg\"> ". 
The images can't be shown correctly.
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/0505bc3c-fbe7-4448-8c55-9448299b342e)
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/dd0dedd0-c751-44f8-a676-605ec68a0ebd)

**Comment by awindsor** [comment]
I suspect that the WebMediaPlayers are not being closed and they are
accumulating to where they hit the Chrome limits:

Chrome 92 has introduced a limit on number of audio and video tags that can
> be allocated in a particular tab. 75 for desktop browsers and 40 for mobile
> browsers.


Alistair
