### ISSUE TITLE
Work on/think about feature flags

### ISSUE THREAD

**Issue by andrewtackett** [memphis-iis/mofacts-ies#117]
For a lot of code we only want it to run for a specific experiment or in specific circumstances.  Technically tdf tags are feature flags but it might be worth it to consider a different way of doing things during the refactor.

**Comment by imrryr** [comment]
I suggest we close this unless you have a specific proposal. I'm really happy to think about a specific proposal though....

**Comment by imrryr** [comment]
I suggest we close this unless you have a specific proposal. I'm really happy to think about a specific proposal though....
