### ISSUE TITLE
package won't run practice anymore

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1173]
![image](https://github.com/memphis-iis/mofacts-ies/assets/13023147/a1747d2b-e401-449a-9755-a2ea8946da97)

Here is the package. the screenshot is from right after starting it...
[Countries Tutor1.zip](https://github.com/memphis-iis/mofacts-ies/files/11886973/Countries.Tutor1.zip)

**Comment by MegaGeese** [comment]
how long ago was the package uploaded?

**Comment by imrryr** [comment]
3pm...

**Comment by MegaGeese** [comment]
@imrryr i've fixed the error. There also seems to be an issue in the TDF's second unit. The learning session lists a clusterList of 0-234 but there are only 233 stims in the stim file.

**Comment by imrryr** [comment]
Is it possible that it doesn't crash the system despite being wrong? I have RAs say this system worked.
