### ISSUE TITLE
Blank page for the tone learning experiment

### ISSUE THREAD

**Issue by mengcaopsy** [memphis-iis/mofacts-ies#1191]
I was testing the tone learning experiment but had the blank page in the beginning. This is a new bug. It used to work before.

![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/bcb1ab32-46d0-4727-8372-975de5ce7a78)

**Comment by MegaGeese** [comment]
@mengcaopsy can you attach the package you uploaded for this experiment?

**Comment by mengcaopsy** [comment]
Here it is. This one has a root file with 4 conditions.
[adaptive 100 participants.zip](https://github.com/memphis-iis/mofacts-ies/files/12073413/adaptive.100.participants.zip)
I also tried a simpler version without the root file. It also have the same problem.
[another 100 participants1 with no subfolders (2).zip](https://github.com/memphis-iis/mofacts-ies/files/12073436/another.100.participants1.with.no.subfolders.2.zip)

**Comment by MegaGeese** [comment]
@mengcaopsy im building this now. Once its updated you'll need to reupload the package. Then the experiment should run properly

**Comment by MegaGeese** [comment]
please try now

**Comment by mengcaopsy** [comment]
@MegaGeese Yes, it works now. Thank you!
