### ISSUE TITLE
Getting stuck on Tone 4 

### ISSUE THREAD

**Issue by mengcaopsy** [memphis-iis/mofacts-ies#1193]
When I tested the tone learning experiment, it gets stuck on Tone 4 examples. No sounds were played and can't go on to the next trial. It played Tone 1, 2, 3 examples correctly.
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/c98c051c-d4b7-4a24-8947-d7cc69b6349d)

**Comment by JRustyHaner** [comment]
@mengcaopsy the error shows that the file type is not supported for playing in the browser. 

Some audio files are compressed differently and the browser won't play them. 

Could you send me the files?

**Comment by mengcaopsy** [comment]
The audio files are all wav files. They are in the zipped file.
[adaptive 100 participants.zip](https://github.com/memphis-iis/mofacts-ies/files/12074629/adaptive.100.participants.zip)

**Comment by imrryr** [comment]
Meng, did you see this error multiple times? Does it reproduce?
