### ISSUE TITLE
Assets don't upload (production)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1205]
I uploaded the attached files, and they did not show until I put them
[Chapter_9.zip](https://github.com/memphis-iis/mofacts-ies/files/12243749/Chapter_9.zip)
 in the zip file. Is that currently required? The instructions imply it should be fine to do them separately... we could choose to change the instructions if zip is better workflow

**Comment by MegaGeese** [comment]
Yes. How its currently coded it only links assets to a stim/tdf file when they are uploaded together via the package uploader.

**Comment by imrryr** [comment]
OK, lets change the instructions to just say zip files .

So, instead of: "This manages your assets, lessons, and stimuli for use in experiments. It can also upload packaged zip files with TDF/stim/asset combinations. You may use video, audio, or image files as well. Please wait until a prompt is given to navigate to a new page."

Say: "This screen allows uploading zip files with TDF/stim/asset combinations. You may use video, audio, or image files as well." 

by the way what does this mean exactly... its really kinda vague. Will it be broken if they navigate away?
"Please wait until a prompt is given to navigate to a new page."

**Comment by imrryr** [comment]
Also, on the button it should say "Upload Zip Files" if other asset files will not work it should not say "Upload Asset Files"

**Comment by JRustyHaner** [comment]
@imrryr I'm going to split this issue, one for staging, one for production

**Comment by imrryr** [comment]
I have no idea why you would split the issue because I don't want it fixed on staging that would be a waste of time.

**Comment by imrryr** [comment]
Maybe I wasn't clear enough in meeting but basically the idea now is that we only make changes in production that are absolutely needed for an experiment that staging is not ready for. @JRustyHaner @MegaGeese

**Comment by JRustyHaner** [comment]
@imrryr No, you were clear. The change was trivial so I wanted to give you the option.

**Comment by JRustyHaner** [comment]
@imrryr No, you were clear. The change was trivial so I wanted to give you the option.

This reminds me that in the future we may want to specify when writing reports if we are talking about the full or mini deployment when it comes to the staging version... UI changes affect both of course, but if there is a bug in full vs mini that would be helpful.

**Comment by imrryr** [comment]
got it, mark the bugs for mini or full
