### ISSUE TITLE
Restore Turk functions

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1216]
Previous to the grant we had a Turk interface that showed various details like the amount of practice and also allowed the sending of a bonus. It appears to be in the code still, just not active. How much work would it be to make it active, so we could get the table of Turk users and do Turk functions like bonusing as we could before.

**Comment by MegaGeese** [comment]
It will take a bit of effort to reimplement this. While the code is still there for the most part, certain key pieces were lost in the migration from mongo to postgres and back it seems. 

From what I see it looks like it would take about a week to reimplement all the features.

**Comment by imrryr** [comment]
OK, I'd like to get this restored then please. It was used a lot before and really speeds up the process of managing Turk works. I have some old versions of the code if we are missing stuff.

**Comment by imrryr** [comment]
Have you looked at the stale branches already. I have a version that is data 2016 that maybe even older than the stale versions and has Turk files. Do you know what filenames would have the lost code? @MegaGeese
