### ISSUE TITLE
radicals experiment won't work on staging mini

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1219]
After upload, it doesn't show as uploaded. Here is the zip I used.
[Chinese radicals final version (2).zip](https://github.com/memphis-iis/mofacts-ies/files/12330475/Chinese.radicals.final.version.2.zip)

**Comment by imrryr** [comment]
Also, there is a phantom button on the lesson select screen... not sure if it is related. Pressing it produces the second screen here. 
![Screenshot (94)](https://github.com/memphis-iis/mofacts-ies/assets/13023147/dc927f2d-c4dc-4074-b2b9-861b6c881796)
![Screenshot (95)](https://github.com/memphis-iis/mofacts-ies/assets/13023147/8fe564eb-c579-4400-84c4-1bec76f34242)

**Comment by JRustyHaner** [comment]
looks like it is an error of the packaging uploader. I'm checking it out.

**Comment by imrryr** [comment]
Currently it gets this far, then it gets stuck at this screen and never moves forward
![image](https://github.com/memphis-iis/mofacts-ies/assets/13023147/aaa2b201-bf1b-45a0-b09b-e7ba70857643)
![image](https://github.com/memphis-iis/mofacts-ies/assets/13023147/8a2ba445-c212-4856-9459-9ae6760154b5)
