### ISSUE TITLE
Chapter 9 missing for new user, but appears for progress report (weirdly)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1225]
**Describe the bug**
![image](https://github.com/memphis-iis/mofacts-ies/assets/13023147/7bb17ef9-46e3-4ed8-8eae-8152a5f5b61c)

**Comment by imrryr** [comment]
Also, Chapter 9 appears twice...

**Comment by JRustyHaner** [comment]
This has been fixed, as far as I've tested
