### ISSUE TITLE
Too many buttons

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1226]
**Describe the bug**
After typing your signup info, there are two buttons, I think there should only be one. I think right now signing in here actually signs up, and signup doesn't work. Probably neither label is great, and the text on the page should say "lets signup"... And a single button could say "submit" after they enter info.

My main problem right now, is that there is no reason for 2 buttons.
![image](https://github.com/memphis-iis/mofacts-ies/assets/13023147/14db6695-8c82-4ebe-9d20-fb38b135def2)

**Comment by JRustyHaner** [comment]
@imrryr I'll clean the sign up page to be a bit less confusing t and test functionality.

**Comment by JRustyHaner** [comment]
![image](https://github.com/memphis-iis/mofacts-ies/assets/46696077/4ea0a663-b7b3-4e05-aaed-81a81538ba8f)

Is that design and wording a better solution for you?

**Comment by imrryr** [comment]
That's crystal clear now... Thank!
