### ISSUE TITLE
New experiment doesn't appear in TDF Practice+ 

### ISSUE THREAD

**Issue by Wei940127** [memphis-iis/mofacts-ies#1233]
**Describe the bug**
Single .json cannot be uploaded. Only the .zip works. However, after successfully uploading the .zip file, the corresponding experiment didn't appear in the TDF Practice +. 
![image](https://github.com/memphis-iis/mofacts-ies/assets/54991536/81738bc6-4d93-482c-aac5-c18fc057e7b2)
[Meaningfulnessstims.zip](https://github.com/memphis-iis/mofacts-ies/files/12563857/Meaningfulnessstims.zip)

**Comment by imrryr** [comment]
Stim file does validate in json tools

**Comment by JRustyHaner** [comment]
@mengcaopsy @imrryr Could you please email us the package?

**Comment by imrryr** [comment]
@Wei940127 please put the package in a comment for the issue. Rusty this is actually Weis work not Mengs

**Comment by imrryr** [comment]
I'm thinking that this is some bug in the stimulus loading... Or the stimulus file...

**Comment by JRustyHaner** [comment]
When we have the package we can check it locally so we can monitor the server side logs.

**Comment by imrryr** [comment]
Argh, we can't replicate the bug now. Not sure what was happening. Closing the issue.
