### ISSUE TITLE
Doesn't show Turk screen for TDF owner

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1238]
![Screenshot (125)](https://github.com/memphis-iis/mofacts-ies/assets/13023147/933ea889-114f-475c-b7d0-af25cf11f551)

**Comment by imrryr** [comment]
Also, how does it detect the assignment ID? It seems to be necessary to distinguish what we are approving....

**Comment by MegaGeese** [comment]
Looks like the docker version of staging doesnt have any of the old data that was on the database prior to August 28th. I can look in to finding a backup or importing the data from prod for testing.

**Comment by imrryr** [comment]
None of that data is needed, unless you need it for testing

**Comment by imrryr** [comment]
I was just going to test with the tdf that we are setting up for turk that is already there

**Comment by MegaGeese** [comment]
I was able to test it against the prod data and it was working.
