### ISSUE TITLE
Simplified feedback with prior response.

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1239]
I'm not sure the best way to code this, but we need a simplified trial screen for language learning. It could be coded as options to the current screen, or it could be a new type of screen for language learning. Perhaps it should apply to "text" but not effect the "clozetext" type. We can talk about it Monday. After a meeting with Meng, Wei, and Hannah, we settled on this design. The meeting was initiated after we examined the radicals experiment in the new interface and found some problems when actually doing the practice. We were mainly concerned with how components unrelated to learning drew attention away from learning, but also wanted to make sure the prompt and response were next to each other.

![Screenshot (127)2](https://github.com/memphis-iis/mofacts-ies/assets/13023147/33937ace-256c-4864-8790-44bec5775dbf)

As you can see, the new screen has the green score above as before (thanks for making it static). The prompt and response of the feedback should look identical to the study trial screen. This means the study trial screen needs the Continue message when it is present on the drillfeedback screen.

![Screenshot (127)](https://github.com/memphis-iis/mofacts-ies/assets/13023147/e45b3d66-f3dc-4643-a9a2-dd4f6cfb6f5f)

The only additional information on the review screen will now be the student's incorrect response. "Your answer: xxxx " and "Incorrect" in a warning yellow). 

Finally, when correct, the word "Correct" should be in light green, and there is an unneeded "." and the bar underneath the word correct should be removed. Furthermore, the students typed response should be kept during the period the word correct is on the screen. 

![Screenshot (128)](https://github.com/memphis-iis/mofacts-ies/assets/13023147/ea965bfe-11dd-42e7-83d7-6ed98a325be5)

**Comment by imrryr** [comment]
@JRustyHaner, is this running now, since it isn't working when I test it...

**Comment by JRustyHaner** [comment]
@JRustyHaner no, it hasn't been reviewed and pulled yet.

**Comment by JRustyHaner** [comment]
It's PR here: https://github.com/memphis-iis/mofacts-ies/pull/1243

**Comment by imrryr** [comment]
ahhh... ok, well I will test the model with the current version until this heads to staging. Are we also waiting on something like that for production for Meng?  @JRustyHaner

**Comment by JRustyHaner** [comment]
@imrryr No, I was waiting to make sure that August deployed it should there be something specific that needed to be done. I can go ahead if you'd like.

**Comment by MegaGeese** [comment]
I saw y'all commenting on the PR page and was waiting for that conversation to end before it got pulled.

**Comment by imrryr** [comment]
Please tell us that next time. I saw a pull request and was awaiting deployment before commenting.

**Comment by imrryr** [comment]
There are some bugs and some spec misses here. Detailed in this video, including flashing bars, delayed countdown, screen organization issues, and extra components on the experiment screen. 

1. hesitation in study countdown but otherwise looks nice
2. timer bar flashing for no reason when set to false for correct and incorrect review
3. countdown for drills showing when set to false
4. review is not organized with the response below the prompt just like the study trials (same size, same grey box below)
5. it is allowing the menu actions in the top right despite being in experiment model with no functions supposed to be available...

https://github.com/memphis-iis/mofacts-ies/assets/13023147/073e6618-9185-4661-9105-2fcec37db9bb

**Comment by imrryr** [comment]
@JRustyHaner Do you know when this will be completed? It's been a bit, and it is highest priority, please.

**Comment by JRustyHaner** [comment]
@imrryr working on it now. I had a deadline come up last week for another project.

**Comment by imrryr** [comment]
As we discussed for that case of timeouts, please list the response as 

partial answer if any [timeout]
