### ISSUE TITLE
Stimuli do not appear in the training session for the tone experiment

### ISSUE THREAD

**Issue by mengcaopsy** [memphis-iis/mofacts-ies#1242]
I was running experiment with the link: https://mofacts.optimallearning.org/experiment/adaptivetonetraining

The stimuli of the training session do not appear any more.
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/35ff132b-f0b3-4599-91a1-efe49ff55db6)

**Comment by mengcaopsy** [comment]
One participant also reported that she had extremely slow loading of the stimuli during training before it totally broke down. Below is a screenshot of the latency during the training trials she had. For the feedback, it should be just 1000 or 6000, but here it seems much longer. Not sure if this is caused by the same problem.
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/1975a3cf-c1b2-4921-ab49-c7863bf32bec)

**Comment by JRustyHaner** [comment]
The error:

Exception while invoking method 'getProbabilityEstimatesByKCId' MongoError: Executor error during find command :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.

**Comment by JRustyHaner** [comment]
@imrryr 
$sort is subject to the 100 megabyte memory usage limit, but is able to write temporary files to disk if additional space is required.

To be fair, August has a comment there:  
 //theres gotta be a more efficient way to do this

**Comment by imrryr** [comment]
OK, what are you talking about. Do what? Sounds like something stupid is in the code.  Do we jsut need to wipe the data to fix it temporarily?

**Comment by imrryr** [comment]
I'm coming in now. I'll stop by.
