### ISSUE TITLE
intertrialtimer

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1248]
We need a millisecond timer for the period when the intertrial message is showing.

**Comment by JRustyHaner** [comment]
@imrryr in the current logic, intertrial only displays when the card sets displayReady to true . If the card doesn't take time to go through the card logic, then the intertrial will never actually display.

The intertrialmessage is currently set either in unit level delivery params, or tdf level delivery params.

Proposed change:
DisplayReady should only be set to true when the interttrial timer has elapsed, measured from the time intertrial message is displayed to the participant.  The timer duration would be set in This would force the intertrial message to be displayed for at least the time in milliseconds from the delivery params. A countdown text, countdown bar, both, or none could be displayed based off of uiSettings from the other pull request.

**Comment by imrryr** [comment]
OK, we need to talk abou this, but it is lower priority issue, so lets get the system fixed and deployed on both staging and production. I can't do testing now and Meng is waiting as well.

If the suggestion above is easy, you could roll it in, but really we need to think about the priority order a bit.

**Comment by JRustyHaner** [comment]
I was waiting for a couple of things from August. Building staging now.
