### ISSUE TITLE
Graceful termination when no available items

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1249]
Currently it forces a spacing of 2, this new feature allows that to be turned off (display paramerter "forcespacing" false), and if all items are marked p.available=="false" it will move to the next unit automatically.

**Comment by JRustyHaner** [comment]
it turns out that if you set p.available during your probabilty function, it will remove it from the cards that are calculated.

**Comment by imrryr** [comment]
I understand Rusty, that's the basis of why I need this request. If all but 2,1, or 0 are left marked not false, the system fails.
