### ISSUE TITLE
p.available types

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1250]
Make 4 options for p. available "false", "drill", "study", and "test" which force the "distance" selection algorithm to give the trial type, or false removes the item from selection at all.

**Comment by MegaGeese** [comment]
What do you mean by "force the "distance" selection algorithm to give the trial type"? 

Is p.available being set by the probability function in this case or is it being set by mofacts for use in the probability function?

**Comment by imrryr** [comment]
This is much less priority than getting production set up for Meng. Please help me get her set up and I will try to answer these when I have time.

**Comment by imrryr** [comment]
yes, I just mean cause the trial to be displayed according to the setting of p.available

**Comment by imrryr** [comment]
@MegaGeese is this deployed? It appears it might be

**Comment by JRustyHaner** [comment]
@imrryr it is, I'm closing this
