### ISSUE TITLE
Error blocking experiment load

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1258]
Something about the uisettings...

"uiSettings": {
          "displayReviewTimeoutAsBarOrText": "text",
          "displayReadyPromptTimeoutAsBarOrText": false,
          "displayCardTimeoutAsBarOrText": "text",
          "displayTimeOutDuringStudy": true,
          "displayUserAnswerAtTop": true,
          "displayPerformanceDuringStudy": true,
          "displayCorrectAnswerInCenter": false,
          "onlyShowSimpleFeedback": true,
          "incorrectColor": "darkorange",
          "correctColor": "green"
        }
[OptimTester1.zip](https://github.com/memphis-iis/mofacts-ies/files/12768740/OptimTester1.zip)
![Screenshot (139)](https://github.com/memphis-iis/mofacts-ies/assets/13023147/ca911019-9f3d-4835-89af-30a67be75a5b)

**Comment by JRustyHaner** [comment]
@imrryr thats a typo on my part.

**Comment by JRustyHaner** [comment]
@imrryr building and deploying the fix now

**Comment by JRustyHaner** [comment]
@imrryr deployed
