### ISSUE TITLE
Gives study trials during practice using survey question stims 

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1261]
There is some bug in the database, probably. It gives survey questions and items that are not in the selection set as practice items. Very weird!

The funny thing is this same tdf worked great yesterday after the first upload, after multiple overwrites, I wonder if the database ids are not in sync with the actual values. No idea why that would happen.

**Comment by MegaGeese** [comment]
do you know which TDF is causing this? If its multiple could you list the ones you know have an issue?

**Comment by imrryr** [comment]
[OptimTester1.zip](https://github.com/memphis-iis/mofacts-ies/files/12770690/OptimTester1.zip)
It is this one I reuploaded afternoon to check the uisettings.... yesterday it worked before a couple changes to the uisettings, but the uisettings can't be causing the wrong item to be displayed...

**Comment by imrryr** [comment]
normally reuploads have worked fine for this package.... not clear what changed.

**Comment by imrryr** [comment]
How is this one coming please with the uploader update to fix this? @MegaGeese after it is finished please deploy it to staging. 

Meng needs us to wait to deploy it to production (assuming this also fixes the birds issues), so don't deploy it to production until she says please. @mengcaopsy

**Comment by MegaGeese** [comment]
Turns out it wasnt the file uploader. I've posted a PR for the fix but I can also make a new enhancement for the new package uploader since it will function better.
