### ISSUE TITLE
Current Readme

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1266]
Is this file current? https://github.com/memphis-iis/mofacts-ies/blob/main/README.md

Also, where is the license for MoFaCTS? We should be posting it somewhere. Where is standard? Is it there please?

**Comment by JRustyHaner** [comment]
I have a end user agreement I drafted for Oji you could look over.

If it's open source, then GPL2 or Creative Commons are normal licences.

**Comment by JRustyHaner** [comment]
No, we use docker now to deploy. I will rewrite it

**Comment by imrryr** [comment]
Gosh I thought we had a license somewhere, but no matter GPL2 seems right after reading it over. Can we add that in some license file or whatever is done? And tell me where I can reference it in the grant report? Also, sure, send the end user agreement to me...

**Comment by imrryr** [comment]
Also, for the readme, we could just provide links to the wiki information so that we don't have to update them both if it changes at all....

**Comment by JRustyHaner** [comment]
@imrryr  Here is the EULA for Oji:

https://ojis-journey.com/terms.html
