### ISSUE TITLE
Tables columns

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#127]
Ideally, table columns would not flush left or right, and be sensitive to the length of the contents, up to some reasonable limit for the typical field contents

**Comment by imrryr** [comment]
What is the appropriate way to add this to the specification for all the web pages

**Comment by wscarter** [comment]
One option would be to have a separate specification (either document or section) to define just UI components and their appearance/behavior (when resizing, populating, etc.).  I don't know how much revision will need to be done to the UI itself after Amy gives her input and whether UI specs should be drafted before then, but I would guess in general we'd want to approach it as atomically as possible (e.g., tables should look like [this] and do [thing] when there are [y] columns), rinse and repeat for other components like buttons, input fields, etc.  I think a UI specification is probably a complex enough topic to warrant a meeting and some discussion.

**Comment by andrewtackett** [comment]
I agree with Wes.  A separate UI spec makes sense and a meeting seems like it would be useful

**Comment by imrryr** [comment]
We decided to just fix the obvious teacher report table that is flush right for this issue to be closed now
