### ISSUE TITLE
OverallOutcomeHistory appears wrong

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1283]
Tracking it in the console, after the second study,  during the third trial, it shows 1 in the overallOutcomeHistory, and continues to put 1's for each study.

So, it appears the outcome is logged late, lagged by 1 trial, and that should not happen, also study is not supposed to be logged as an outcome at all. So that is also a problem

**Comment by MegaGeese** [comment]
This is a simple fix. It can also be applied to prod since its a 1 line change

**Comment by imrryr** [comment]
You can apply it to prod, but really it might be unneeded. Perhaps we can get staging changes deployed today since it is simple. This 1 line caused both the study logging problem and the 1 trial recording lagging problem?

**Comment by MegaGeese** [comment]
I'll have to take a deeper look at the lagging issue. I'm not sure why that's happening as it should be updated as soon as the user's answer is evaluated for correctness. And before it's logged

**Comment by imrryr** [comment]
So, I see these values for the last participant I did with 5 trials, failing on the 4th quitting on the 5th:
study
study
study
incorrect
for 
ice
seal
corpse
ice


Now, checking the output I see these 6 records ahhh that's it

**Comment by imrryr** [comment]
In my console the story is different (search for setUpCard)

hook overallhistory [] * phantom selection never given ****perhaps this causes the problem somehow
ice overallhistory []
seal overallhistory []
corpse overallhsitory [1] * something got logged but was not  -- should still be []
ice overallhistory [1, 1] * ok another false log, since all previous were studies -- should be []
seal overallhistory [1, 1, 1] * here we see that 3 loggings of the studies -- should be [0]

**Comment by imrryr** [comment]
So perhaps the phantom selection of hook causes it to start logging late chronically.... @MegaGeese

**Comment by MegaGeese** [comment]
It doesnt look like that's the case. I'm not sure where that phantom selection is coming from but it was a race condition where the outcome history was logged too late to be used in the selection. I have a fix for those two issues that can be safely ported to prod and am currently investigating the phantom selection.

**Comment by imrryr** [comment]
excellent. I did check and the phantom selection was for the same user TESTRADS3006 as the other 5 trials, I wanted to make sure it wasn't from a previous run

**Comment by imrryr** [comment]
By the way, in my console output it lists each of the first 15 clusters twice. Do you know why that duplication occurs?

**Comment by MegaGeese** [comment]
can you provide a screenshot? I'm not sure I've seen that before

**Comment by imrryr** [comment]
![Screenshot (141)](https://github.com/memphis-iis/mofacts-ies/assets/13023147/55f2b71f-4256-4919-ba30-62a2e3d4ed31)

**Comment by MegaGeese** [comment]
looks like its calculating hints even though hints aren't available. Thats a simple fix

**Comment by MegaGeese** [comment]
If i can't find a solution to the phantom trial do you want me to deploy these fixes anyway or can this fix wait until next week?

**Comment by imrryr** [comment]
I think it would be great to deploy the fixes since the phantom trial
didn't seem to be doing anything.

**Comment by JRustyHaner** [comment]
@imrryr I'll go ahead and build staging with the fixes
