### ISSUE TITLE
scoring broken in assessment sessions

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#129]
The second question is that when I log in to the http://localhost:3000/ to test for the experiment, it will record the scores for the pretest and posttest. While when I use this link https://mofacts.optimallearning.org/experiment/tonelearning3 to test for the experiment, it does not record scores for the pretest and posttest.

**Comment by wscarter** [comment]
closed by #147 - 

Rather than skipping the scoring of assessment sessions, delivery params should be set to 0 to handle unscored sessions.
