### ISSUE TITLE
uiSettings problems

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1291]
Here is what I set

"uiSettings": {
          "displayReviewTimeoutAsBarOrText": "false",
          "displayReadyPromptTimeoutAsBarOrText": "false",
          "displayCardTimeoutAsBarOrText": false,
          "displayTimeOutDuringStudy": false,
          "displayUserAnswerAtTop": true,
          "displayPerformanceDuringStudy": true,
          "displayCorrectAnswerInCenter": true,
          "onlyShowSimpleFeedback": true,
          "incorrectColor": "darkorange",
          "correctColor": "green"

In many some cases, there are bars or timers on the displays, but every single one is turned off in my uiSettings, assuming you don't need to correct my usage. 

Also, for some incorrect, the messages are wrong. The correct answer should not be shown in a sentence on top when it is in the center, they are exclusive, including after correct responses and the 4 incorrect types. Here is how top feedback should be if I am using the settings right.

The  top messages should be
For timeout it should say "Your answer: [timeout] \n Incorrect."
For string X + timeout it should say "Your answer: X [timeout] \n Incorrect."
For string X it should say "Your answer: X \n Incorrect." This one is currently working right, except for the bottom bar flashing.
For string "" it should say "Your answer:   \n Incorrect."
For correct it should simply say "Correct."

I made a video of my experience, but please look at the above for much clearer instructions. Thanks! @JRustyHaner 

https://github.com/memphis-iis/mofacts-ies/assets/13023147/f2bc7175-f91e-43ba-a7c1-62d53e73dff1

**Comment by JRustyHaner** [comment]
@JRustyHaner looking at this now

**Comment by imrryr** [comment]
Assuming my specification in the UI settings is correct could you please test it after deploy to make sure it's following the requested specification. I think that would help us reduce iteration on these problems and save us both time.

**Comment by JRustyHaner** [comment]
@imrryr It was an odd race condition. For something to be consistent and not flash, we can't have it on card.html since it rerenders for each new card. Also, the progressbar can't be just hidden, aparently. We have to remove a whole class from it otherwise it will bug out / flash.

**Comment by imrryr** [comment]
[OptimTester1.zip](https://github.com/memphis-iis/mofacts-ies/files/13072953/OptimTester1.zip)
