### ISSUE TITLE
Alert Devs when Staging or Prod are not available

### ISSUE THREAD

**Issue by MegaGeese** [memphis-iis/mofacts-ies#1292]

**Comment by imrryr** [comment]
Will this be part of the same system for deployment alerts? In both cases, can we provide instructions in the install readme on how I can configure this (and others) I wold like all my grad students and myself to receive this alert and the deployment alrets.

**Comment by JRustyHaner** [comment]
@imrryr unfortunately, a process cannot monitor itself. If it goes down, it can't execute more code. I will have a script and provide and instructions on how to set it up. It will check every 5 minutes and when docker says its down, it will email an array of emails. You should have received an email a few minutes ago about staging being down.

**Comment by imrryr** [comment]
oh yeah, right.

**Comment by JRustyHaner** [comment]
@imrryr well, we could partially automate it...

docker can restart any down containers automatically. Odds are if the container is down, then the entire server is down. If that happens, then we can't execute any code at all.

I currently have a standalone script monitoring it, but setting docker to automatically restart containers would help. For the script to have to trigger, then docker would have had to fail restarting the container. That would be incredibly rare.

**Comment by JRustyHaner** [comment]
@imrryr  I've updated the https://github.com/memphis-iis/mofacts-docker repository readme to have the monitoring script and instructions in how to set it up.
