### ISSUE TITLE
A gray bar appears on the screen

### ISSUE THREAD

**Issue by mengcaopsy** [memphis-iis/mofacts-ies#1293]
I added the code below right after deliveryparams.
"uiSettings": {
          "displayReviewTimeoutAsBarOrText": "false",
          "displayReadyPromptTimeoutAsBarOrText": "false",
          "displayCardTimeoutAsBarOrText": false,
          "displayTimeOutDuringStudy": false
        }
There is a gray bar that moves along with other objects, such as when scrolling on the consent screen, and it consistently appears at the bottom of all screens, including instructions and all trial screens.
It just needs to be hidden/removed properly, since it overlaps other objects
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/9629109b-fc5f-495e-b4ce-9cf547ab2b85)
![image](https://github.com/memphis-iis/mofacts-ies/assets/43429451/d81ffd7c-5084-4125-ad3c-3d4f116b2a82)

**Comment by JRustyHaner** [comment]
@imrryr this has been fixed in the current deployment
