### ISSUE TITLE
Speech API broken

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#13]
Error with speech api call: Invalid recognition 'config': Context phrase with 1414 characters found, but max is 100.

**Comment by jeigrei** [comment]
[This page](https://cloud.google.com/speech-to-text/quotas) documents the API quotas in question

**Comment by andrewtackett** [comment]
Should be fixed with commit: aeb457933bac5a6348cf531a7553760f1f516c5b

Please re-open this issue if the problem persists.
