### ISSUE TITLE
Hint enabled is broken in new build

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1302]
Its set to  "hintsEnabled": false, @JRustyHaner @MegaGeese but I still get this for each trial. It's not even clear that hints enabled is even available on staging.
[OptimTester1 preflight.zip](https://github.com/memphis-iis/mofacts-ies/files/13260300/OptimTester1.preflight.zip)
![mofacts_app - Google Chrome 11_4_2023 4_15_51 PM](https://github.com/memphis-iis/mofacts-ies/assets/13023147/aaecab58-7599-434d-ab58-4b7b323f1103)

**Comment by JRustyHaner** [comment]
@imrryr syllable hints should be

**Comment by imrryr** [comment]
Well, I don't get that since aren't the hints created with calls to Andrew's software? Frankly, I have no idea how the hints are turned on now, but anyhow, that's not the issue here, the problem is that all the popups when the setspec has it hints deactivated still, that code is being called despite that, but it should not ever be triggered when "hintsEnabled": false, so there is some typo in the brackets around an if statement or something in the new build.

**Comment by JRustyHaner** [comment]
@imrryr syllable hints are called using syllables.jar, a server that runs on our servers
