### ISSUE TITLE
problem with "swapclusters"

### ISSUE THREAD

**Issue by mengcaopsy** [memphis-iis/mofacts-ies#1307]
I was testing the bird experiment and found that "swapclusters" does not work. 

Below is the package I used. 
[bird newest test1.zip](https://github.com/memphis-iis/mofacts-ies/files/13300774/bird.newest.test1.zip)

In the stims file, each bird image is a cluster. Clusters  64-69 70-75 76-81 82-87 88-93 94-99 100-105 106-111 112-117 118-123 124-127 belong to 11 bird categories (Altamira Oriole, Audubon's Oriole, Baltimore Oriole, Bullock's Oriole, Campo Oriole, Hooded Oriole, Orange Oriole, Scott's Oriole, Yellow-backed Oriole, Yellow Oriole, Spot-breasted Oriole).

I was using the code "shuffleclusters": "64-69 70-75 76-81 82-87 88-93 94-99 100-105 106-111 112-117 118-123 124-127" to randomize the exemplars within each bird category. In this way, participants will be presented with randomly 4 exemplars among the 6 exemplars during the pretest and learning sessions (both are assessment units). The "shuffleclusters" works well.

**However, when I used the code "swapclusters": "64-69 70-75 76-81 82-87 88-93 94-99 100-105 106-111 112-117 118-123" to randomize the order of the bird categories. The bird categories are not in a random order in the learning session (assessment unit with feedback, see the code below). 

Currently, the groups "A B C D E F G H M N X" used clusters "64-67 70-73 76-79 82-85 88-91 94-97 100-103 106-109 112-115 118-121 124-127" with the same bird category order as below: Altamira Oriole, Audubon's Oriole, Baltimore Oriole, Bullock's Oriole, Campo Oriole, Hooded Oriole, Orange Oriole, Scott's Oriole, Yellow-backed Oriole, Yellow Oriole, Spot-breasted Oriole. The order of the birds is not randomized.**

                  "assessmentsession": {
                      "conditiontemplatesbygroup": {
                          "groupnames": "A B C D E F G H M N X",
                          "clustersrepeated": "4 4 4 4 4 4 4 4 4 4 2",
                          "templatesrepeated": "4 4 4 4 4 4 4 4 4 4 4",
                          "group": [
                                  "0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48",
                                  "0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48",
                                  "0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48",
                                  "0,b,d,0 0,b,d,4 0,b,d,32 0,b,d,36 0,b,d,0 0,b,d,4 0,b,d,32 0,b,d,36 0,b,d,0 0,b,d,4 0,b,d,32 0,b,d,36 0,b,d,0 0,b,d,4 0,b,d,32 0,b,d,36",
                                  "0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48",
                                  "0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48",
                                  "0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48 0,b,d,0 0,b,d,16 0,b,d,32 0,b,d,48",
                                  "0,b,d,0 0,b,d,4 0,b,d,32 0,b,d,36 0,b,d,0 0,b,d,4 0,b,d,32 0,b,d,36 0,b,d,0 0,b,d,4 0,b,d,32 0,b,d,36 0,b,d,0 0,b,d,4 0,b,d,32 0,b,d,36",
                                  "0,b,d,0 0,b,d,4 0,b,d,8 0,b,d,12 0,b,d,0 0,b,d,4 0,b,d,8 0,b,d,12 0,b,d,0 0,b,d,4 0,b,d,8 0,b,d,12 0,b,d,0 0,b,d,4 0,b,d,8 0,b,d,12",
                                  "0,b,d,0 0,b,d,4 0,b,d,8 0,b,d,12 0,b,d,0 0,b,d,4 0,b,d,8 0,b,d,12 0,b,d,0 0,b,d,4 0,b,d,8 0,b,d,12 0,b,d,0 0,b,d,4 0,b,d,8 0,b,d,12",
                                  "0,b,d,0 0,b,d,164 0,b,d,0 0,b,d,164 0,b,d,0 0,b,d,164 0,b,d,0 0,b,d,164 "
                                 ]
                      },
                      "initialpositions": "\n  X_1 X_2 X_3 X_4\n   M_1 M_2 M_3 M_4 M_1 M_2 M_3 M_4 M_1 M_2 M_3 M_4 M_1 M_2 M_3 M_4\n  A_1 E_1 B_1 B_2 A_2 E_2 F_1 F_2 A_3 E_3 B_3 B_4 A_4 E_4 F_3 F_4   A_1 E_1 B_1 B_2 A_2 E_2 F_1 F_2 A_3 E_3 B_3 B_4 A_4 E_4 F_3 F_4    A_1 E_1 B_1 B_2 A_2 E_2 F_1 F_2 A_3 E_3 B_3 B_4 A_4 E_4 F_3 F_4    A_1 E_1 B_1 B_2 A_2 E_2 F_1 F_2 A_3 E_3 B_3 B_4 A_4 E_4 F_3 F_4 \n    C_1 C_2 C_3 C_4 G_1 G_2 G_3 G_4 D_1 D_2 D_3 D_4 D_1 D_2 D_3 D_4   C_1 C_2 C_3 C_4 G_1 G_2 G_3 G_4 H_1 H_2 H_3 H_4 H_1 H_2 H_3 H_4      C_1 C_2 C_3 C_4 G_1 G_2 G_3 G_4 D_1 D_2 D_3 D_4 D_1 D_2 D_3 D_4    C_1 C_2 C_3 C_4 G_1 G_2 G_3 G_4 H_1 H_2 H_3 H_4 H_1 H_2 H_3 H_4\n       N_1 N_2 N_3 N_4 N_1 N_2 N_3 N_4 N_1 N_2 N_3 N_4 N_1 N_2 N_3 N_4 \n   X_1 X_2 X_3 X_4\n ",
                      "randomizegroups": "false",
                      "clusterlist": "64-67 70-73 76-79 82-85 88-91 94-97 100-103 106-109 112-115 118-121 124-127",
                      "assignrandomclusters": "false",
                      "permutefinalresult": "0-0"
                  }

Below is the data file showing what stimuli participants will learn on each trial. The bird categories used should be different for each participant, but currently, it is fixed for all participants.
[problem data file.xlsx](https://github.com/memphis-iis/mofacts-ies/files/13301031/problem.data.file.xlsx)

**Comment by imrryr** [comment]
Not sure why this wouldn't work anymore. It seems to be in the code still and it was well used previously.

**Comment by JRustyHaner** [comment]
@imrryr  me either, the git history shows this logic was written 2-3 years ago.

**Comment by imrryr** [comment]
But that's not true; maybe that is when a bug was introduced... I used it in 2018 and I think its from around 2016

**Comment by imrryr** [comment]
Just checked. It was written by Craig in 2015

**Comment by imrryr** [comment]
here is a dev backup dated 2016 @JRustyHaner @MegaGeese 
//create a mapping vector. The idea is that for cluster x, mapping[x] returns
//a translated index. Note that the default mapping is identity, so that
//mapping[x] = x HOWEVER, the user may submit a different default mapping.
//This is mainly so that multiple shuffle/swap pairs can be run. ALSO important
//is the fact that additional elements will be added if
//mapping.length < clusterCount

createStimClusterMapping = function(clusterCount, shuffleclusters, swapclusters, startMapping) {
    if (clusterCount < 1)
        return [];

    var i;

    //Default mapping is identity - mapping[x] == x
    //We also need to make sure we have clusterCount elements
    var mapping = (startMapping || []).slice(); //they get a copy back
    while (mapping.length < clusterCount) {
        mapping.push(mapping.length);
    }

    //Shufle the given ranges of cards (like permutefinalresult)
    if (!!shuffleclusters) {
        var shuffleRanges = [];
        Helpers.extractDelimFields(shuffleclusters, shuffleRanges);

        var shuffled = mapping.slice(); //work on a copy

        _.each(shuffleRanges, function(rng) {
            var targetIndexes = Helpers.rangeVal(rng);
            var randPerm = targetIndexes.slice(); //clone
            Helpers.shuffle(randPerm);

            for(j = 0; j < targetIndexes.length; ++j) {
                shuffled[targetIndexes[j]] = mapping[randPerm[j]];
            }
        });

        mapping = shuffled.slice();
    }

    //Swap out sections of clusters (one step up from our shuffle above)
    if (!!swapclusters) {
        //Get the chunks that we'll be swapping. Each chunk is in the format
        //of an array of integral indexes (after the map). We actually get
        //TWO lists of chunks - one in order and one that is the actual swap
        var ranges = [];
        Helpers.extractDelimFields(swapclusters, ranges);
        var swapChunks = _.map(ranges, Helpers.rangeVal);
        var sortChunks = _.map(ranges, Helpers.rangeVal);

        //Now insure our sorted chunks are actually in order - we sort
        //numerically by the first index
        sortChunks.sort(function(lhs, rhs) {
            var lv = lhs[0], rv = rhs[0];
            if      (lv < rv) return -1;
            else if (lv > rv) return 1;
            else              return 0;
        });

        //Now get a permuted copy of our chunks
        Helpers.shuffle(swapChunks);

        var swapped = [];
        i = 0;
        while (i < mapping.length) {
            if (sortChunks.length > 0 && i == sortChunks[0][0]) {
                //Swap chunk - grab the permuted chunk and add the mapped numbers
                var chunk = swapChunks.shift();
                for (var chunkIdx = 0; chunkIdx < chunk.length; ++chunkIdx) {
                    swapped.push(mapping[chunk[chunkIdx]]);
                }

                //advance to the next chunk
                i += sortChunks.shift().length;
            }
            else {
                //Not part of a swapped chunk - keep this number and just move
                //to the next number
                swapped.push(mapping[i]);
                i++;
            }
        }

        //All done
        mapping = swapped.slice();
    }

    return mapping;
};

**Comment by imrryr** [comment]
@JRustyHaner @MegaGeese The old version above from 2016, looks subtlely different from the old version. I bet it was not tested when it was moved into this file and modified to the context of the function... 

  // Swap out sections of clusters (one step up from our shuffle above)
  if (swapclusters) {
    // Get the chunks that we'll be swapping. Each chunk is in the format
    // of an array of integral indexes (after the map). We actually get
    // TWO lists of chunks - one in order and one that is the actual swap
    const ranges = [];
    extractDelimFields(swapclusters, ranges);
    const swapChunks = _.map(ranges, rangeVal);
    const sortChunks = _.map(ranges, rangeVal);

    // Now insure our sorted chunks are actually in order - we sort
    // numerically by the first index
    sortChunks.sort(function(lhs, rhs) {
      const lv = lhs[0]; const rv = rhs[0];
      if (lv < rv) return -1;
      else if (lv > rv) return 1;
      else return 0;
    });

    // Now get a permuted copy of our chunks
    shuffle(swapChunks);

    const swapped = [];
    i = 0;
    while (i < mapping.length) {
      if (sortChunks.length > 0 && i == sortChunks[0][0]) {
        // Swap chunk - grab the permuted chunk and add the mapped numbers
        const chunk = swapChunks.shift();
        for (let chunkIdx = 0; chunkIdx < chunk.length; ++chunkIdx) {
          swapped.push(mapping[chunk[chunkIdx]]);
        }

        // advance to the next chunk
        i += sortChunks.shift().length;
      } else {
        // Not part of a swapped chunk - keep this number and just move
        // to the next number
        swapped.push(mapping[i]);
        i++;
      }
    }

    // All done
    mapping = swapped.slice();
  }

  return mapping;

**Comment by mengcaopsy** [comment]
@imrryr @JRustyHaner @MegaGeese  Could you please also fix this issue in the old system? https://mofacts.optimallearning.org/  I might use the old one to run the experiment.

**Comment by JRustyHaner** [comment]
@imrryr @mengcaopsy unfortunately, copying and pasting that code snippet into the current staging branch and comparing them shows that they are the same

**Comment by imrryr** [comment]
@JRustyHaner what do you mean? I don't know what code snippet you are talking about....   I gave you 2 code snippets you realize, one is from staging, one is from 2016

**Comment by imrryr** [comment]
You understand the new code introduced an error? This issue is to fix that error. I'm not sure why the function was moved. @JRustyHaner

**Comment by JRustyHaner** [comment]
@imrryr Sorry, I hadn't had my coffee this morning. Let me take another look.

**Comment by JRustyHaner** [comment]
@imrryr There's not any logic differences between the two, but there are some stylistic differences for best practices. The old code snippet uses a different declaration type, let instead of const, or a if(!!variable) instead of just (variable) which is an odd choice, but both do the same thing. Basically, it looks like the changes were made because the original code was poorly written. The new code does the exact same functions but is memory safe. We can change it back, but I doubt that this is where the error is.

**Comment by imrryr** [comment]
Well, we will talk it through at 10:30am then. Please think of the best way to look at the inputs and outputs of that function so that we can be sure it is being triggered. Her tdf code appears flawless, so I'm not seeing how this it is not working unless these lines of code have some bug. The function is essential for randomization in cases like this. I suspect the rewrite is causing a subtle problem, since I'm pretty sure it was not tested. I have no further evidence.

**Comment by JRustyHaner** [comment]
@imrryr the cluster mapping is created correctly, it has nothing to do with her tdf. You can view the cluster mapping in console by filtering for 'Cluster mapping  created'. The array that follows that is the results of the cluster mapping.

**Comment by imrryr** [comment]
OK, but that contradicts the error report, so we need to figure that out....

**Comment by imrryr** [comment]
So I went on to try this, and the content is corrupted. It does not start, and the images appear missing in the content upload interface. Was there an attempt at deletion @mengcaopsy @JRustyHaner I wanted to test this in meeting at 10:30am, but now it doesn't run at all...

**Comment by JRustyHaner** [comment]
@imrryr I've been working locally only by copying the database to my own machine

**Comment by JRustyHaner** [comment]
@mengcaopsy that happens when the server cannot find the images.

**Comment by imrryr** [comment]
Clearly there are 2 errors, one is an uploader problem on the new system, then there is the swap custers problem which should be both systems. We will sort through this in a few minutes

**Comment by JRustyHaner** [comment]
@mengcaopsy did you change your experiment target? the original zip file has birdtest and staging currently doesn't have an experiment with that url.

**Comment by imrryr** [comment]
from her root file: {
    "tutor": {
        "setspec": {
            "lessonname": "Bird Category Learning",
            "stimulusfile": "birdstimsnew.json",
            "experimentTarget": "birdcategory",
            "randomizedDelivery": "1",
            "userselect": "false",
            "condition": [
              "birdlownarrow1.json",

**Comment by JRustyHaner** [comment]
@imrryr thanks, this is from the first zip file at top, which is what I was testing:

{
    "tutor": {
        "setspec": {
           "lessonname": "Bird Category Learning",
	         "userselect": "true",
            "stimulusfile": "birdstimsnew.json",
           **"experimentTarget": "birdtest",**
               "audioInputEnabled": "false",
               "shuffleclusters": "64-69 70-75 76-81 82-87 88-93 94-99 100-105 106-111 112-117 118-123 124-127",
               "swapclusters": "64-69 70-75 76-81 82-87 88-93 94-99 100-105 106-111 112-117 118-123",
            "hintsEnabled": false,
	   "tags": [
				"Experiment",
				"bird learning"
			]
        },

**Comment by imrryr** [comment]
@JRustyHaner @MegaGeese Join Zoom Meeting
[https://memphis.zoom.us/j/86966887622?pwd=WXJVQWxrd05xM3ljTGtNaEdXSmJzdz09](https://www.google.com/url?q=https://memphis.zoom.us/j/86966887622?pwd%3DWXJVQWxrd05xM3ljTGtNaEdXSmJzdz09&sa=D&source=calendar&usd=2&usg=AOvVaw3qXUYe__rzi9T4XQfRndJT)
