### ISSUE TITLE
Download all data is broken

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#1308]
[Download all TDF data for current user: imrryr@gmail.com](https://staging.optimallearning.org/dataDownload)

This link is dead for me
![mofacts_app - Google Chrome 11_8_2023 4_13_49 PM](https://github.com/memphis-iis/mofacts-ies/assets/13023147/ea88852e-498c-4cbc-980a-5fd83af1ed9e)

**Comment by imrryr** [comment]
That is what the interface indicates. This relation to classes is not meaningful not sure how it happened and I don't think we can handle that level of downlaod specifity without extra work. Seems like a bug. It should find all data for tdfs with ownership. But there are some nested issues, which is that my download screen shows all the data I think, but I do not own all the tdfs listed. In fact, can you check true "ownership" in the database, since it says I have ownership of things I can't recall uploading on the content page. On the download page it shows a larger subset of things I didn't upload. 

Of course, maybe they work normally (showing only things related to the users uploads and access) for teacher level users, but I don't know).

For the admin, I think we should in the same way restrict data download to owned or tdfs with access. Not all tdfs. That is better from an IRB standpoint. I think we should also do this for the content upload/download, allowing the admin to only see things they have ownership and access to.

**Comment by JRustyHaner** [comment]
@imrryr that makes sense. I have a fix for the data download side, but I'll add in the UI display changes too.

**Comment by JRustyHaner** [comment]
@imrryr It wasn't the case for the content file manager that it only displayed owned/accessible tdfs and packages.
