### ISSUE TITLE
Calculate Indcies produces length error on chinese radicals experiment

### ISSUE THREAD

**Issue by JRustyHaner** [memphis-iis/mofacts-ies#1309]
![Screenshot from 2023-11-10 11-10-10](https://github.com/memphis-iis/mofacts-ies/assets/46696077/084e0748-e4c9-492f-924a-dc669809b9bf)

to reproduce:

https://staging.optimallearning.org/experiment/mt1 and click continue, then view the console

**Comment by imrryr** [comment]
@MegaGeese this seem likely to be related to the recent work to remove the redundant calculation or probability. Learning sessions don't give trials due to the errror

**Comment by JRustyHaner** [comment]
@MegaGeese this will also fix the publishing issue for dynamicassets
