### ISSUE TITLE
Modified stim file format and dual trials

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#131]
improvements in stim file formatting and ability to jointly present text and sound, sounds and picture, text and picture, or all three as a prompt

**Comment by andrewtackett** [comment]
Completed with commits: 714c839ed994fb2189e62bd7583b41a8ae3e8193, 435d3cf0cd79c0e7400d0aaed40c42c04bcc263b

@imrryr I anticipate you might want to tweak the layout a bit.  Let me know if this is the case and I might be able to help you do rapid prototyping so we can update it quickly.
