### ISSUE TITLE
Stimulus tag field passthrough

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#138]
Please enhance the data output so that datashop downloads have the <tags> information added as CF () tags in the output. Can it be made to inventory the tags in the stim file corresponding tdf and just add a column for each tag to list its value for the stimulus for that trial in the output?

**Comment by andrewtackett** [comment]
Solved with commit: 1d928f9b08c75142b506221fb1260a34bde858a1
