### ISSUE TITLE
Dialogue response often asks you you a question where the correct answer is simply "It"

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#148]
This is problematic. It does this for sentence that begin this It. Resolving this problem is key to improving dialogue.

**Comment by aolney** [comment]
I think this duplicates https://github.com/aolney/mofacts-automated-authoring/issues/16

I can prioritize that enhancement, just let me know.

**Comment by imrryr** [comment]
It is prioritized for Fall 2020 according to tot he Milestones, that's pretty soon
