### ISSUE TITLE
Content creation sort function

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#153]
Allow the content creator to sort the list of items by text order or by the order of the priority. When there is a priority sort, the text will not be shown as it is currently

**Comment by imrryr** [comment]
Clarify which priority tag to use
Allow sort to original order
By "text" in the original comment I mean the text on the left, but now thinking about it, this may not be needed or even really wanted, I mistakenly thought it might be necessary on first analysis

**Comment by imrryr** [comment]
use sentenceWeight

**Comment by imrryr** [comment]
Forgot, we also need to sort by whether or not paraphrase or coreference substitution (original or created). tricky because paraphrases have 2 versions

**Comment by imrryr** [comment]
Want to delete withe paraphrase or original

**Comment by andrewtackett** [comment]
Need to be able to delete any paraphrase and leave original AND delete original and bump up paraphrase to main display property instead of alternativeDisplay list

**Comment by andrewtackett** [comment]
Mostly done with commits: 6b07a9de6fc3efab651acdbdaf594d984d20aae4, 07c26d0fc54c2915297c07fed4a6b9684e806f9f

**Comment by andrewtackett** [comment]
Tenatively done with commit: 4e03823a793d240ae862dd9620ca155d3031097c

**Comment by imrryr** [comment]
1.  can't remove paraphase only? That is highly desirable...
2.  what does source text tell us that we can't infer easily (seems like it makes it require 50% more scrolling to see items, so lets remove it unless I'm missing something, and save the additional line...)

**Comment by andrewtackett** [comment]
> can't remove paraphase only? That is highly desirable...

You can delete a paraphrase. What do you mean?

**Comment by andrewtackett** [comment]
Done done with 9425591a5ecf315cfe6a9c93464d57ebe87b08c3.

Please reopen if you find more issues tomorrow.
