### ISSUE TITLE
Minute 2:03

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#154]
Reveals a bug in dialogue where it repeats the final phrase twice...

**Comment by andrewtackett** [comment]
@imrryr Minute 2:03 of what?

**Comment by imrryr** [comment]
Sorry meant to drop the YouTube link but I think this is an Andrew Olney task primarily

**Comment by imrryr** [comment]
https://www.youtube.com/watch?v=iurlKNDNrrE&t=0s

**Comment by aolney** [comment]
Time indexed link: https://youtu.be/iurlKNDNrrE?t=122

**Comment by aolney** [comment]
Closed with https://github.com/aolney/mofacts-automated-authoring/commit/0cc2b8c78e6a0f3153d89b43c9259a10e0431773

Will send release soon.
