### ISSUE TITLE
Drill down to student records unreliable

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#164]
Clicking on student ids should bring up the student's individual record, just like the student see it, except with the course averages shown as a comparison. First fix the student report, then add the comparison.

**Comment by andrewtackett** [comment]
Fixed with commit: 7baf65f835a20c6be797135907255d7f45be79d1

Comparison to follow

**Comment by andrewtackett** [comment]
Comparison added with commit: 1491505e2a1d2e5a39afc7eea2c101444853c616
