### ISSUE TITLE
Check and correct time computations in progress report

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#165]
Time is added for 
Drills and reviews after drills
Time in dialogue (excluding time sitting at continue buttons)

Please confirm or fix

**Comment by andrewtackett** [comment]
Time is added for all trial types (not just drills) and for reviews afterwards, including the dialogue loop.

Should time only be added for drill trial types?

Also why exclude time at continue buttons?  So they can't game the system?

**Comment by imrryr** [comment]
Well, I think that test trials will likely not every be counted in the time (they are not currently given either). Of course, we don't want to count the survey, and that is all test trials.

Yes, exactly, we don't need to fix that now, but ideally, continue buttons would not count for the time spent in practice since they would/could game that for extra credit.

**Comment by imrryr** [comment]
Actually the continue buttons are a temporary ad hoc decision and it may make sense to transition to dialogue without them in some way in the future... the best HCI here is not yet clear to me.

**Comment by andrewtackett** [comment]
Fixed so test trial types don't count towards user progress.  For now I'm leaving the continue button timing out but please open up another issue if you want it changed eventually and prioritize it accordingly.

Commit: b56cef016cee530aac088420312414373df11571
