### ISSUE TITLE
Horizontal buttons

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#167]
Please assess how hard it would be to display the buttons for multiple choice using a <buttonArrayWidth> which specifies how many columns of buttons to render. Don't do this now, please just assess.

**Comment by andrewtackett** [comment]
@imrryr This should be very easy.  Just changing up the template helper function buttonListImageRows and figuring out where to put the parameter. deliveryParams seems reasonable.  Do you have a desired name for the parameter or want me to make one?

**Comment by imrryr** [comment]
Looks like this is already implemented for image buttons (at least a 2 wide display is) lets but this in low priority unless it comes up again.

**Comment by andrewtackett** [comment]
Allow configuration of number of columns and rows for flexibility.  Notify Wei when done

**Comment by andrewtackett** [comment]
Implemented with commit: 256d2a0cc396766c4b80ab3922dc5cc9eb2e06ad

**Comment by andrewtackett** [comment]
Wei confirms it works.  

Documentation updated.

Closing for now and will send out an email once these changes are pushed to prod.
