### ISSUE TITLE
timeuntilstimulus

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#169]
This was previously used and is meant for only sound stimuli. Please rename it to <timeuntilsoundstimulus> and have it apply accordingly. I'll put this detail in the checkout doc I'm working on. I beleive<timebeforefeedback> was also meant to apply only for sound, but I have not yet checked that...

**Comment by imrryr** [comment]
At least I'm pretty sure and anticipating Meng will point it out when she tests.... leave it for now, but I wanted to note it

**Comment by imrryr** [comment]
Talked to Meng today, in addition to this issue, the screen in rendered in an order (buttons first) then icon, that results in the buttons jumping locations as the icon is rendered. Please render the stimuli first, or at least reserve space so the buttons don't jump after the icon is placed.

**Comment by imrryr** [comment]
First comment here should have also asked about <timebeforefeedback>500</timebeforefeedback> how is that working now?

**Comment by andrewtackett** [comment]
After talking with Phil and fixing Meng's issues #174 , no further changes are wanted at this time so I'm closing this issue for now.
