### ISSUE TITLE
Default progress value

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#17]
![mofacts_app](https://user-images.githubusercontent.com/13023147/64489262-a2907380-d216-11e9-9cc6-32ab09ac6ca7.png)

Change default select chapter to the chapter you are currently working in, or all if none

**Comment by andrewtackett** [comment]
Talked to Phil.  Need to default to first individual tdf for now instead of "All".

**Comment by andrewtackett** [comment]
Solved with commit: f22e4ff2523cdaa20ae4634f60db1eb9396f02fe

Please reopen if issues persist.
