### ISSUE TITLE
Buttons rendering before stimulus

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#178]
This was in Meng's testing. The buttons render before the stimulus, but they need to render at the same time, or slightly before to prevent components moving.

**Comment by andrewtackett** [comment]
Potential solution with commit: c7dae3bcde83e3d303b20e86cca195b082e62b74

Will email Meng to download and test.

**Comment by andrewtackett** [comment]
Commit solved the issue per Meng.  Closing.
