### ISSUE TITLE
% axes need to be 0-100

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#18]
not 0 to 1, that is probability
![mofacts_app](https://user-images.githubusercontent.com/13023147/64489319-6c072880-d217-11e9-9a20-c15fe9da91e9.png)

**Comment by andrewtackett** [comment]
Should be solved with commit: 4ab32d2c2dac35e7e18fbddb624bf4d04dd9188d

Please reopen if not.
