### ISSUE TITLE
TDFs for Fall2020

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#181]
Phil needs to add new consent after negotiated 8/12
Phil needs to change tags for refutation and dialogue

**Comment by imrryr** [comment]
Can Phil put in database directly? or pass on to Andrew?

**Comment by andrewtackett** [comment]
TDFs have to be transformed into JSON (and should be edited as XML so we have version histories of the full source files), so uploading via the web interface is the best option for now.  I made content upload allow multiple files at once so this should be less tedious and also fixed some bugs related to the newer stim file format in uploading.

**Comment by imrryr** [comment]
Thanks

**Comment by imrryr** [comment]
Uploaded to config repo for testing, consent update needed before upload

**Comment by imrryr** [comment]
I'm holding off on the full upload to prevent anyone from accidentally trying to use the system

**Comment by imrryr** [comment]
the TDFs currently in repo are ready to update lessonname to include x% to the lessonname, where x = 5, 10 or 15

**Comment by andrewtackett** [comment]
Tdfs are updated
