### ISSUE TITLE
Stims for Fall2020

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#182]
Phil needs them at some point to alter parameters.... Maybe it doesn't matter when... Andrew T?

**Comment by andrewtackett** [comment]
@imrryr Realized I didn't add in the "Did you read the chapter" question to the stim files in the config repo, would you mind doing that?  The prompt should be under the "text" property of the display property and they should be the last cluster/stim in the file.

**Comment by andrewtackett** [comment]
@aolney 

Found another weird stim randomly, from ch10.05.selected-cloze.json.  It seems the clozeCorefTransformation is identical to the original cloze item.

```
{
    "cloze": "Structures called sensory receptors at the ends of neurons in the __________ __________ __________ provide the sensory function of the nervous system.",
    "itemId": 1896056682,
    "clozeId": -35361001,
    "correctResponse": "peripheral nervous system",
    "tags": {
        "weightGroup": 0,
        "orderGroup": 2,
        "sentenceWeight": 96,
        "clozeProbability": 0.00000392415387705948,
        "clozeParaphraseTransformation": "Structures called sensory receptors at the ends of neurons in the __________ __________ __________ provide sensory function in the nervous system.",
        "clozeCorefTransformation": "Structures called sensory receptors at the ends of neurons in the __________ __________ __________ provide the sensory function of the nervous system.",
        "correctResponseCorefTransformation": "peripheral nervous system",
        "corefClusters": 2,
        "corefClusterTotalWeight": 96,
        "corefClusterBackwardWeight": 21,
        "corefClusterForwardWeight": 72,
        "rootDistance": 7,
        "startDistance": 10
    }
}
```

**Comment by aolney** [comment]
My guess is that there might have been a transformation after the equality check that removed white space, making them identical afterwards. I'll look out for it on the next round.

**Comment by imrryr** [comment]
AT actually I would have to do a large number of cut and paste and based on the new format might not be entirely sure it would work... Isn't there code that you run to do this. It seems that having me do it by hand would be a way to introduce error.

**Comment by andrewtackett** [comment]
You're right.  I've updated the config repo.

**Comment by imrryr** [comment]
Isn't there any automatic code to add that final stimulus? I'm not sure
what it looks like in the new format. I'd rather not accidentally introduce
errors at this point in the process given I don't understand Json
intuitively yet. If you don't have code to add it please send me what it
will look like in the new format...

The change I was going to make is actually considerably easier than adding
these additional stimuli.

**Comment by imrryr** [comment]
Sorry, technical glitch, my reply was not appearing on my phone, so I repeated. I assume you were replying to me then Andrew T?

**Comment by andrewtackett** [comment]
Yes

On Tuesday, August 18, 2020, Philip Pavlik <notifications@github.com> wrote:
> Sorry, technical glitch, my reply was not appearing on my phone, so I
repeated. I assume you were replying to me then Andrew T?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/DL3HwgGGndEMsX8wPpzogCQlzxABiCgd3RYiHEIANBwoMly8XKTIvzpCr_NKqmzNaiRoCo4MLITr9JWTuQJmnlUpHqL_LgKjvyoMqKidMmELz6xQVn10bEx00e2dGFiH8NwSljMi_zNq97Q8sTDxf9bugEtnGAXTkPxK86I1eMKVIqJbBLOLRWatgY5ru-p_t9zC-_YIRC3mgGTU2NDG89jHV7zaCv5pax2PJorQ5w=s0-d-e1-ft#https://github.com/notifications/beacon/ABIWVHGK2PDQWJ4XO5K5DKDSBJ4FRA5CNFSM4P44DPIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFBBM4TQ.gif>

**Comment by imrryr** [comment]
Stims are imported to database, feel free to check me
