### ISSUE TITLE
Studio 3T licenses

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#187]
They don't make it cheap, so lets only get year licenses for those who will use them.... Seems like AT, perhaps Wes, perhaps myself.... Are we thinking anyone else? Will Wes really need it? if it is good chance happy to get...

**Comment by aolney** [comment]
I'd be inclined to use the free Robomongo or [Compass](https://www.mongodb.com/blog/post/compass-now-free-for-all) in general; it's not clear to me what paid features I would need from Studio 3T.

My assumption is that I would need to do a dump and then do all analysis in R regardless.

**Comment by wscarter** [comment]
For me it would be a "nice to have", but not critically important.  I get by fine with free Robot 3T and NoSQLBooster

**Comment by imrryr** [comment]
How nice ;) ? Do you mean you might use it and if you do it will be nice, or you will use it and it will be nice when you do even if infrequently?

**Comment by wscarter** [comment]
The latter, but it really isn't a problem for me to use the free options for now and perhaps we can revisit if the need for a licensed feature arises.

**Comment by andrewtackett** [comment]
Purchased
