### ISSUE TITLE
Bug, perhaps in refutation functions

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#189]
![Screenshot (19)](https://user-images.githubusercontent.com/13023147/91047143-3a7d9d80-e5df-11ea-9f81-b16ea0a0a51a.png)

**Comment by imrryr** [comment]
No other problems discovered Sunday

**Comment by andrewtackett** [comment]
Fixed with commit: 604b97c469373d99dfa2367dab0a306b27f85f98
