### ISSUE TITLE
left and right margins should be at least 1or 2% of sreen width and center all fields

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#19]
![mofacts_app](https://user-images.githubusercontent.com/13023147/64489319-6c072880-d217-11e9-9a20-c15fe9da91e9.png)

**Comment by andrewtackett** [comment]
Solved with commit: bc8e48562814cf4ce88cad0441c27cee7f8f9d17

Please reopen if issues persist.
