### ISSUE TITLE
Bug in progress reproter

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#190]
![Screenshot (21)](https://user-images.githubusercontent.com/13023147/91088492-ba275e80-e617-11ea-9774-7176404a1729.png)

**Comment by imrryr** [comment]
I left the machine, came back, did a couple trials, then went to progress and was getting this

**Comment by imrryr** [comment]
We got this I'm almost positive, open if I am wrong.

**Comment by andrewtackett** [comment]
I don't think we did.  It's just a rare occurrence.  Reopening pending further investigation...

**Comment by imrryr** [comment]
Seems no sense to keep this open at this point since all that is being redone and tested with this current cycle milestone

**Comment by imrryr** [comment]
Oh wait I see you have it on the milestone I'll leave it then

**Comment by andrewtackett** [comment]
Shouldn't be an issue in the new postgres version
