### ISSUE TITLE
Fix hint display

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#194]
Not a code bug, but a logic bug is that is you have a two syllable hint with a 1 syllable first word with a two or more syllable second word, the response is ambiguous as in "for swa________" which could be swallowing or for swallowing
or "thin mem______" which could be membrane or thin membrane

Resolve by underlining the hint in addition to the fill-in

**Comment by imrryr** [comment]
that's the definition of a code bug, that is why I specified it was a bug in the logic/spec. It isn't an enhancement however precisely, since that implies it worked correctly in the first place. I have remarked it as invalid, to indicate the result is not in spec or spec was not appropriate. This is on me.

I added this to the spec, please check it over to make sure it reflects current cloze behavior after completing this task.

**Comment by imrryr** [comment]
screenshot below shows different problem which likely belongs here...

**Comment by imrryr** [comment]
Second fill in instance should be handled the same way as first

![Screenshot (32)](https://user-images.githubusercontent.com/13023147/92405805-07b5c800-f0fc-11ea-8fb6-dbb7db5b60e4.png)

**Comment by andrewtackett** [comment]
Check why this commit didn't do it: https://github.com/memphis-iis/mofacts-ies/commit/a00fbeea5cf5ed7dd4fa346bd1d8a1a54af1c883

**Comment by andrewtackett** [comment]
Try to allow swallowing as well as lowing and for swallowing

**Comment by andrewtackett** [comment]
Fixed with commit: c632eaf4080b28bd294cc7a9ca605919966063d4
