### ISSUE TITLE
Single screen for dialogue

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#195]
Questions to answer at the next meeting

It flips to review the correct answer after the dialogue, perhaps it should do that beforehand? Just run a regular trial, then have a continue button to do dialogue on the next screen, followed by a continue button to get the next trial from that single dialogue screen.

Lets have the continue buttons say "Timing stopped, press continue when ready" unless we see problems with that, perhaps it is unneeded to saying timing stopped?

**Comment by andrewtackett** [comment]
Completed with commits: ecd597c716683906504ab09e5ef9910e2b3927d2, 0c14757d419c4e8b1a12e3ff0e5ccf29ac381a3b
