### ISSUE TITLE
Template filter in content creation

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#197]
Lets put a string filter above the template dropdown that restricts it to whatever items contain the string.... If we can use simple logical operators, e.g. imrryr AND Chapter 1 that would be neat... not sure if there are prepackaged functions for that, if not, don't add that to the request here

Also, when you navigate to content creation, it starts halfway scrolled down the page. Let's make it start at the top of the document.

**Comment by wscarter** [comment]
Finished with commit 8e5328f9bb0a9dad9c5ae128af400a81de7551a3
