### ISSUE TITLE
Load limiter

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#199]
We have to preserve the user experience in the case the server load gets high. We need to have a sort of a graceful failure where people are refused entry to the server when we can't serve them. Can we set a system where it only allows x number of unique connections? This will allow us to set the value at a safe level by watching the server load value in relationship to the setting. I don't think there's time to make it dynamic but in theory such a system could even monitor the load and automatically increase the users if load was low. I expect I will do that manually, so build in a way to change the limit without redeploy.

**Comment by andrewtackett** [comment]
Upon login page render, query database for active users.  Approximation of active users for now could be grab ids of all users last logged in within 24 hours.  Then count unique user ids with datetimestamps in usertimeslog in the last 15 minutes.  Manually run this query every few minutes server side and client side just query latest result for both performance and logging.

Also make sure users returning/not generating datetimestamps after 15 minutes have to log in again to ensure bottleneck for limiter.

**Comment by andrewtackett** [comment]
Fixed with commit: 3e8338b513f6ff9985c413dffd0b41210d791e56
