### ISSUE TITLE
Develop load testing scripts for mofacts

### ISSUE THREAD

**Issue by andrewtackett** [memphis-iis/mofacts-ies#201]
Make script that can do a realistic user experience for stress/load testing, including login, experiment navigation, repeating answer loop, maybe progress checking?

**Comment by andrewtackett** [comment]
Initial version in this commit by wes: 9c1444b712b954b97b1f828c299d41eff4bd2e60

**Comment by JRustyHaner** [comment]
@imrryr We have Selenium for this
