### ISSUE TITLE
Double check all server functions with new server

### ISSUE THREAD

**Issue by andrewtackett** [memphis-iis/mofacts-ies#205]
Backups, cron jobs, etc.

**Comment by andrewtackett** [comment]
re-enable letsencrypt for mofacts2 and make sure everything renews and backs up properly

**Comment by andrewtackett** [comment]
check S3 functions, name backups differently per server

**Comment by imrryr** [comment]
Not sure if this is current, but closing out this milestone, so move this to the "Bugs and Urgent Issues" milesotne
