### ISSUE TITLE
Dialogue switch

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#206]
Create dialogue on/off switch which allows a random setting at start

**Comment by imrryr** [comment]
Make it separate from but organized near the TTS and SR panel.

**Comment by andrewtackett** [comment]
Toggle between simple, refutational, dialogue and default to random setting choice.

**Comment by andrewtackett** [comment]
Also allow tdf writers to force one feedbackType or allow students to change with a default

**Comment by andrewtackett** [comment]
Wes completed with commit: 5030735a4c115a9aeeb63dd0bc482aa16977a765
