### ISSUE TITLE
Bug in selection engine activation

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#207]
User: 01710009, page: /card, time: Thu Sep 17 2020 06:43:48 GMT+0000 (UTC), description: I am answering the same question over and over . , userAgent: Mozilla/5.0 (X11; CrOS x86_64 13099.110.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.136 Safari/537.36

Log attached... selection fails until after they reported the error
[datashopRothschild-Chapter2_mrothschild_2020_09_09T21_28_29_926Z_FA_2020_TDF.xml-data.txt](https://github.com/memphis-iis/mofacts-ies/files/5246665/datashopRothschild-Chapter2_mrothschild_2020_09_09T21_28_29_926Z_FA_2020_TDF.xml-data.txt)

**Comment by andrewtackett** [comment]
Maybe be resolved through DB refactor

**Comment by andrewtackett** [comment]
Look at whether this was really Rothschild-Chapter2_mrothschild_2020_09_09T21_22_43_491Z_FA_2020_TDF.xml

which is malformed

**Comment by imrryr** [comment]
Should we just close this issue maybe? We are getting any error reports so I think that we really have the errors figured out in that system but perhaps you have a better perspective.

**Comment by andrewtackett** [comment]
Yes, we should probably wipe the slate with the new system and try to be thorough in testing.  Closing this for now
