### ISSUE TITLE
Reload problem

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#208]
User: 01742655, page: /card, time: Sun Sep 20 2020 20:18:03 GMT+0000 (UTC), description: no questions popping up
, userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
User: 01566854, page: /card, time: Mon Sep 21 2020 04:25:00 GMT+0000 (UTC), description: chapter will not load, userAgent: Mozilla/5.0 (X11; CrOS x86_64 13310.76.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.108 Safari/537.36

**Comment by imrryr** [comment]
looks like the first person couldn't start Chapter 3, but did a bunch in 2

**Comment by andrewtackett** [comment]
Dupe #207 , closing
