### ISSUE TITLE
Assessment session scoring

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#209]
Only learning session trials should be scored as a default, the scoring/ time/ percent correct is not intended for assessment session trials generally.

Make sure we can turn it off or on for either assessment or learning session trials also.

**Comment by andrewtackett** [comment]
Email Meng to notify when done

**Comment by andrewtackett** [comment]
Completed with commit: e63d5ee2a93170230e9ea48f597250503ce27268

**Comment by andrewtackett** [comment]
In addition: a new deliveryparam, scoringEnabled, has been added.  It defaults to false for assessment sessions and true for learning sessions but can be overridden in each unit to turn scoring and score displays on/off.
