### ISSUE TITLE
Progress data table

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#21]
don't draw the borders, leave them invisible
make the time in "Minutes" with only one decimal place
make the 3 fields share the horizontal width inside the margins for the page (currently time is bunched on the right)
![mofacts_app](https://user-images.githubusercontent.com/13023147/64489319-6c072880-d217-11e9-9a20-c15fe9da91e9.png)

**Comment by andrewtackett** [comment]
Solved with commit: bc8e48562814cf4ce88cad0441c27cee7f8f9d17

Please reopen if issues persist.
