### ISSUE TITLE
Bug shows when running as test online (matches student experience)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#210]
![Screenshot (36)](https://user-images.githubusercontent.com/13023147/93909124-0fad6480-fcc5-11ea-8a0b-8d3918613343.png)

**Comment by andrewtackett** [comment]
@imrryr What does "running as test" mean?

**Comment by imrryr** [comment]
Logging in is a test user, using the test user function to skip the sso...

**Comment by andrewtackett** [comment]
Dupe #207 , closing
