### ISSUE TITLE
Repetition correctness table

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#22]
Rename the graph "Corrrectness Across Repetitions of the Same Fill-in"
make the x axis be called "Repetition Number"
![mofacts_app](https://user-images.githubusercontent.com/13023147/64489319-6c072880-d217-11e9-9a20-c15fe9da91e9.png)

**Comment by andrewtackett** [comment]
Solved with commit: aa17debe9828253a5cfb8b05729159cf7230f879

Please reopen if issues persist.
