### ISSUE TITLE
Newly created tdfs in content creation menu should refresh the tdf template menu after save

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#226]
teacher meeting indicated this was extremely problematic the way it worked previously

**Comment by andrewtackett** [comment]
"Search here" in search bar, make paste source default hidden with button to expand and show, drop down taller on tdf template select

**Comment by andrewtackett** [comment]
Partial progress with commit: 2454ae711d26b3c0fd12ace7c316b3c823ac0db1

**Comment by andrewtackett** [comment]
UX improvements done with commit: 5de5560a6cff2c4b7d09c87344b6ec2de2e7d905
