### ISSUE TITLE
Title the page with the "Progress for " and then Studentid

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#23]
Remove the phrase "Student Reporting -"

![mofacts_app](https://user-images.githubusercontent.com/13023147/64489319-6c072880-d217-11e9-9a20-c15fe9da91e9.png)

**Comment by andrewtackett** [comment]
Solved with commit: e903ce74ab39002983bd24cba5420292c5122ebc

Please reopen if issues persist.
