### ISSUE TITLE
Payment issue in MoFaCTS

### ISSUE THREAD

**Issue by mengcaopsy** [memphis-iis/mofacts-ies#231]
I got an error when I click the approve/pay button in MoFaCTS.

![image](https://user-images.githubusercontent.com/43429451/109185776-ee5e1200-7755-11eb-8151-bfb6d6ebd5a6.png)

**Comment by andrewtackett** [comment]
Investigate users AQAXDL1INQC9Q and  A1VMPZVVVZUCS4.

**Comment by andrewtackett** [comment]
Issue seems to have been due to a transient server issue.  I'm going to close this for now.  Please reply if you see it again Meng, and it'll open up again.

**Comment by mengcaopsy** [comment]
Got it. I am not running experiments now. I will test it when I run. Thank
you, Andrew.

Meng
