### ISSUE TITLE
Voice buttons and TTS buttons

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#239]
This means that the button trials could be answered with SR, and the questions and answers could be read out loud.

Long-term issue just wanted to note.

**Comment by andrewtackett** [comment]
Button trials already can be answered with SR, not sure about questions and answers being read out loud, need to investigate

**Comment by andrewtackett** [comment]
@MegaGeese Can you investigate whether questions and answers can be read out with TTS for button trials?  testTdf.xml's first two questions in the first unit (which is an assessment session unit) are button trials and can be used to test this.

**Comment by MegaGeese** [comment]
Reading the buttons can be done. However for the image responses (like the Algeria question in testTdf) there would need to be some transcription of the images added to their json files.

**Comment by andrewtackett** [comment]
@MegaGeese Go ahead and implement it, and reach out to Phil and ask him what he'd prefer to do in that case.  I'd assume ignoring image responses but it's up to him.

**Comment by imrryr** [comment]
Thanks, yes. Rather than just fully ignore them maybe we can actually have
it break if somebody tries to do that and give a message that says it's not
an acceptable configuration.

**Comment by andrewtackett** [comment]
@MegaGeese We do something similar in resumeFromComponentState()  Give an appropriately informative message about what exactly is broken in this case

```
if (!rootTDF) {
    console.log('PANIC: Unable to load the root TDF for learning', Session.get('currentRootTdfId'));
    alert('Unfortunately, something is broken and this lesson cannot continue');
    leavePage('/profile');
    return;
  }
  ```
