### ISSUE TITLE
Migrate rest of mongo database to postgres

### ISSUE THREAD

**Issue by andrewtackett** [memphis-iis/mofacts-ies#241]
Maybe leave off auth/users as that's more involved with meteor framework

**Comment by andrewtackett** [comment]
Collections include:

StimSyllables = new Meteor.Collection("stimuli_syllables");

ScheduledTurkMessages = new Mongo.Collection("scheduledTurkMessages");
GoogleSpeechAPIKeys = new Mongo.Collection("googleSpeechAPIKeys");
ClozeEditHistory = new Mongo.Collection("clozeEditHistory");
ErrorReports = new Mongo.Collection("errorReports");
LoginTimes = new Mongo.Collection("loginTimes");
UtlQueryTimes = new Mongo.Collection("utlQueryTimes");
DynamicConfig = new Mongo.Collection("dynamicConfig");
UserProfileData = new Mongo.Collection("userProfileData");

as well as Users

**Comment by JRustyHaner** [comment]
@imrryr This is depreciated
