### ISSUE TITLE
student progress report shows items not in the learning session practice clusterlist

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#245]
Also, we only want to compute ps for items actually part of the learning session in the tdf, so only the clusterlist in the learningsession. This might be occurring for teacher reports as well...

Progress reports are originally tied to the same data as learning session practice, not tied to tdfs. the linkage to the learning unit has been lost I think. Thoughts?

**Comment by imrryr** [comment]
I saw some erratic behavior here on reload also, but before reload it just seemed the only problem was that it showed the did you read the chapter item in the progress report...

**Comment by andrewtackett** [comment]
"Progress reports are originally tied to the same data as learning session practice, not tied to tdfs. the linkage to the learning unit has been lost I think. Thoughts?"

This seems accurate.  I can filter out non learning session items.

**Comment by imrryr** [comment]
Great, lets make the assumption for now that the progress report shows all the items that are seen in learningsessions only. Since the progress reporter will be updated, I'm moving this detail to that issue.
