### ISSUE TITLE
disable student login for server 2 first then, after data is removed,  unregister it with AWS so we are no longer charged

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#249]

**Comment by imrryr** [comment]
I've grouped all the data issues as highest since we want to clear those so we can finalize the model

**Comment by andrewtackett** [comment]
Done.  Data backup is sitting in my home dir on mofacts1

**Comment by imrryr** [comment]
So, the backup is not the same as the data. We discussed putting the old version of the code back up on server 2 (which created the data downloads correctly), getting the data (not the backup) which I need to do in the interface typically, then the server was to be taken offline.  This is also discussed here: https://github.com/memphis-iis/mofacts-ies/issues/247 the download changes to get the hints have broken general downloading on master
