### ISSUE TITLE
postgres progress report for student is not working

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#252]
Please put the queries responsible here. I will help vet them, unless you already know how to fix it, I'd like to see every query for the progress report on the student side

**Comment by imrryr** [comment]
Amy says: I think the Current Estimate of Recall graph is pulling data from previous sessions, but none of the other data on this page is cumulative.

**Comment by imrryr** [comment]
The query you sent in the email should be useful in helping me debug the issue, thanks

**Comment by imrryr** [comment]
OK, so one problem is that the componentstate.priorcorrect appears to be not reloaded or updated ONLY when componentstate.componentnstate=''stimulus"

This is pretty clear from this query:
select * from componentstate where userid='sKTs2qarrcguJqu2K' order by componenttype;

This may cause downstream problems like null p values perhaps...

**Comment by imrryr** [comment]
it looks like totalpracticeduration, firstseen and last seen may also not be updating/ reloading for the stimulus component type for those items that were correct...

**Comment by imrryr** [comment]
Now that we have a bit of perspective on this problem, it may be a data recording problem affecting the model... Bumping it up to highest since it blocks further testing.

**Comment by imrryr** [comment]
So, to narrow down the possibility, I checked the componentstate with userid=ikzXPRZXMqaMeLheq while I was in the first session. I saw that the missing information was still there. I reloaded and it was still there, after going to the progress report during the second session it was suddenly gone... Cluster and response information seems to be fine..... Also, I'm thinking it doesn't depend on correctness....  I think it may happen to all stimulus variables from a first session in some way connected to second session progress reports.

**Comment by imrryr** [comment]
Just replicated it... the data for stimulus in components state is lost when the progress reporter starts during a second session...

**Comment by imrryr** [comment]
Couldn't replicate it for first session, but while I was looking at the seemingly correct progress report for about 1.5 seconds, it updated, and no longer showed the info (it was still in the database at this point), and when it disappeared the dropdown no longer showed tdf chapter 9 at all... After restarting a second session, I discovered that to get it to dump the data when getting a progress report during the second session you need to do a handful of second session trials first...

**Comment by andrewtackett** [comment]
State restoration on resume was riddled with bugs.  Commit 5e743fbe2ee014a7cf1bf8f32909f65327ed30cc should fix all of those, which in turn should fix the progress reporter having progress seemingly cleared and only presenting the last continuous session's data.

Also fixed in this commit was an issue where quickly navigating to progress report caused the UI to blank after a few seconds due to not handling closing out voice recognition properly.
