### ISSUE TITLE
dialogue and refutation not showing

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#255]
report from Amy - does not show when turned on and provided incorrect response is given.

**Comment by andrewtackett** [comment]
for example the correct answer was cell membrane and the list of hints said membrane, so I typed in membrane, and it only said “Incorrect, the correct answer is cell membrane”

Dialogue loop was not initiated - investigate

**Comment by andrewtackett** [comment]
I was unable to reproduce this in dialogue or refutational feedback mode in firefox or chrome.  I believe this was fixed just before this issue was submitted when the staging server had code in between commits.  Going to close for now as this shouldn't block testing.
