### ISSUE TITLE
y-axis progress labels

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#26]
For the Corrrectness Across Repetitions of the Same Fill-in

can the y-axis be in steps of 10? thats traditional for a grade report and will be easier for students to think about

**Comment by andrewtackett** [comment]
Fixed with commit: 6b020b3b7c384c8ae3a9c0ba97bf7b6d68bbcccf

I also made the bottom chart scale in steps of 10 as well.  Let me know if that's not what you want.
