### ISSUE TITLE
Item removal by student

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#267]
A button that appears during review, in the bottom right corner. With a feedback popup if student uses it. 

Button text "Report this item as wrong and remove it."

Feedback popup "Thanks, we’ll take it out of your stack." (with continue button)

Student presses button, no outcome will be recorded for the trial (e.g. mark it “Removal” in outcome column for the trial in data output)

Special flag is set for stimuli in the componentstate table (model code will be fed this info and always compute the item p=0, preventing its selection for that student and allowing us to quickly search for these items so as to not include them in the progress gauges (do count past time and percent correct for the items, but not the other 3 readouts...)

**Comment by andrewtackett** [comment]
This is very well specified and a good example of a good feature request.  I would suggest if they remove too many we prevent additional removal, maybe more than a third or a half of items?  Alternatively only stop it when there are 3 items left (we need at least 2/3 for certain routines to function properly).

**Comment by imrryr** [comment]
Yes, good call, lets make it 3 for safety. I think few people will abuse it, but we shouldn't let them cause an error.

**Comment by lukeEG** [comment]
This might be a very efficient way to curate new stimuli sets in general (e.g., if X% of students or more agree about an item a researcher/teacher can look at it and confirm/reject dropping item). Probably important to emphasize the feature during initial familiarization so students know to use it.

**Comment by imrryr** [comment]
Good idea I'm going to be having my new graduate ra work on completely new
instructions and I'll make sure that this comes up...

**Comment by MegaGeese** [comment]
@imrryr In the student reporting page, should the removed stims be included in or excluded from the reports shown on that page?

**Comment by imrryr** [comment]
Excluded. We're basically assuming that students are removing them because
the item is  confusing or in error in some way.
