### ISSUE TITLE
Sentence incomplete

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#269]
**Describe the bug**
Sentence is cutoff during practice

**To Reproduce**
go to unit 9 until you see this stimuli... I think you mentioned this one already

**Expected behavior**
full sentence display with period at the end

**Screenshots**
![mofacts_app and 8 more pages - Personal - Microsoft​ Edge 8_21_2021 2_10_36 PM](https://user-images.githubusercontent.com/13023147/130332571-29811aca-79ce-41e6-b87d-7a843a6dbd11.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version Latest

**Comment by andrewtackett** [comment]
Note: Current code for syllable replacement doesn't handle cases where original question has multiple instances of the answer replaced with underscores. Look in unitEngine.js

**Comment by JRustyHaner** [comment]
Changing testStim an reinitializing postgres dataset via script to have a longer string and two blanks inside currentDisplay.clozeText appends currentDisplay.text to currentQuestion for the first instance a question is seen.
