### ISSUE TITLE
hitting back on progress screen should return to practice

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#27]
currently it just breaks the practice with a blank stimuli box

**Comment by andrewtackett** [comment]
Talked to Phil. Make back button go back to practice page if on progress page so we can re-enter the tdf practice correctly.

**Comment by andrewtackett** [comment]
Resolved with commit: f4e26c1a8f7c9c8fb6f4696f4e02d6ea550b2ecd

Please reopen if problems persist.
