### ISSUE TITLE
Incorrect totalpracticeduration in component state

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#271]
**Describe the bug**
It isn't including the entire practice trial, only stimulus portion

**To Reproduce**
These queries illustrate how sum is only stimulus by glancing at the results.
select * from componentstate where userid='RgkgAxgpYfbGxfpgF' and componenttype='cluster' and kcid=10009  order by componenttype,kcid;
select *
from history where userid='RgkgAxgpYfbGxfpgF' and kcid=10009
order by history.eventstarttime;

**Expected behavior**
Should be sum of response and feedback durations also, not just stimulus.

**Comment by andrewtackett** [comment]
Fixed with commit: 4435ec3236ed0eeea4adf835b570cb524554067c
