### ISSUE TITLE
Stub Ch 10 JSON for Advisory Board demo

### ISSUE THREAD

**Issue by aolney** [memphis-iis/mofacts-ies#28]
Sent the json last weekend; just adding this to make sure its tracked.

**Comment by imrryr** [comment]
Advisory board demo wasn't really ready for this aspect, but maybe we can show something at the meeting

**Comment by imrryr** [comment]
Can we close this?

**Comment by aolney** [comment]
Closing b/c the issue was time limited and has now expired.
