### ISSUE TITLE
Testing for cell phones

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#3]
Is there an easy way to access my local server with my cellphone? In other words, can I test locally on my cellphone... Or do I need to do all cell phone testing using the remote server.

**Comment by jeigrei** [comment]
In principle, if your machine and phone are both on the same network, you should be able to access the local development server by entering the fully qualified hostname into your browser and specifying the port with a colon. For example, on my machine on the university network:

`http://grayson-ThinkStation-P300.memphis.edu:3000`

This will only work if port 3000 is open to outside access on your machine (which can definitely be arranged) and if, in the case of the campus network, traffic on port 3000 is allowed (not sure about that one). I'll look into it.

**Comment by jeigrei** [comment]
This is tested and working on the campus network as of commit 3353f55b7b98267f18f6604cba5a21a6eba25e9d

You'll need to re-provision the Vagrant VM for the changes to take effect, i.e.
```
$ vagrant destroy
$ vagrant up
```

**Comment by imrryr** [comment]
No big deal, but this worked if I used the test login only... Gmail login from phone didn't work do=ue to oauth failure. Don't fix this unless it is trivial...
