### ISSUE TITLE
Doesn't run when started as student in demo mode

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#301]
**Describe the bug**
I posted the available content (1 tdf was already there) for my teacher id for ies, but then login in as a demo student it errors

**To Reproduce**
1. Login to my teacher account and try the tdf

**Expected behavior**
no error

**Screenshots**
![image](https://user-images.githubusercontent.com/13023147/135322146-35ff666c-835d-44ab-883c-f903e29b9161.png)

**Desktop (please complete the following information):**
fast laptop

**Comment by JRustyHaner** [comment]
@imrryr which tdf were you uploading so I can reproduce the error?

**Comment by imrryr** [comment]
The only one on staging that I could use:
tdf | Chapter_10_ambanker_2020_11_11T15_34_31_278Z_FA_2021_TDF.xml
stim | Chapter_10_ambanker_2020_11_11T15_34_31_278Z_FA_2021_Stim.json

**Comment by imrryr** [comment]
not clear this still needs debugging, was not reproduced with converted content from Andrew, lets close it for now, to work on more tangible issues.
