### ISSUE TITLE
Get backups to S3 working again

### ISSUE THREAD

**Issue by andrewtackett** [memphis-iis/mofacts-ies#320]
We have a solution that was created to sync mongo dumps off ec2 instances (/var/mongobackups) to an S3 bucket for safekeeping.  It appears to be failing now.  Possibly we just need to use the right connection string for mongo but we should also enable dumps from postgres as well now that that will house most of our important data.

**Comment by imrryr** [comment]
is this task old, please close if so, I think we have backups
