### ISSUE TITLE
Using the speech recognition seems to disable the TTS, even when you turn it off

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#33]
Also, the speech API key not setup message isn't detecting the key in the TDF, and it also should remove the button, since the key in the tdf should override the need to set your own key (its just confusing to offer a button they never press)

Do we plan to allow both tts and sr at the same time if they want (perhaps with a message that headphones are needed

**Comment by imrryr** [comment]
Do we plan to allow both tts and sr at the same time if they want (perhaps with a message that headphones are needed)?

**Comment by andrewtackett** [comment]
Yes, we're going to allow both.  I've updated the code to display a message suggesting headphones when they click to enable both in the profile page.  Relevant commit: ae7884c0e43b704df941ef3c959c6fbeed06f979
