### ISSUE TITLE
"Neuron" item shows content generation bug

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#364]
**Describe the bug**
In chapter 10
                        "response": {
                            "correctResponse": "Neuroglia"
                        },
                        "display": {
                            "clozeStimulus": "__________ are found throughout the nervous system, and in the brain Neurons greatly outnumber neurons."
                        },

Please decide whether we should recreate the files, since this seems like a logic problem in the code generating the items.... "Neurons" also appears to be the wrong word as if there was an incorrect substitution. Not sure why we are substituting in this case...

**Comment by imrryr** [comment]
Maybe not? I'm wondering about only applying it to the first words of sentences. Is that a very complicated change to make?

It seems the first word is special, since it will always be a problem if it needs resolution and then item will always be bad. So, in the case of first word (often where it is needed) it may be a real help. Alternatively, if we detect a first-word resolution issue, we could just remove the item. 

For words other than the first, I agree your solution seems best. Would you be able to remake the stimuli then? I'm thinking that we don't need the 5% this time around, but I'd like to be able to choose from the 10 or 15% percent sets for each chapter. If it is really easy to do this, perhaps you could give me the 10, 13 and 16% sets instead actually.

**Comment by aolney** [comment]
[Here are some test cases I previously ran, with error statistics](https://github.com/aolney/mofacts-automated-authoring/issues/16#issuecomment-665256642).

As you can see, the current policy is to replace if the NP starts with this/that/these/those or a personal pronoun.

Some of these cases cover the subject position, which is what I believe you mean when you say "first words".

We could restrict replacement to the subject position, but as you can see in these examples, you will still get bad items if other words in the sentence are not resolved.

Back then we decided that instructors would review the items to compensate for the fact that the coreference is only about 64% correct.

**Comment by imrryr** [comment]
Thanks for reminding me and pointing me back to these details. I will
search for the stim files that were edited as you said. I forgot this
important issue makes it a higher priority.
