### ISSUE TITLE
One step local operation

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#373]
How might we include in the repo
A. produce a dummy settings file that allows the local version to start up (perhaps with instructions on how to change the email...
B. Have the 2 files for Andrew's ref and dialogue modes be uploaded through the content uploading and not necessary for the system to book. Also, how are these files referenced in the code. Are they hard coded, or does the tdf reference them somehow. The tdf or stimuli file should be the place where they are referenced since they are "content" files.

By having these files necessary, it makes it very hard for outsiders to use mofacts unless we add them to the repo or make them an option specified in tdfs at least so they are not required unless the tdf calls for them.

**Comment by JRustyHaner** [comment]
It might be a good idea to make an install script that would do all the setup steps for the end user, make it auto updating.
