### ISSUE TITLE
SSO login does not work

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#435]
**Describe the bug**
Login doesn't work for  Southwest SSO, this happened 5 times...

**To Reproduce**
Difficult to reproduce without login id. Will discuss in meeting. Please see if we get any debug info for situations like this. Can we save debug info when this happens? Any ideas?

**Expected behavior**
Login preceeds

**Screenshots**
![Screenshot (80)](https://user-images.githubusercontent.com/13023147/143692313-32c64945-ec14-4f9e-8716-46c71cdf119a.png)

**Comment by imrryr** [comment]
Here is what I see with the valid test account, which I will now send you by email. It appears we are authenticating the wrong website .... it says mofacts.optimallearning....
![image](https://user-images.githubusercontent.com/13023147/146958400-0acd2f49-4347-4045-b497-afb2a5b3a43a.png)

**Comment by JRustyHaner** [comment]
that url only appears in comments, our SSO settings are currently showing staging.optimallearning.org as ROOT_URL and mofacts2 as ALT_URL (this displays a link on signInSouthwest when the staging is overloaded). Does southwest's forwarding on the account send it back to mofacts.optimallearning.org? I can't see where anything in our code would request a callback to mofacts.optimallearning.org

**Comment by imrryr** [comment]
OK, well I was just hoping it might be that easy to fix, thanks for the info. I guess we can try other ways to debug now that we have a test account (which I tested at the main SW website to make sure it works)

**Comment by JRustyHaner** [comment]
If its any consolation, I just get a blank Firefox page. At least you receive an error.
