### ISSUE TITLE
New build 11/29 does not start tdfs

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#436]
**Describe the bug**
The screenshot shows an error in the console

**To Reproduce**
Try it now online

**Expected behavior**
It works. The button gives no response now.

**Screenshots**
![mofacts_app and 9 more pages - Personal - Microsoft​ Edge 11_29_2021 8_46_09 AM](https://user-images.githubusercontent.com/13023147/143888953-e485d007-1ac5-461f-a117-f4e11b5f60fd.png)

**Comment by JRustyHaner** [comment]
@imrryr this is a database error, we won't have to push any code to fix it. Shouldn't be more than a few minutes.

**Comment by MegaGeese** [comment]
@imrryr db has been fixed. Try reuploading the tdf and confirming.
