### ISSUE TITLE
Trial isn't completely ended after home button

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#445]
**Describe the bug**
Several times, the program would continue with dialogue even after they hit the Home button.
Do you mean the home button didn't work? Then it started working after the dialogue? Not sure I understand how long it didn't work... ​It seemed like a glitch, in my opinion. This occurred when they were using the audio features, where the computer read aloud the question for them; for most of the participants, when they clicked "Home", the computer would read aloud the next question, even though they were on the Home page. This only happened for the first question after they clicked Home.

**To Reproduce**
Should be easy to reproduce

**Expected behavior**
Trial activities are abort at home button. Make sure all data records are complete.

**Comment by MegaGeese** [comment]
Can you provide a video of this happening? I can't seem to reproduce this. I think this has to do with the timing of when the user clicks home.
