### ISSUE TITLE
Crash after reading question unit 2

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#451]
**Describe the bug**
Just stops as screenshot shows.

**To Reproduce**
Should reproduce, didn't do anything special

![mofacts_app and 10 more pages - Personal - Microsoft​ Edge 12_3_2021 10_03_40 AM](https://user-images.githubusercontent.com/13023147/144634059-895f7a7e-faf0-4c29-a7e8-2a50cecead55.png)

**Comment by imrryr** [comment]
it shouldn't be checking for not being NOT yes or no, so this should just be marked as no.... almost certain if it was no, it would still error, but its a bug either way

**Comment by MegaGeese** [comment]
This should be fixed on staging now. Somehow aspects of feature freeze made it into the deployment. They have been removed.
