### ISSUE TITLE
Countdown Timer Clearing Refutational Feedback

### ISSUE THREAD

**Issue by MegaGeese** [memphis-iis/mofacts-ies#463]
**Describe the bug**
Randomly during the countdown the refutational feedback will get replaced with simple feedback. 

**To Reproduce**
1. Enable refutational feedback
2. Uncomment the countdown timer

**Comment by imrryr** [comment]
Also can we make the countdown timer appear underneath the feedback not
inside the box with the feedback please. That will make the feedback easier
to read since the changing of the number draws the eyes when it is nearby.
