### ISSUE TITLE
Does not give practice

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#483]
**Describe the bug**
![mofacts_app and 12 more pages - Personal - Microsoft​ Edge 1_7_2022 9_48_30 AM](https://user-images.githubusercontent.com/13023147/148569376-844226a8-7fb2-44de-8ea2-0a826e9814a2.png)

**To Reproduce**
Use the test tdf and try to do any practice

**Expected behavior**
Practice

**Comment by JRustyHaner** [comment]
this is occuring when a stim has an undefined probability estimate. looking into it now.

**Comment by JRustyHaner** [comment]
@imrryr  this was a variable naming problem between p.probabilityEstimate and p.probability. Simple fix though.

**Comment by imrryr** [comment]
Great, just say when it is live on staging please

**Comment by JRustyHaner** [comment]
@imrryr Deployed
