### ISSUE TITLE
Local version won't start

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#487]
**Describe the bug**
Screenshots show details

**To Reproduce**
Might be general, no one else has used it lately I think

**Screenshots**
![image (5)](https://user-images.githubusercontent.com/13023147/149163926-9d91f979-aef1-4780-abd4-cd1dd1000004.png)
![image (6)](https://user-images.githubusercontent.com/13023147/149163990-aefa0cfd-e680-492e-b0b7-3df5403878bc.png)

**Comment by MegaGeese** [comment]
So I was able to reproduce this. This looks like an error with first time installs that needs to be addressed. To fix this what I did was:
1. Exit the vagrant virtual machine with `exit`
2. Shut down the virtual machine with `vagrant halt`
3. Delete the folder `node_modules` from `mofacts-ies/mofacts`
4. In the `mofacts-ies/mofacts` directory, run the command `meteor npm install`
4a.  if you get an error saying that meteor is not an executable then follow the instructions from the terminal's output and remove the `.meteor/` folder
5. Restart vagrant/mofacts with `vagrant up` and `vagrant ssh` and run meteor. 
<br>
To avoid this issue going forward, until I find a permanent fix that works across OS's, run `meteor npm install` before starting the vagrant virtual machine whenever you clone the repository

**Comment by mengcaopsy** [comment]
It doesn't work for me to run meteor npm install. Below are the code and results in the command.

C:\Users\Meng\Documents\NetBeansProjects\mofacts-ies3\mofacts>meteor npm install --save meteor-node-stubs
'meteor' is not recognized as an internal or external command,
operable program or batch file.

After I delete the node_modules and .meteor/ folders, I restart the vagrant and run the meteor. Here is what I got.
![image](https://user-images.githubusercontent.com/43429451/149198134-32d9e514-3bfc-407e-ab5e-3ddc6b8a8fda.png)

**Comment by MegaGeese** [comment]
Run `meteor npm remove meteor-node-stubs` inside the vagrant box then `./run meteor`. Mofacts should start for you then. You may still see the message about unresolved modules but from what I can see they are not used in mofacts.

**Comment by mengcaopsy** [comment]
I run meteor npm remove meteor-node-stubs  in the following code.
vagrant@ubuntu-bionic:~/mofacts/mofacts$ meteor npm remove meteor-node-stubs

But still goes to the "vagrant@ubuntu-bionic:~/mofacts/mofacts$" after I run the meteor.
![image](https://user-images.githubusercontent.com/43429451/149222335-83989fff-8f1b-4892-812b-20e24e37f3bc.png)

**Comment by MegaGeese** [comment]
It'll probably be best to set up a meeting to fix this issue. What time would you be available for either an in-person or zoom meeting?

**Comment by mengcaopsy** [comment]
How about tomorrow at 2 pm on Zoom? Other time will also be fine.
