### ISSUE TITLE
Progress report doesn't show

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#490]
**Describe the bug**
I did 33 trials... But Progress says NaN and says I have not practiced. See console error.

**To Reproduce**
Login to my course on staging as "John Doe"

**Screenshots**
![mofacts_app and 11 more pages - Personal - Microsoft​ Edge 1_13_2022 9_23_09 AM](https://user-images.githubusercontent.com/13023147/149358581-8c794581-40e3-450a-8430-5fd3f06a8650.png)
![mofacts_app and 11 more pages - Personal - Microsoft​ Edge 1_13_2022 9_23_34 AM](https://user-images.githubusercontent.com/13023147/149358594-e542980f-165c-4dc6-84c8-b7b73d21e52d.png)

**Comment by JRustyHaner** [comment]
@imrryr On it
