### ISSUE TITLE
Total time in instructor report incorrect

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#491]
**Describe the bug**
See John Doe's stats in first screen are not how the progress report says. There is an error in the next to last column, but last column appears to use the correct value...

**To Reproduce**
Login to my teacher account and look

**Screenshots**
![mofacts_app and 11 more pages - Personal - Microsoft​ Edge 1_13_2022 9_23_09 AM](https://user-images.githubusercontent.com/13023147/149359427-da529acb-ba18-4520-93c7-c623d25bb608.png)
![mofacts_app and 11 more pages - Personal - Microsoft​ Edge 1_13_2022 9_28_30 AM](https://user-images.githubusercontent.com/13023147/149359447-75fade93-64aa-48fa-8498-7c6361a74818.png)

**Comment by MegaGeese** [comment]
Ive found where this bug is happening. When we save the component stat we are saving the total practice duration per cluster/card and per stim. Should it be saved on a per-card or per-stim basis?
