### ISSUE TITLE
Bugs in Hints

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#496]
**Describe the bug**
Described after each screenshot. All of these were coming up in multiple contexts...

**Screenshots**
![mofacts_app and 12 more pages - Personal - Microsoft​ Edge 1_17_2022 10_50_11 AM](https://user-images.githubusercontent.com/13023147/149829902-3fb085bd-9081-47e8-bf7a-e054395394e6.png)

There used to be a space between the words when it was 2 words. It is missing here, so you can't tell he response is supposed to be 2 words  it should be "<u>sensor___</u> _________ ", 

![mofacts_app and 12 more pages - Personal - Microsoft​ Edge 1_17_2022 10_50_36 AM](https://user-images.githubusercontent.com/13023147/149829926-154f5080-0a08-46cb-ab96-62cdef0a352c.png)

In this one, it seems like the ability to type the remaining portion of the response is broken... this was built in.

![mofacts_app and 12 more pages - Personal - Microsoft​ Edge 1_17_2022 10_56_22 AM](https://user-images.githubusercontent.com/13023147/149830142-d6a0a142-3194-4e7e-87a5-1355a1b01dba.png)

It appears to be giving a 2 syllable hint for a 2 syllable response, but 2 syllable responses don't get hints. Bug

![mofacts_app and 12 more pages - Personal - Microsoft​ Edge 1_17_2022 10_53_10 AM](https://user-images.githubusercontent.com/13023147/149830181-d7a236a2-006b-40a3-930d-3d7cbbf8166c.png)

Here it looks like a 2 word response, but it prints the hint twice. I might guess it thinks the number of words in the response is the same as the number of syllables needed, since it needed 2 syllables "portion" and it gave a blank space between the underlines.

![mofacts_app and 12 more pages - Personal - Microsoft​ Edge 1_17_2022 10_51_24 AM](https://user-images.githubusercontent.com/13023147/149830411-b69065e9-66b9-43ff-839e-c0693f8f4666.png)

This appears to be a version of the Schwann cells item above, it gives the whole response as a 2 syl hint, but it can't give hints for dendrites, since it is a 2 syl word.

**Comment by JRustyHaner** [comment]
On it

**Comment by JRustyHaner** [comment]
@imrryr found most of the issues. 
1. Spaces in multi-word answers: fixed;
2 hint levels exceeding 1 for 2 syll words: fixed;
3. multiple instances of the answer in the same blank:  This one was caused by multiple blanks in the stim. If an answer has multiple words, it should still only be one blank in the stim.
4. typing just the missing part of the answer: working on it.

**Comment by JRustyHaner** [comment]
@imrryr  for example:
Question:  A  _______ _______ is an excellent film. A  _____ ____ won an oscar. 
Appears at hintlevel 1:  A beau____ _____ is an excellent film. A beau____ ____ won an oscar.
Appears In Stim:  A ____________ is an excellent film. A ___________ won an oscar.
Answer: Beautiful Mind

If two ______s are together in the stim, MoFACTs will repeat the answer twice, as below.
Question:  A  _______ _______ is an excellent film. A  _____ ____ won an oscar. 
Appears at hintlevel 1:  A beau____ beau___ is an excellent film. A beau____ beau____ won an oscar.
Appears In Stim:  A ______ ______ is an excellent film. A _____ ______ won an oscar.
Answer: Beautiful Mind

**Comment by imrryr** [comment]
Are you saying the stim files are wrong in some cases for the current code?

**Comment by JRustyHaner** [comment]
Since hintlevel didn't really work previously, we're running into issues with stims that worked in the past.

**Comment by imrryr** [comment]
Also in the past we never gave any hints at all for one and two syllable words. It sounds like you may have changed it inadvertently so that two syllable words will get hints which is probably not a good idea since that would be a change that we never gathered data to measure...

**Comment by JRustyHaner** [comment]
@imrryr I mispoke, hintlevels will not be given for any answers that have two or less syllables.

**Comment by imrryr** [comment]
Sorry that so much of this had to be rewritten. It sounds like you will be handling the case for multiple blanks in the stimuli though and we don't need to change the stim files.

**Comment by JRustyHaner** [comment]
@imrryr it's not a problem, and it can be set where it handles multi word answers in that manner. Might be a good idea since the stimulus authors could habitually write multi word answers with one blank or many.

**Comment by imrryr** [comment]
I think I made the incorret assumption that iterating over the hint levels would have no effect on the way they were displayed, since the possible values didn't change I didn't anticipate the display algorithm would stop working if the source of the hint levels was different

**Comment by JRustyHaner** [comment]
@imrryr That's fair, I think we all missed that. The double blanks will be easy to fix, and I'm working on the partial answer problem.

**Comment by imrryr** [comment]
When it comes right down to it we're actually in an excellent position to get things done on time compared to prior semesters. I've really appreciated how responsive you and Rhodes have been.

**Comment by JRustyHaner** [comment]
We both appreciate that. It's definitely coming along. 
I split the issue with the missing syllables answer into a separate issue,  since there's another bug happening there. Blank answers or typing in what's displayed (i.e.  nerv___ _____ is displayed, and one types in 'nerv') returns correct.
