### ISSUE TITLE
Data field available?

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#508]
Does the javascript model function currently have access to the string value for the item response? How would I write a line to get the length of the response students type? Just asking since I don't intend to request a feature if this is not available...

**Comment by JRustyHaner** [comment]
@imrryr do you want the most recent answer for the response? The probability function occurs before the answer is typed in by the student. I could pass along the most recent answer for that stim into the probability function.

The javascript to get the length of a string is <variable>.length

**Comment by imrryr** [comment]
I'm sorry my previous question was so unclear

**Comment by JRustyHaner** [comment]
No worries, I just wanted to clarify.

It's literally a one line change to get that for you, so I'm going to knock it out. The variable will be p.answerText and the length will be p.answerText.length.
