### ISSUE TITLE
Skip unit button appears inappropriately

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#511]
**Describe the bug**
![image](https://user-images.githubusercontent.com/13023147/150596553-36c43f9d-b0d0-401b-a0e4-472425608e35.png)

**Comment by JRustyHaner** [comment]
@imrryr the skip unit button always appears when logged in as Administrator or Teacher, but never Student.

**Comment by imrryr** [comment]
Great so this won't be a problem after we have the test login account fixed. Since her registered Gmail is an administrator it's not possible for her to test the student experience right now.

**Comment by imrryr** [comment]
Not account... I mean the test login field

**Comment by JRustyHaner** [comment]
@imrryr Rhodes is looking on that one now, but I'll go ahead and close this
