### ISSUE TITLE
Fails to display tdf... looks easy to fix

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#529]
**Describe the bug**
Screenshot shows it clearly... no button, specific error in console

**Screenshots**
![mofacts_app and 8 more pages - Personal - Microsoft​ Edge 1_28_2022 8_26_54 AM](https://user-images.githubusercontent.com/13023147/151564090-2e52e5e6-7db0-438e-9694-2c33ce17f981.png)

**Comment by JRustyHaner** [comment]
@imrryr  we hotfixed it and redployed

**Comment by imrryr** [comment]
Still fails... very similar error.
![mofacts_app and 9 more pages - Personal - Microsoft​ Edge 1_28_2022 9_19_00 AM](https://user-images.githubusercontent.com/13023147/151572878-548c8985-e01a-4cbb-a10c-fe5c32c7b0e7.png)

**Comment by JRustyHaner** [comment]
@imrryr my build enviorment for some reason wasn't using the most recent postgresMigration. I am rebuilding now. It's an odd bug happening in git.

**Comment by MegaGeese** [comment]
@imrryr latest version deployed for real this time. Tdfs are being displayed again
