### ISSUE TITLE
Crash before first trial

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#532]
**Describe the bug**
Works up to content delivery
![mofacts_app and 11 more pages - Personal - Microsoft​ Edge 1_28_2022 2_21_40 PM](https://user-images.githubusercontent.com/13023147/151616129-21896000-7277-496f-ab0c-1f8aa446e162.png)

**Comment by imrryr** [comment]
Confirmed with old tdf, can't run trials until fixed

**Comment by JRustyHaner** [comment]
@imrryr the answers are not in the syllable database. I fixed neurons, but ranvier isn't in there either, which was my next question. As a fallback, I can default to hintlevel 0 for answers that are not in the dictionary.

**Comment by imrryr** [comment]
But I didn't use a new stim file? Why did this happen now?

**Comment by imrryr** [comment]
Even if more syllables can be produced, we need the fallback in place today to continue testing on schedule. We need to be testing the full system soon otherwise we will encounter problems with delivery.

**Comment by JRustyHaner** [comment]
@imrryr I've added the fallback, it didn't happen in the past because of the full implementation of hint levels.

**Comment by JRustyHaner** [comment]
@imrryr also, it might be a good idea to find a fallback syllable dictionary so that if there is a word that is not in the dictionary, we can still produce some hint data.

**Comment by JRustyHaner** [comment]
I'll build it as soon as Rhodes reviews it. I want to get testing started.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JRustyHaner** [comment]
Building now

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
