### ISSUE TITLE
On some questions, blank answers are reporting correct

### ISSUE THREAD

**Issue by JRustyHaner** [memphis-iis/mofacts-ies#536]
On some answers, inputting nothing returns correct.

**Comment by awindsor** [comment]
For some questions, nothing is the best thing to say!

Alistair

Alistair Windsor
Director | Institute for Intelligent Systems
Associate Professor | Mathematical Sciences
[image: UofM logo] The University of Memphis
355 Dunn Hall | 436A FIT
Memphis, TN 38152

901-318-3912 | memphis.edu <https://www.memphis.edu/>
[image: UofM tw] <https://www.facebook.com/uofmemphis> [image: UofM tw]
<https://twitter.com/uofmemphis> [image: UofM tw]
<https://www.instagram.com/uofmemphis/>

**Comment by JRustyHaner** [comment]
@imrryr this appears to have been fixed with Rhode's latest pull.

**Comment by imrryr** [comment]
Still happens
