### ISSUE TITLE
Inconsistent fill in, the longer one looks correct

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#538]
![mofacts_app and 10 more pages - Personal - Microsoft​ Edge 1_31_2022 12_28_29 PM](https://user-images.githubusercontent.com/13023147/152002797-a0d2ad2c-0484-46ff-891a-914efd17f09f.png)
![mofacts_app and 10 more pages - Personal - Microsoft​ Edge 1_31_2022 12_30_03 PM](https://user-images.githubusercontent.com/13023147/152002800-656e1a90-97c9-48f1-9eff-65bb7551d306.png)

**Comment by imrryr** [comment]
Not sure the relation of this issue with the teacher aid.... I'm talking about the length of the underscores, but maybe they are just combined in the commit.

**Comment by MegaGeese** [comment]
Fixing teacher aid ended up also fixing this issue
