### ISSUE TITLE
Backup database periodically over the IES study

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#54]

**Comment by andrewtackett** [comment]
I've set up a logrotate script that will do a full dump of the database every week and retain the last 10 dumps.  Full script here:

/var/mongobackups/archive.gz {
  rotate 10
  weekly
  notifempty
  postrotate
    mongodump --db=MoFaCT --gzip --archive=/var/mongobackups/
  endscript
}

Working on periodic dump to S3 in case of ec2 instance failure/corruption

**Comment by aolney** [comment]
Is this the best way to do analytics on the data, e.g. looking at the edit history of items by instructors?

**Comment by andrewtackett** [comment]
S3 setup.  Full updated logrotate config here:

/var/mongobackups/archive.gz {
  rotate 10
  weekly
  notifempty
  dateext
  postrotate
    mongodump --db=MoFaCT --gzip --archive=/var/mongobackups/
    /root/.local/bin/aws s3 sync /var/mongobackups/ s3://mofacts.db.dump/ --dele
te
  endscript
}

Will address clozeEditHistory download in a separate issue.
