### ISSUE TITLE
Screenshot of audio popup error

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#542]
**Describe the bug**
Not sure what it is

**To Reproduce**
DK

**Expected behavior**
no popup

**Screenshots**
![2022-01-31_17-57](https://user-images.githubusercontent.com/13023147/152004306-728d3eb9-f668-4458-b31f-788f33119931.png)

**Comment by JRustyHaner** [comment]
@imrryr this is a error returned from the google speech API

**Comment by imrryr** [comment]
Also reported by Amy... If you have any questions about how to remove it Rusty, feel free to ask.

**Comment by JRustyHaner** [comment]
Turn off google speech API
