### ISSUE TITLE
Tooltips running?

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#545]
**Describe the bug**
I got a report that the progress report worked but the tooltips were not seen... Is this user error or an oversight

**Comment by JRustyHaner** [comment]
@imrryr They're running, just hover over the text and it will pop up

**Comment by imrryr** [comment]
From Amy: I think the issue is that I did not know how to access the tooltips information. I fear many students will also not find that information, as there is nothing on the interface to indicate more information is available. They will not hover in the right spot without prompting.

Could we either have the tooltips info as permanent text, or have an icon to indicate more info is available and/or text that says something like “hover on each dial to learn more” ?

**Comment by imrryr** [comment]
So just adding a note below the bottom graph to "hover over the labels to learn more"

**Comment by JRustyHaner** [comment]
@imrryr As a prompt, would a ( i ) information icon be more appropriate?

**Comment by JRustyHaner** [comment]
@imrryr that's an easy one
