### ISSUE TITLE
When posting content stim files are not accepted

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#556]
**Describe the bug**
It says they are accepted, but they don't appear, and tdfs containing them are refused. I'm not sure if the old ones were properly overwritten. If I can't overwrite I will need some way to remove tdfs, but we can talk about other options ... the big problem is I can't get it there at all now. Lets fix that first

**Screenshots**
Note console log for missing tdfs AND present tdfs
![mofacts_app and 2 more pages - Personal - Microsoft​ Edge 2_5_2022 8_10_49 AM](https://user-images.githubusercontent.com/13023147/152656081-7ed921b9-072e-41a1-a0d6-c1a92946bda9.png)

**Comment by JRustyHaner** [comment]
@imrryr #562 will add a delete button, making this issue less important, however, the uploader does need to be looked at.

**Comment by MegaGeese** [comment]
Ive narrowed this down to a problem with overwritting/reuploading stim files. Whenever you reupload a file for whatever reason it is setting all items in the database to the last item in the reuploaded stim file.

**Comment by JRustyHaner** [comment]
@imrryr Rhodes has it figured out, bug is over a year old apparently.

**Comment by imrryr** [comment]
Excellent. I really appreciate all the hard work you guys are putting into
this

**Comment by imrryr** [comment]
I'll expect the database will be cleaned out for the next deployment

**Comment by JRustyHaner** [comment]
@imrryr it'll have to be, that 1 year old error destroyed what you were doing anyways. It was updating all rows of the items table because there wasn't a condition set.
