### ISSUE TITLE
Practice crashes immediately on pressing the Chapter X button

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#558]
It goes to this screen after with console shown:
![mofacts_app and 2 more pages - Personal - Microsoft​ Edge 2_5_2022 8_14_08 AM](https://user-images.githubusercontent.com/13023147/152656196-97c0c0e0-3e5b-4fb1-bac1-65e4684279cb.png)

**Comment by MegaGeese** [comment]
There seems to be a bug in the file uploader. The only item I can find in the db that came from stims is "Yes~Excellent this should make the practice more effective.;.*~That may not be the best choice. We suggest going back and reading the chapter." entered about 1700 times. This same bug is causing the #556 bug
