### ISSUE TITLE
After restarting the practice (2nd login) and going to the other section (the one different than the first login)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#559]
**Describe the bug**
See screenshot, not sure it may come up in related cases, or it may be due to me unassigning and reassigning the tdfs on the teacher assignment screen prior to this problem.

![mofacts_app and 5 more pages - Personal - Microsoft​ Edge 2_5_2022 1_37_20 PM](https://user-images.githubusercontent.com/13023147/152656321-1f8983bd-da1e-4e00-af1a-ed0242f62cf2.png)

**Comment by JRustyHaner** [comment]
@imrryr I'm getting the same.

**Comment by MegaGeese** [comment]
This seems to be caused by a db bug. The bug is occurring because of #556

**Comment by imrryr** [comment]
Still doing this

![mofacts_app and 7 more pages - Personal - Microsoft​ Edge 2_7_2022 4_40_23 PM](https://user-images.githubusercontent.com/13023147/152887395-b8417d21-e0b6-47e6-96a2-a3091fb1e61f.png)

**Comment by imrryr** [comment]
buttons look good!
