### ISSUE TITLE
Some sort of crash

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#560]
**Describe the bug**
I accidentally entered a blank name for the class, and it breaks the function to add classes for the next try

![152813352-fc60319c-c2c7-4df7-9558-6ba8883fd839](https://user-images.githubusercontent.com/13023147/152814015-6ca2ddec-f281-4a61-82be-669f24f3fef5.png)

![mofacts_app and 2 more pages - Personal - Microsoft​ Edge 2_5_2022 8_06_18 AM](https://user-images.githubusercontent.com/13023147/152813890-30e5907f-9b7b-4608-9aa0-fc42663ef442.png)

**Comment by JRustyHaner** [comment]
@imrryr this was an easy one.
