### ISSUE TITLE
Add delete button for content

### ISSUE THREAD

**Issue by JRustyHaner** [memphis-iis/mofacts-ies#561]
Admins should be able to delete TDFs and Stims they own

**Comment by MegaGeese** [comment]
@imrryr as it is now. This solution will delete history, componentstate, and assignments associated with the tdfs/stims selected for deletion. Meaning teachers wont be able to recover assessment data from deleted stims and tdfs.

**Comment by JRustyHaner** [comment]
There's a warning about this below the box. The problem is how the database is structured. We're working on fixing the uploader.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by imrryr** [comment]
How hard is it to make this safer by dumping all that is deleted to a file or something.... this is not a request, it is a question :)

**Comment by JRustyHaner** [comment]
@imrryr It's doable, just run the same function that the data downloader does. The database is set to where it will not let you delete a row if it is linked to another row, and hence the issue. This feature shouldn't have to be used with rhode's fix earlier, but it has potential value.
