### ISSUE TITLE
Can we list the filename on the content assignment to class screen (additionally, perhaps in parens after the lessonname)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#566]
**Describe the bug**
Well, it is sorta a bug, sorta a new feature. Basically, I can't tell the "Chapter X"s apart if there are differences for the control and intervention, i.e. 2 different tdfs for control and intervention. Since that "Chapter X" info is on the buttons, it has to be the same for each condition so it can't be used to differentiate when I assign.

For tonight I will just post the intervention tdfs

**Comment by JRustyHaner** [comment]
@imrryr I don't see anything identifying tdfs as control or intervention besides possibly the filenames, are you using a tag to identify the differences, or would you like the filename listed in the assignment list? We could create a tag that would need to be added to each tdf if needed that would only display during the chapter assignments page.

**Comment by imrryr** [comment]
No I don't think a tag is a good way to generalize this system. I think just listing the file names in the assignment list is going to solve it really well for this use case and for many use cases in the future...

**Comment by imrryr** [comment]
And yes I plan to identify it in the file names
