### ISSUE TITLE
SSO on MoFaCTS

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#569]
Just a placeholder for this issue we are aware of

**Comment by imrryr** [comment]
How is this coming please? Have needed emails been sent? since Bailey may take time to respond, we need to get this initiated...

**Comment by MegaGeese** [comment]
Google SSO is working. Im about to send the email to Southwest about updating the configuration for the new server. Will cc you when that email goes out.

**Comment by MegaGeese** [comment]
Southwest SSO is now working on prod
