### ISSUE TITLE
Correctness in progress wrong after no practice

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#57]
Local user
go in but don't do a trial
go immediately to progress it will show 1 trial completed
go back to practice, it behaves as if it never occurred (despite progress)

Also x axis for correctness needs to be lower

**Comment by andrewtackett** [comment]
This is due to the demographics questions being treated as normal trial questions.  My suggestion is to introduce a new unit deliveryparam that dictates that answers in a given unit shouldn't be treated as correct or incorrect but instead just record the answer.  What do you think @imrryr ?

**Comment by andrewtackett** [comment]
Correctness label fixed with commit: 1c15bfc922f201ea90871bb57319bef7820b97d9

**Comment by imrryr** [comment]
Well, perhaps it is simpler than that. The progress reporting should only apply to the items described in learning sessions, not the assessment sessions.

**Comment by andrewtackett** [comment]
ignore assessment sessions, reset across learning sessions

**Comment by andrewtackett** [comment]
Fixed with commit: 29c2e89869f150bac198cacaeba9b80386c9300a
