### ISSUE TITLE
Not answering yes broke it

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#571]
**Describe the bug**
I came back and said yes, and it worked...
![mofacts_app and 8 more pages - Personal - Microsoft​ Edge 2_7_2022 5_04_48 PM](https://user-images.githubusercontent.com/13023147/152887094-6e59fef2-c2f2-44e0-91bc-c7218d504c3a.png)

**Comment by MegaGeese** [comment]
This will happen if the feedback is in refutation mode. If there is no defined refutation study it will cause this error. I can change this to default to the reviewstudy param if refutationstudy isnt defined
