### ISSUE TITLE
Remove an item function broken...

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#580]
**Describe the bug**
After a few seconds from removing it, the screen goes like this instead of moving on, the second time I tried it this screen only flashed up and then it went to home.... not sure if that is a different or related bug....
![mofacts_app and 3 more pages - Personal - Microsoft​ Edge 2_9_2022 7_55_45 AM](https://user-images.githubusercontent.com/13023147/153215926-7569820d-bfc6-40a4-9497-f34e42f60654.png)

**Comment by imrryr** [comment]
Also, the statement "Please answer every question" should never appear under normal operation. I can't image why that statement is int he code, since there are no contexts when it would have been appropriate.

**Comment by JRustyHaner** [comment]
@imrryr I'm going to fork that into two separate issues
