### ISSUE TITLE
Weirdness with the stability of the settings (From Liz)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#584]
**Describe the bug**
I turned on the "say my answers out loud" and it worked perfectly at picking up my voice when I practiced Chapter 5. I clicked Home and changed it to "I type my answers", then turned on "The computer reads my feedback out loud", and clicked to practice Chapter 9. The countdown timer did not show up when I got answers wrong, and the message "I did not get that. Please try again." would show up in the space to type my answers. This happened for three questions, until I clicked Home, then clicked on Chapter 9 again. 

I asked Liz for more:
When I went between chapters 5 and 9, the issue was that I had turned off speech recognition, and selected to type my answers instead. But the program responded as if I had not turned off speech recognition. So, I was not speaking, and I had selected to type my answers when the message appeared.

**Comment by JRustyHaner** [comment]
@imrryr I doubt this is related to #589, but it makes it difficult to debug. We've fixed #589, but diving into why this occurs when it's explicitly told not to will take a bit more research after #589 is merged.
