### ISSUE TITLE
Still getting a little bit of repetition

### ISSUE THREAD

**Issue by aolney** [memphis-iis/mofacts-ies#586]
**Describe the bug**
Getting some stretches of 4-5 items in a row with the same answer, but it is better than before.

Specifically, the answer is **humerus**

**To Reproduce**

- chrome
- ap 1 control
- aolney202202090902
- Computer reads questions and feedback, I type answers
- ch 9
- refutational feedback

**Expected behavior**

Do not give items with the same answer more than 2 times in a row.

**Desktop (please complete the following information):**

- ubuntu 20.04
- Headphones
- Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by JRustyHaner** [comment]
@aolney this isn't a developer issue, it's with the calculation that Phil is using. I'm going to close this as this issue is not a Dev Team issue.
