### ISSUE TITLE
10+ second delay on feedback as an isolated instance

### ISSUE THREAD

**Issue by aolney** [memphis-iis/mofacts-ies#587]
**Describe the bug**

On answering this item

```
The flexor carpi ulnaris connects the distal end of the __________ to fascia of the palm and flexes the wrist.
```

with this answer

```
ulna
```

The delay in feedback was so long, I thought the system crashed.

**To Reproduce**

- chrome
- ap 1 control
- aolney202202090902
- Computer reads questions and feedback, I type answers
- ch 9
- refutational feedback

**Expected behavior**

Feedback should be immediate or less than 2-3 seconds

**Desktop (please complete the following information):**

- ubuntu 20.04
- Headphones
- Chrome Version 97.0.4692.71 (Official Build) (64-bit)
-

**Comment by JRustyHaner** [comment]
@aolney we're going to watch for this in the future, but I'm going to mark it closed for now.
