### ISSUE TITLE
Spelling error triggering bad refutational feedback

### ISSUE THREAD

**Issue by aolney** [memphis-iis/mofacts-ies#588]
**Describe the bug**

The system is not accepting a simple misspelling, which is then triggering a bad refutational feedback.

``
Many of the __________ involved come from the distal end of the humerus and from the radius and ulna

muslces

Muslces is not right. The right answer is muscles. Muscles and Muscles are two different things. Muscles in the muslces are what you use to move your body. Muslces in the muscles are what your body uses to contract and relax your muscles. Muscular contractions are your body's way of telling your muscles to do what you want them to do
```

**To Reproduce**
Steps to reproduce the behavior:

- chrome
- ap 1 control
- aolney202202090902
- Computer reads questions and feedback, I type answers
- ch 9
- refutational feedback
- type the above answer into the above item

**Expected behavior**
A clear and concise description of what you expected to happen.

The two letter transposition should be recognized by MoFaCTS as the correct answer.

If this cannot happen for some technical reason, I should probably go through the refutational feedback cache for mispelled words so we don't generate bizarre feedback.


**Desktop (please complete the following information):**

- ubuntu 20.04
- Headphones
- Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by JRustyHaner** [comment]
@aolney This is a new one, have you had this problem with answer assessments before? The code hasn't changed and I am curious to see if this worked before.

**Comment by aolney** [comment]
I never noticed a misspelling in the feedback cache, but it is obviously possible.

My understanding is that the system uses edit distance or something similar to correct mispellings if they are sufficiently small.

So one question is whether this misspelling is small enough to be caught by the system

**Comment by aolney** [comment]
Just emailed the new cache to Rusty, cc'ing Phil

**Comment by imrryr** [comment]
Rusty or Rhodes can close if this is in place.
