### ISSUE TITLE
After practicing and checking progress report, modules don't appear on home screen

### ISSUE THREAD

**Issue by aolney** [memphis-iis/mofacts-ies#589]
**Describe the bug**
After practicing and checking progress report, modules don't appear on home screen

**To Reproduce**

- chrome
- ap 1 control
- aolney202202090902
- Computer reads questions and feedback, I type answers
- ch 9
- refutational feedback
- practice for a while
- look at progress report
- go to home

**Expected behavior**

Options for practice modules should always be on home screen

**Screenshots**

![2022-02-09_09-36](https://user-images.githubusercontent.com/4432084/153235070-3ca8336b-0f3d-44c6-beec-28c553d72d5e.png)

**Desktop (please complete the following information):**

- ubuntu 20.04
- Headphones
- Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by MegaGeese** [comment]
This can be reproduced by refreshing the page after logging in through southwest.
