### ISSUE TITLE
Crashed instructor reporting for A&P 1 Chapter 5

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#591]
I was messing around with the date, but that breaks the tool.... see erro
![mofacts_app and 10 more pages - Personal - Microsoft​ Edge 2_9_2022 2_29_01 PM](https://user-images.githubusercontent.com/13023147/153285364-cf9febd7-18f1-4308-8aad-57897e488a80.png)
![mofacts_app and 10 more pages - Personal - Microsoft​ Edge 2_9_2022 2_32_02 PM](https://user-images.githubusercontent.com/13023147/153285365-9e5782f7-60f4-492d-b859-f2ac7c68cb92.png)
r

**Comment by JRustyHaner** [comment]
![image](https://user-images.githubusercontent.com/46696077/153287409-6cda54da-c3d7-4c5c-8b5e-45e7042a53d4.png)
