### ISSUE TITLE
Instructor reports give same info Chapter 9 even when I switch sections

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#592]
**Describe the bug**
It appears to be grouping the data from all Chapter 9's rather than reporting for the section specifcally
![Screenshot 2_9_2022 2_34_04 PM](https://user-images.githubusercontent.com/13023147/153285937-41abd326-26a6-4a25-97f1-817910000b58.png)

**Comment by imrryr** [comment]
When I switch to control the data is identical

**Comment by JRustyHaner** [comment]
@imrryr looking at the data, I would expect your user Id list to be the same. For example, JOHN DOE is in both classes. However, the metrics should not be the same.

**Comment by JRustyHaner** [comment]
@imrryr I created a brand new class, and it had students already in it with trials. I queried the database on it, and found that there were already rows in the table for that class.

**Comment by MegaGeese** [comment]
Anyone that participates in a tdf regardless of which class it was assigned too will appear in all classes that use that tdf. Which is what is causing this bug.

**Comment by awindsor** [comment]
Is there an easy fix?
