### ISSUE TITLE
Blank response crashes system

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#598]
**Describe the bug**
Seems to happen always

**Comment by imrryr** [comment]
Should I call for testing now or wait until this is fixed.... It makes testing awkward, since blank responses are standard when you don't know it. However, if the workflow is better delaying a few hours for a fix, it may make more sense. I suppose it depends just how easy the deployment is...

**Comment by MegaGeese** [comment]
Ill build and deploy this hotfix right now @imrryr

**Comment by JRustyHaner** [comment]
@imrryr  This one's on me, I had a variable out of scope.
