### ISSUE TITLE
TTS reads out some blanks with "less than" and "greater than"

### ISSUE THREAD

**Issue by aolney** [memphis-iis/mofacts-ies#603]
**Describe the bug**
TTS reads out some blanks with "less than" and "greater than". Seems to happen more when there is a hint.

**To Reproduce**

- chrome
- ap 1 control
- aolney202202090902
- all audio options yes
- ch 10
- dialogue feedback
- Wait for this item
```
Sensory receptors convert their information into im________ , which are then transmitted along peripheral nerves to the central nervous system.
```
**Expected behavior**
Don't speak invisible characters

**Desktop (please complete the following information):**

- ubuntu 20.04
- Headphones
- Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by imrryr** [comment]
Also noted by Paul

**Comment by JRustyHaner** [comment]
@imrryr the TTS is reading the html tag to signal underline.

**Comment by imrryr** [comment]
Prolly just have it say .... "Blank" instead?

**Comment by JRustyHaner** [comment]
@imrryr I'm having a regex remove the html tags

**Comment by aolney** [comment]
I'm assuming the fix isn't deployed, because I'm still seeing it.

**Comment by JRustyHaner** [comment]
@aolney No, I usually fix a few bugs before deploying, since building takes time
