### ISSUE TITLE
ASR has trouble with "Ranvier"

### ISSUE THREAD

**Issue by aolney** [memphis-iis/mofacts-ies#604]
**Describe the bug**

Ranvier was recognized as "wrong va" or "rhombus"

**To Reproduce**

- chrome
- ap 1 control
- aolney202202090902
- all audio options yes
- ch 10
- dialogue feedback

**Expected behavior**
ASR should be more forgiving on this word

**Screenshots**

**Desktop (please complete the following information):**

- ubuntu 20.04
- array mic
- Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Additional context**
If you're giving the ASR a word list, it might help to tweak it for items like this that have a non-English pronunciation

**Comment by imrryr** [comment]
The developers don't have time to tweak all the responses for the words. We need a more plausible solution in terms of developer time or we can ignore this.

**Comment by imrryr** [comment]
Also, its not a bug in our software exactly I think, nothing is really broken in our code. It seems the ASR doesn't hear Ranvier is what I hear you saying so the ASR is what is broken... But that the ASR is not our software so we can't fix their bug, we need a new feature to work around their bug, or we need to live with it.

**Comment by awindsor** [comment]
Also the task is a hard one for "general" ASR. Take a single spoken word,
probably a specialist one which occurs with low frequency in regular
speech. We could get better performance by training our own ASR but it is
probably not worthwhile.

A workaround is to have a green list of ASR responses that should be
considered correct. You populate this by having a diverse group of people
give the correct answer and see what ASR returns.

Another possibility is to have people read the whole cloze passage rather
than just the blanks. This gives the ASR engine context for the words and
will improve recognition.

Yours,

Alistair

Alistair Windsor
Director | Institute for Intelligent Systems
Associate Professor | Mathematical Sciences
[image: UofM logo] The University of Memphis
355 Dunn Hall | 436A FIT
Memphis, TN 38152

901-318-3912 | memphis.edu <https://www.memphis.edu/>
[image: UofM tw] <https://www.facebook.com/uofmemphis> [image: UofM tw]
<https://twitter.com/uofmemphis> [image: UofM tw]
<https://www.instagram.com/uofmemphis/>

**Comment by JRustyHaner** [comment]
@awindsor The whitelist would be the easiest to implement, since the google voice recognition API would be only fixed by a collaboration with Google.

**Comment by aolney** [comment]
My understanding is that you guys are giving the ASR expected words, which may be what Rusty is referring to as the whitelist. If so, I suggest expanding it for this item (this suggestion was in my bug report)

If you guys want unit testing of your ASR, I would suggest having the TTS speak the correct answers and see if the ASR picks it up. Any cases where this is a problem would suggest a closer look, e.g. adding to expected words.

**Comment by imrryr** [comment]
It doesn't make sense to implement a whitelist without debugging at the
last minute for only one specific word that we are aware of. Please think
of what is practical at the current time Andrew and Alistair. Rusty or
Rhodes of course can override what I'm saying if he thinks we have time. I
posted several issues with the data output that would have a lot more
urgency...

**Comment by JRustyHaner** [comment]
@imrryr the problem with the whitelist idea is that it would not be comprehensive, since it would be difficult to determine what google's api output would interpret the audio input as. The other issues, are, in my opinion, more important.

**Comment by aolney** [comment]
Closing this as a "won't fix" since there does not appear to be a whitelist for ASR results currently and the problem appears to be quite rare.
