### ISSUE TITLE
Can't reenter tdf

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#605]
**Describe the bug**
I entered as Sally Doe, then I started 21 and went as far as the instructions, then went to the progress report, then home.... I think...

Then I try to reenter 21 and I get this, and it just reloads the buttons... no Chapter 21 is available. Sally Doe is still broken when I close the browser and reload and go to A&P 2 and hit Chapter 21 again. Seems to show the same errors as the screenshot for the first case
![mofacts_app and 10 more pages - Personal - Microsoft​ Edge 2_10_2022 8_21_50 PM](https://user-images.githubusercontent.com/13023147/153528385-8a8c88db-13b4-465d-985c-1c2be2470e27.png)

**Comment by JRustyHaner** [comment]
@imrryr it's erroneously reporting 'TDF completed'

**Comment by JRustyHaner** [comment]
@imrryr The check for if a TDF is finished is if the current unit is the last unit, which makes sense --- initially.  However, the check should be if the last completed unit was the final unit. It's possible to enter a unit not completed and try to return and it reports complete.

**Comment by imrryr** [comment]
got it, glad you found the problem
