### ISSUE TITLE
Potential glitch upon refresh (Paul)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#608]
**Describe the bug**
Potential Error: Going from a trial to the progress menu to the home menu and then refreshing the page displays modules previously unavailable. The modules available after refreshing include modules for Chapters 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 19, 20, and 21. There are two modules for Chapters 10, 11, 12, 16, 17, 20, and 21. The only modules available at the start of testing were 9, 10, 11, and 12

**Comment by JRustyHaner** [comment]
@imrryr  when you hit the refresh button, it triggers the session cleanup, which removes all session variables.

**Comment by imrryr** [comment]
OK, isn't the login info a session variable? Shouldn't it trigger logoff then on refresh... Is there another solution you suggest?

**Comment by JRustyHaner** [comment]
@imrryr I'd check if the variable in question is set, then if not redirect to login
