### ISSUE TITLE
never except blanks

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#612]
**Describe the bug**

Alistair reports this: There is an issue where for long hints the edit distance of hint plus
   blank is within the correct threshold. The code is working correctly when
   it accepts the blank answer because correct is hint + answer is within a
   certain edit distance of correct. To resolve this issue a design decision
   on changing the definition of correct needs to be made.

**Expected behavior**
The simplest fix is to simply run the check to see if it is blank first. In fact, I think this is a sorta a bug, since we should have always been excepting blanks as wrong. It was never in the spec to check for a blank after checking if it matches by edit distance. Checking for a blank will always come first since a blank is always wrong.

**Comment by JRustyHaner** [comment]
@awindsor @imrryr I added this check a while ago for another issue as a stopgap, will reinstate.
