### ISSUE TITLE
Rethink dialogue integration

### ISSUE THREAD

**Issue by aolney** [memphis-iis/mofacts-ies#615]
The more I test the dialogue integration, the more I think it's not the right approach.

A typical AutoTutor sequence is:

- hint
- prompt
- elaborate

where each successive move can be seen as a simplification of the problem bottoming out in elaborate which just gives them the answer.

The first version of the dialogue started them off with a hint. In testing, I realized that didn't make sense because they had just failed a cloze to trigger the dialogue, which is the same level of difficulty as a prompt. So the first version of the dialogue pathologically made the problem harder, not simpler.

The second version of the dialogue (current version) starts them off with a prompt. This is better, but in practice I'm finding it too vague to give a good answer. I think the reason is that AutoTutor frames the entire session with a seed problem, so the student can consider a prompt in the context of a problem statement. The dialogue doesn't have a problem statement, and the only context is the cloze item, which they got wrong, and which is now off the screen.

Here are a couple of thoughts on how we could improve things

1. Keep the trigger for launching the dialogue the same, but leave the cloze item up for context. 

This might make the dialogue questions less vague

2. Keep the trigger the same, but somehow generate a seed question to create context.

3. Consider a new trigger for the dialogue

Perhaps it would be better to trigger the dialogue when we detect a pattern of confusion, rather than them just being wrong on an item. For example, if we used the student model and their history of being correct/incorrect on certain concepts, rather than making a single mistake.

Overall, I'm not very fond of the dialogue condition right now. I much prefer the elaborated feedback condition. It fits better into the current design of the system and seems to be providing more value for learning.

**Comment by imrryr** [comment]
OK, it sounds like we might turn it off and rethink over summer? Or should we consider option 1, which seems the only viable solution now....

**Comment by aolney** [comment]
If you use dialogue as-is, I think the learning will be the same or less than simple feedback. I'd be surprised if it were better. However, you could collect data just to show that.

If you guys want to try #1, I'm happy to evaluate it and see if it feels better. I don't know if the devs will think that is hard to accomplish given all that is going on right now.

If we are making refutational feedback the default, then what we do with dialogue may not matter, because I doubt many people will move off the default.

**Comment by aolney** [comment]
@JRustyHaner @MegaGeese Following up on the simplest option of https://github.com/memphis-iis/mofacts-ies/issues/615#issue-1132835529 , could you please take a look at how difficult it would be to display the cloze item missed at the top of the dialogue pages?

**Comment by MegaGeese** [comment]
Since dialogue and trials happen on the same template it should be simple to display the missed cloze item during dialogue

**Comment by imrryr** [comment]
Please go ahead
