### ISSUE TITLE
New capability for intial studies

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#62]
So the idea is to allow an option for an initial trial to be study, instead of drill, during optimized practice.

The following changes appear to allow for this:

currentTestingHelpers.js, add a studyfirst attribute defaulted to false:
var deliveryParams = {
        'studyfirst': false,
...

unitengine.js, where typically Session.set() only sets for drill replace with this:
//if set to true, first trial is study, then subsequently drill. if false, always drill.
if(getCurrentDeliveryParams().studyfirst=='true'){
            if(card.studyTrialCount == 0){                              
            Session.set("testType", "s");                         
            }else{                                                   
            Session.set("testType", "d");
            }      
            }else{
            Session.set("testType", "d");
            }

**Comment by imrryr** [comment]
Lets do this at the cluster level, so the first item for each cluster is a study trial

**Comment by andrewtackett** [comment]
Your suggestions seemed to work perfectly.  Thanks Phil.

Solved with commit: 88f4474695aae267d671e4b6b2d37f30c3c6328b
