### ISSUE TITLE
Header in data only at the top of file

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#620]
**Describe the bug**
It occurs multiple times

**Comment by JRustyHaner** [comment]
@imrryr I'm guessing that multiple classes or tdfs are being exported, correct? In that case, the script might be just appending the output one tdf to another, reproducing the header for each new class/tdf.

**Comment by imrryr** [comment]
I'm quite sure that's what's happening. It would be a bug
