### ISSUE TITLE
Data txt file is duplicating lines

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#628]
**Describe the bug**
For example, data for 1649274 for Chapter 10 is reported twice in the file. I suspect it probably always happens, but here are the lines I first noticed it:

**Comment by imrryr** [comment]
1649274	Fri, 11 Feb 2022 Chapter_10.json	tdf file	Chapter_10.json	xcondition		schedule condition	A_1	how answered	keypress	1	Reading completed	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Did you read the chapter (yes/no)?"}	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Did you read the chapter (yes/no)?"}	1.64461E+12			yes	correct	1	ATTEMPT	C	RESULT	60059			60031		FALSE	FALSE	1	0	31		0	Yes	{}	0	{}	FALSE	1.64461E+12	2223	2632	4				excellent this should make the practice more effective.		direct																																																																																																																																																																																																																																																																																																																																																																																																							
1649274	Fri, 11 Feb 2022 Chapter_10.json	tdf file	Chapter_10.json	xcondition		schedule condition	N/A	how answered	keypress	2	Learning unit	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"__________ can also be classified by functional differences into the following groups, depending on whether __________ carry information into the CNS, completely within the CNS, or out	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"__________ can also be classified by functional differences into the following groups, depending on whether __________ carry information into the CNS, completely within the CNS, or out	1.64461E+12			neurons	correct	1	ATTEMPT	C	RESULT	60037			60017		FALSE	FALSE	0	17	17		0	Neurons	{}	0	{}	FALSE	1.64461E+12	7516	10510	4				Correct.		direct	210014795	-1134020611	4		1			77	6.08193E-06	__________ can also be classified according to functional differences into the following groups depending on whether they transmit information to the CNS, entirely to the CNS, or outside the CNS.	1	77	24	47		__________ can also be classified by functional differences into the following groups, depending on whether they carry information into the CNS, completely within the CNS, or out of the CNS.	__________ can also be classified by functional differences into the following groups, depending on whether __________ carry information into the CNS, completely within the CNS, or out of the CNS.																																																																																																																																																																																																																																																																																																																																																																																						
1649274	Fri, 11 Feb 2022 Chapter_10.json	tdf file	Chapter_10.json	xcondition		schedule condition	N/A	how answered	keypress	2	Learning unit	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"However, nodes of __________ between Schwann cells or oligodendrocytes interrupt the sheath."}	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"However, nodes of __________ between Schwann cells or oligodendrocytes interrupt the sheath."}	1.64461E+12			ranvier	correct	1	ATTEMPT	C	RESULT	60008			60004		FALSE	FALSE	0	4	4		0	Ranvier	{}	0	{}	FALSE	1.64461E+12	2788	4655	5				Correct.		direct	-340656247	2036283636	6	1	4	4		17	6.08193E-06	However, __________ nodes between Schwann cells or oligodendrocytes destroy the capsule.	2	17	6	7																																																																																																																																																																																																																																																																																																																																																																																									
1649274	Fri, 11 Feb 2022 Chapter_10.json	tdf file	Chapter_10.json	xcondition		schedule condition	N/A	how answered	keypress	2	Learning unit	{"clozeText":"The neurons that conduct __________ from the central nervous system to sensitive structures called effectors perform motor functions in the nervous system."}	{"clozeText":"The neurons that conduct __________ from the central nervous system to sensitive structures called effectors perform motor functions in the nervous system."}	1.64461E+12			impulses	correct	1	ATTEMPT	C	RESULT	60056			60030		FALSE	FALSE	0	30	30	0	2	impulses	{im,pul,ses}	3		FALSE	1.64461E+12	2466	6068	5				Correct.		direct	-1084183046	-105697595	2		6	8		98	3.92415E-06		3	98	68	26																																																																																																																																																																																																																																																																																																																																																																																									
1649274	Fri, 11 Feb 2022 Chapter_10.json	tdf file	Chapter_10.json	xcondition		schedule condition	N/A	how answered	keypress	2	Learning unit	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Released neurotransmitter molecules diffuse across the synaptic cleft and bind to receptors on the postsynaptic cell __________."}	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Released neurotransmitter molecules diffuse across the synaptic cleft and bind to receptors on the postsynaptic cell __________."}	1.64461E+12			membrane	correct	1	ATTEMPT	C	RESULT	60033			60016		FALSE	FALSE	0	16	16		2	membrane	{}	0	{}	FALSE	1.64461E+12	17802	20399	7				Correct.		direct	-77645491	262733541	7		2	1		32	9.31E-07	The released __________ __________ diffuse through the synaptic cleft and bind to receptors on the postsynaptic cell membrane.					ARG1																																																																																																																																																																																																																																																																																																																																																																																								
1649274	Fri, 11 Feb 2022 Chapter_10.json	tdf file	Chapter_10.json	xcondition		schedule condition	N/A	how answered	keypress	2	Learning unit	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"The general pattern is that neurons receive input through the __________ and the cell body, and send output in the form of an impulse conducted away from the cell body, down the axon."}	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"The general pattern is that neurons receive input through the __________ and the cell body, and send output in the form of an impulse conducted away from the cell body, down the axon."}	1.64461E+12			dendrites	correct	1	ATTEMPT	C	RESULT	60052			60027		FALSE	FALSE	0	27	27		0	dendrites	{}	0	{}	FALSE	1.64461E+12	6576	9404	4				Correct.		direct	-453367329	1513536998	3		4	9		84	4.33607E-06	The general formula is that neurons receive input through the __________ and the cell body and send the output in the form of an impulse sent from the cell body down the axon.	2	84	52	28																																																																																																																																																																																																																																																																																																																																																																																									
1649274	Fri, 11 Feb 2022 Chapter_10.json	tdf file	Chapter_10.json	xcondition		schedule condition	N/A	how answered	keypress	2	Learning unit	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"The parts of the Schwann cells that contain most of the cytoplasm and the nuclei remain outside the myelin sheath and comprise a __________, or neurilemmal sheath, which surrounds the m	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"The parts of the Schwann cells that contain most of the cytoplasm and the nuclei remain outside the myelin sheath and comprise a __________, or neurilemmal sheath, which surrounds the m	1.64461E+12			lipid	incorrect	0	ATTEMPT	C	RESULT	60053			60028		FALSE	FALSE	0	28	28		0	neurilemma	{}	0	{}	FALSE	1.64461E+12	13878	15280	11				Lipid is not right. The right answer is neurilemma. The difference is that a lipid is a group of organic compounds that includes triglycerides( fats), phospholipids, and steroids, and the neurilemma is living cellular layer formed from Schwann cells on th		direct	-741266418	1186969889	3		2	23	dobj	84	3.92415E-06	Parts of Schwann cells, which contain most of the cytoplasm and nuclei, remain outside the myelin sheath and contain __________, or neurilemmal sheath, which surrounds the myelin sheath.																																																																																																																																																																																																																																																																																																																																																																																													
1649274	Fri, 11 Feb 2022 Chapter_10.json	tdf file	Chapter_10.json	xcondition		schedule condition	N/A	how answered	keypress	2	Learning unit	{"clozeText":"Sodium ions diffuse through open sodium channels down the __________ of their concentration, which helps attract sodium ions to negative charges on the inner side of the membrane."}	{"clozeText":"Sodium ions diffuse through open sodium channels down the __________ of their concentration, which helps attract sodium ions to negative charges on the inner side of the membrane."}	1.64461E+12			gradient	correct	1	ATTEMPT	C	RESULT	60029			60014		FALSE	FALSE	0	14	14	0	1	gradient	{}	0	{}	FALSE	1.64461E+12	11687	16530	6				Correct.		direct	1135550131	1992806038	6		3	18	pobj	24	3.92415E-06																																																																																																																																																																																																																																																																																																																																																																																														
1649274	Fri, 11 Feb 2022 Chapter_10.json	tdf file	Chapter_10.json	xcondition		schedule condition	N/A	how answered	keypress	2	Learning unit	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Neurons that conduct impulses from the CNS to responsive structures called __________ carry out the motor functions of the nervous system."}	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Neurons that conduct impulses from the CNS to responsive structures called __________ carry out the motor functions of the nervous system."}	1.64461E+12			effectors	correct	1	ATTEMPT	C	RESULT	60056			60030		FALSE	FALSE	0	30	30		1	effectors	{}	0	{}	FALSE	1.64461E+12	6551	8313	4				Correct.		direct	-1084183046	-105697595	2		6	8		98	3.92415E-06		3	98	68	26																																																																																																																																																																																																																																																																																																																																																																																									
1649274	Fri, 11 Feb 2022 Chapter_10.json	tdf file	Chapter_10.json	xcondition		schedule condition	N/A	how answered	timeout	2	Learning unit	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Myelin gives the cell __________ of Schwann cells a higher proportion of lipid than other cell __________."}	{"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Myelin gives the cell __________ of Schwann cells a higher proportion of lipid than other cell __________."}	1.64461E+12			[timeout]	incorrect	0	ATTEMPT	C	RESULT	60049			60026		FALSE	FALSE	0	26	26		2	membranes	{}	0	{}	FALSE	1.64461E+12	30023	30023	12				The correct answer is membranes.		direct	-1785115459	-311905494	3		2	10	dobj	80	3.92415E-06	Myelin provides Schwann's cell membranes with a higher __________ of lipids than other cell membranes.

**Comment by MegaGeese** [comment]
Im not sure what you mean. The content that you posted doesnt have any duplicated lines as far as I can tell.

**Comment by imrryr** [comment]
Sorry, the correct word is rows, which are vertical lines of course

**Comment by imrryr** [comment]
No wait, thats another issue, those two lines are the same. I posted 2 lines here they are again with a line between

1649274 Fri, 11 Feb 2022 Chapter_10.json tdf file Chapter_10.json xcondition schedule condition A_1 how answered keypress 1 Reading completed {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Did you read the chapter (yes/no)?"} {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Did you read the chapter (yes/no)?"} 1.64461E+12 yes correct 1 ATTEMPT C RESULT 60059 60031 FALSE FALSE 1 0 31 0 Yes {} 0 {} FALSE 1.64461E+12 2223 2632 4 excellent this should make the practice more effective. direct
1649274 Fri, 11 Feb 2022 Chapter_10.json tdf file Chapter_10.json xcondition schedule condition N/A how answered keypress 2 Learning unit {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"__________ can also be classified by functional differences into the following groups, depending on whether __________ carry information into the CNS, completely within the CNS, or out {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"__________ can also be classified by functional differences into the following groups, depending on whether __________ carry information into the CNS, completely within the CNS, or out 1.64461E+12 neurons correct 1 ATTEMPT C RESULT 60037 60017 FALSE FALSE 0 17 17 0 Neurons {} 0 {} FALSE 1.64461E+12 7516 10510 4 Correct. direct 210014795 -1134020611 4 1 77 6.08193E-06 __________ can also be classified according to functional differences into the following groups depending on whether they transmit information to the CNS, entirely to the CNS, or outside the CNS. 1 77 24 47 __________ can also be classified by functional differences into the following groups, depending on whether they carry information into the CNS, completely within the CNS, or out of the CNS. __________ can also be classified by functional differences into the following groups, depending on whether __________ carry information into the CNS, completely within the CNS, or out of the CNS.
1649274 Fri, 11 Feb 2022 Chapter_10.json tdf file Chapter_10.json xcondition schedule condition N/A how answered keypress 2 Learning unit {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"However, nodes of __________ between Schwann cells or oligodendrocytes interrupt the sheath."} {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"However, nodes of __________ between Schwann cells or oligodendrocytes interrupt the sheath."} 1.64461E+12 ranvier correct 1 ATTEMPT C RESULT 60008 60004 FALSE FALSE 0 4 4 0 Ranvier {} 0 {} FALSE 1.64461E+12 2788 4655 5 Correct. direct -340656247 2036283636 6 1 4 4 17 6.08193E-06 However, __________ nodes between Schwann cells or oligodendrocytes destroy the capsule. 2 17 6 7
1649274 Fri, 11 Feb 2022 Chapter_10.json tdf file Chapter_10.json xcondition schedule condition N/A how answered keypress 2 Learning unit {"clozeText":"The neurons that conduct __________ from the central nervous system to sensitive structures called effectors perform motor functions in the nervous system."} {"clozeText":"The neurons that conduct __________ from the central nervous system to sensitive structures called effectors perform motor functions in the nervous system."} 1.64461E+12 impulses correct 1 ATTEMPT C RESULT 60056 60030 FALSE FALSE 0 30 30 0 2 impulses {im,pul,ses} 3 FALSE 1.64461E+12 2466 6068 5 Correct. direct -1084183046 -105697595 2 6 8 98 3.92415E-06 3 98 68 26
1649274 Fri, 11 Feb 2022 Chapter_10.json tdf file Chapter_10.json xcondition schedule condition N/A how answered keypress 2 Learning unit {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Released neurotransmitter molecules diffuse across the synaptic cleft and bind to receptors on the postsynaptic cell __________."} {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Released neurotransmitter molecules diffuse across the synaptic cleft and bind to receptors on the postsynaptic cell __________."} 1.64461E+12 membrane correct 1 ATTEMPT C RESULT 60033 60016 FALSE FALSE 0 16 16 2 membrane {} 0 {} FALSE 1.64461E+12 17802 20399 7 Correct. direct -77645491 262733541 7 2 1 32 9.31E-07 The released __________ __________ diffuse through the synaptic cleft and bind to receptors on the postsynaptic cell membrane. ARG1
1649274 Fri, 11 Feb 2022 Chapter_10.json tdf file Chapter_10.json xcondition schedule condition N/A how answered keypress 2 Learning unit {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"The general pattern is that neurons receive input through the __________ and the cell body, and send output in the form of an impulse conducted away from the cell body, down the axon."} {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"The general pattern is that neurons receive input through the __________ and the cell body, and send output in the form of an impulse conducted away from the cell body, down the axon."} 1.64461E+12 dendrites correct 1 ATTEMPT C RESULT 60052 60027 FALSE FALSE 0 27 27 0 dendrites {} 0 {} FALSE 1.64461E+12 6576 9404 4 Correct. direct -453367329 1513536998 3 4 9 84 4.33607E-06 The general formula is that neurons receive input through the __________ and the cell body and send the output in the form of an impulse sent from the cell body down the axon. 2 84 52 28
1649274 Fri, 11 Feb 2022 Chapter_10.json tdf file Chapter_10.json xcondition schedule condition N/A how answered keypress 2 Learning unit {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"The parts of the Schwann cells that contain most of the cytoplasm and the nuclei remain outside the myelin sheath and comprise a __________, or neurilemmal sheath, which surrounds the m {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"The parts of the Schwann cells that contain most of the cytoplasm and the nuclei remain outside the myelin sheath and comprise a __________, or neurilemmal sheath, which surrounds the m 1.64461E+12 lipid incorrect 0 ATTEMPT C RESULT 60053 60028 FALSE FALSE 0 28 28 0 neurilemma {} 0 {} FALSE 1.64461E+12 13878 15280 11 Lipid is not right. The right answer is neurilemma. The difference is that a lipid is a group of organic compounds that includes triglycerides( fats), phospholipids, and steroids, and the neurilemma is living cellular layer formed from Schwann cells on th direct -741266418 1186969889 3 2 23 dobj 84 3.92415E-06 Parts of Schwann cells, which contain most of the cytoplasm and nuclei, remain outside the myelin sheath and contain __________, or neurilemmal sheath, which surrounds the myelin sheath.

1649274 Fri, 11 Feb 2022 Chapter_10.json tdf file Chapter_10.json xcondition schedule condition N/A how answered keypress 2 Learning unit {"clozeText":"Sodium ions diffuse through open sodium channels down the __________ of their concentration, which helps attract sodium ions to negative charges on the inner side of the membrane."} {"clozeText":"Sodium ions diffuse through open sodium channels down the __________ of their concentration, which helps attract sodium ions to negative charges on the inner side of the membrane."} 1.64461E+12 gradient correct 1 ATTEMPT C RESULT 60029 60014 FALSE FALSE 0 14 14 0 1 gradient {} 0 {} FALSE 1.64461E+12 11687 16530 6 Correct. direct 1135550131 1992806038 6 3 18 pobj 24 3.92415E-06
1649274 Fri, 11 Feb 2022 Chapter_10.json tdf file Chapter_10.json xcondition schedule condition N/A how answered keypress 2 Learning unit {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Neurons that conduct impulses from the CNS to responsive structures called __________ carry out the motor functions of the nervous system."} {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Neurons that conduct impulses from the CNS to responsive structures called __________ carry out the motor functions of the nervous system."} 1.64461E+12 effectors correct 1 ATTEMPT C RESULT 60056 60030 FALSE FALSE 0 30 30 1 effectors {} 0 {} FALSE 1.64461E+12 6551 8313 4 Correct. direct -1084183046 -105697595 2 6 8 98 3.92415E-06 3 98 68 26
1649274 Fri, 11 Feb 2022 Chapter_10.json tdf file Chapter_10.json xcondition schedule condition N/A how answered timeout 2 Learning unit {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Myelin gives the cell __________ of Schwann cells a higher proportion of lipid than other cell __________."} {"text":"","audioSrc":null,"imgSrc":null,"videoSrc":null,"clozeText":"Myelin gives the cell __________ of Schwann cells a higher proportion of lipid than other cell __________."} 1.64461E+12 [timeout] incorrect 0 ATTEMPT C RESULT 60049 60026 FALSE FALSE 0 26 26 2 membranes {} 0 {} FALSE 1.64461E+12 30023 30023 12 The correct answer is membranes. direct -1785115459 -311905494 3 2 10 dobj 80 3.92415E-06 Myelin provides Schwann's cell membranes with a higher __________ of lipids than other cell membranes.

**Comment by MegaGeese** [comment]
Is this when you click the "download all tdfs for user:" button or another?

**Comment by imrryr** [comment]
Its the all button...

**Comment by MegaGeese** [comment]
Nah. The query in `getHistoryByTDFfileName` is returning duplicate data.
