### ISSUE TITLE
Tutor Response Subtype 20153 20144 20098 20089

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#629]
**Describe the bug**
This is a datashop column, please leave it blank. As a rule, we should not log database id codes to the data report. It makes it too hard to work with, too hard to share, and there tends to be lost information over time unless one spends a lot of time keeping organized. It is easier to log the actual values for such cases.  Here CF (Correct Answer) contains the response, other columns contain the mode of response, and further data is unneeded.

**Comment by imrryr** [comment]
This is similar to the KC (Cluster) codes, but here it is also redundant, because the response info is logged.

**Comment by JRustyHaner** [comment]
@imrryr  it's being set as the cluster code, I can leave it blank.

**Comment by JRustyHaner** [comment]
'Tutor Response Subtype' was being set to kc_default,
'KC_Default' was being set to stimulusKC,
'KC_Cluster' was being set to clusterKC,
so ithe Tutor Response Subtype was identical to KC_Default in the data download.

**Comment by imrryr** [comment]
very good, so it just needs to not be in the Tutor Response Subtype

**Comment by imrryr** [comment]
I think this may have been done, no?
