### ISSUE TITLE
Incorporating other correct answers into edit distance for assessing student input

### ISSUE THREAD

**Issue by aolney** [memphis-iis/mofacts-ies#63]
### Problem

The current approach to assessing student input seems to go like this

- Compare the student input to the correct answer and if the edit distance is small enough, give full credit

The problem with this approach is that it is not globally sensitive to the discriminations we want students to make. Example:

- thin filaments
- thick filaments

are close enough for edit distance to give credit to the wrong answer, even though these are contrasting concepts in the book that should be kept distinct.

### Proposed solution

Instead of using edit distance on the given answer, try one of the following options

- See if the answer is correct for any of the other cloze items in this section. If it is, don't give credit.
- Calculate edit distance for all answers for cloze items in this section and "resolve" the student answer to the one that is closest. If the closest is not correct for the current item, don't give credit.

The second option is more principled but may take too long to score in practice. The first option would at least prevent us from giving credit when that is clearly the wrong thing to do, though it will fail when they misspell the incorrect answer, e.g.

- thik filaments

**Comment by andrewtackett** [comment]
Go with first option

**Comment by andrewtackett** [comment]
High priority

**Comment by andrewtackett** [comment]
Implemented with commit: 15b7ba9065ce4ed32b63454416b050ca7e66cdba
