### ISSUE TITLE
Entry_Point direct direct direct direct direct jrhaner@southwest.tn.edu/a

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#631]
**Describe the bug**
the ENtry poitn column in the data always reads "direct" except when Rusty tested it for your class.... go figure...  In those case it reads:  jrhaner@southwest.tn.edu/a , but whenever the entry point is one of my posted tdfs, I get "direct" for the trial. Thanks for this new feature by the way, I know its a hassle having a bug on late request.

**Comment by JRustyHaner** [comment]
@imrryr which class/section was this? My theory is that the class didn't have any sections, so it comes to say 'direct' under current logic.

**Comment by imrryr** [comment]
it was all classes, which have no sections
