### ISSUE TITLE
Dialogue trials in data

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#632]
How do we log the data for a dialogue trial? How could I find one to check it?

**Comment by JRustyHaner** [comment]
SELECT * from history WHERE feedbacktype = 'dialogue' ; returns quite a few, which means a lot of dialogue tests were done since last time. Are you not seeing any in the report?

**Comment by imrryr** [comment]
I marked it as research because I can't find it in the data report. They need to be there too, they are a trial. Maybe we need a column, maybe I didn't look in the right column...

**Comment by JRustyHaner** [comment]
Definitely can add a column stating if it's a dialogue trial, if you wish.

**Comment by imrryr** [comment]
I'm looking at the data now, and it appears that Feedback-Text may be blank when it is dialogue?

are we saving either the dialogue prompts or the student response during dialogue now?

**Comment by JRustyHaner** [comment]
@imrryr It is set to the text of the userInteraction div tag in the html (a fairly hacky way of doing things, if the original intention is to get the feedback text, why not do this directly than reading from a UI element?)

**Comment by JRustyHaner** [comment]
@imrryr sorry, feedback text is determined by reading the text within a UI element

**Comment by imrryr** [comment]
But why is it blank then in the data report? Or you mean in the cases where it is working it works this way?

**Comment by JRustyHaner** [comment]
Thats the cases it's working in, however, that text box could be blank, since its a very unreliable way of getting the feedback text. It's like putting a camera at the speedometer of your car and reading the speed from the camera... why not just use the mechanism that the speedometer is reading?

**Comment by imrryr** [comment]
right, I get it, the dialogue is on multiple screens with different HTML structure than the simple and refutational.... But this circles back to the question: are we saving either the dialogue prompts or the student response during dialogue now? It seems no....

**Comment by imrryr** [comment]
OK, we don't expect usage of dialogue to be that high this semester, so we may put this one on the backburner, unless you think we can get it done given other tasks you are seeing. Could we at least record the statements the student types in during dialogue? Perhaps even that is a lot.  

To me it seems odd that this was built without data recording, but I'm sure the reason is that I did not explicitly spec the data recording... If you two see me forget to spec data recording on a new feature it will always be helpful to tell me.

**Comment by JRustyHaner** [comment]
dialogueUserAnswers and dialogueUserPrompts is being recorded to memory, but not to the database. It shouldn't be to hard to pass them along.

**Comment by imrryr** [comment]
Well we'd love to have that info if it is not too much. Lets be careful it doesn't become a timesuck

**Comment by JRustyHaner** [comment]
@imrryr actually, I might be wrong. The column dialogue history should be a JSON object that stores both UserPrompts and UserAnswers. I'm not sure if that's consistent with what you are seeing.

**Comment by imrryr** [comment]
I see the column, I just checked it and it is always blank. Perhaps it isn't loaded because the info is not in the database yet.... but that column could just container the entire dialogue in sequence with a delimiter for turns.... of prompt; response; prompt; response; etc

**Comment by imrryr** [comment]
What is the plan here please? Not sure what was feasible...

**Comment by JRustyHaner** [comment]
@imrryr that's where I am too, it appears as if the history is being written before the dialogue happens, so we have a logic order problem.

**Comment by imrryr** [comment]
OK, so how are we getting the feedback duration of the dialogue, that is really critical, and it looked correct in the data report, but now you have me doubting it. Please do more research on this then I guess right?

**Comment by imrryr** [comment]
@JRustyHaner didn't this get finished? Did it just not get closed?

**Comment by imrryr** [comment]
@JRustyHaner @MegaGeese Just a reminder I did not see any information in the dialogue history column when I downloaded the data. Please help me figure it out by confirming there is some in the database first (I think there is at least a little), then correcting the output.

**Comment by MegaGeese** [comment]
It looks like it's not being passed to the data download thanks to some capitalization errors. Simple enough fix that we can add to today's deployment
