### ISSUE TITLE
Feedback setting button

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#646]
**Describe the bug**
Paul reports:
Trial Not Appearing. I closed the window while in the Progress Menu then logged back in to check if my progress was saved. After logging in, selecting Chapter 11 and selecting Simple Feedback (the conditions I was in prior to closing the window), I pressed the Feedback Settings button while still on the Feedback Settings page. Then I attempted to resume the trials, however no item appeared and the screen remains empty except for the menu buttons and MoFaCTS Student.

**Comment by imrryr** [comment]
Leave it for now

**Comment by JRustyHaner** [comment]
@imrryr ignore that mention, it was mislabled.

**Comment by imrryr** [comment]
Believe fixed
