### ISSUE TITLE
website says not secure

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#648]
**Describe the bug**
![mofacts_app and 4 more pages - Personal - Microsoft​ Edge 2_16_2022 8_01_01 AM](https://user-images.githubusercontent.com/13023147/154280336-883cbd8b-35b9-4548-b121-8b6ddccc6c65.png)

**Comment by JRustyHaner** [comment]
@MegaGeese I'm guessing this is that the SSL cert was supposed to expire, did we ever reup?

**Comment by JRustyHaner** [comment]
@imrryr the other option is that http:// is not redirecting to https://

**Comment by imrryr** [comment]
huh, now I am checking and it isn't doing it...

**Comment by imrryr** [comment]
yes, it is not redirecting, that is the problem...

**Comment by JRustyHaner** [comment]
@imrryr there were two enabled server configurations, for some reason.
