### ISSUE TITLE
Not reporting delivered hint syllables... CF (Display Syllable Indices)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#658]
**Describe the bug**
This column is always empty, shouldn't it provide the indexes for the displayed syllables here, i.e. the hint that is displayed? It doesn't appear the hint is anywhere else. I think this is an old bug that never got fixed earlier in 2021.

**Comment by MegaGeese** [comment]
Just double checking @imrryr, the output for artery at the bottom should be [ar,ter] right?

**Comment by imrryr** [comment]
Assuming it displayed those two syllables as the hint for that trial absolutely that's what I'm expecting

**Comment by MegaGeese** [comment]
@imrryr what is the difference between 'CF (Display Syllable Indices)' and 'CF (Displayed Hint Syllables)"?

**Comment by imrryr** [comment]
I'm not sure they seem redundant to me... I did not specify that there should be these two columns someone did it for me unfortunately. Basically we just need to know the hint syllables.
