### ISSUE TITLE
Freeze on "did you read chapter" answer

### ISSUE THREAD

**Issue by aolney** [memphis-iis/mofacts-ies#663]
**Describe the bug**
Page freezes

**To Reproduce**

1. chrome
2. ap 1 control
3. aolney202202090902
4. all audio options no
5. ch 11
6. progress report
7. home
8. ch 10
9. did you read
10. yes
11. **froze**

**Expected behavior**

Do not freeze

**Screenshots**

![2022-02-16_10-45](https://user-images.githubusercontent.com/4432084/154314448-b99ba825-45fb-47fa-a8ee-0a2fb782c1da.png)

**Desktop (please complete the following information):**

- ubuntu 20.04
- Headphones
- Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Additional context**

Tried to recover by going to home, ch 10 again, but hit same problem

**Comment by JRustyHaner** [comment]
@aolney it's implying that your class was unset as well, I've added a check for that.
