### ISSUE TITLE
After removing the item, it continues to make me wait for the next trial

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#675]
**Describe the bug**
Since the item is bad, it should abbreviate the practice, and record the time so far for the feedback duration

![mofacts_app and 12 more pages - Personal - Microsoft​ Edge 2_19_2022 12_42_45 PM](https://user-images.githubusercontent.com/13023147/154815685-d91932e2-a6d7-4a35-a4a5-a0203423d23f.png)

**Comment by imrryr** [comment]
It also has this problem during the test portion...

**Comment by MegaGeese** [comment]
Issue not fixed from #685
