### ISSUE TITLE
login as John Doe or new user crashes it

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#696]
**Describe the bug**
went to A&P II intervention, logged in and got this
![mofacts_app and 7 more pages - Personal - Microsoft​ Edge 2_22_2022 8_10_51 AM](https://user-images.githubusercontent.com/13023147/155149364-148f738b-a808-4af5-bc06-1aac73d44e67.png)
s

**Comment by imrryr** [comment]
Any login is crashing it. We forgot to preflight I think!

**Comment by JRustyHaner** [comment]
@imrryr routing fix, building and pushing now
