### ISSUE TITLE
Fill in lengths are weird....

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#702]
**Describe the bug**
This is why I suggested a constant length. To fix this let me request a constant length for filling words (eg 20 chars of underline) and constant length for  partial words (eg. 10 characters) otherwise we get perverse results and also provide unplanned additional hints. SOrry I did not spec this better earlier...

**Comment by MegaGeese** [comment]
It looks like this issue never got fixed in #690. Instead it added 10 underscores per syllable. Ill look into what it takes to finalize this issue.
