### ISSUE TITLE
Item removal

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#705]
**Describe the bug**
Can't find the mark for that in data,  maybe I missed it. Maybe I forgot to ask for one earlier.

**Comment by MegaGeese** [comment]
Judging by #703 it looks like I put it in the wrong place. I had previously put it in 'outcome' in the history table and 'showitem' in the componentstate. 

Ill make a new column in history for reported cards so that the outcome is preserved.

**Comment by imrryr** [comment]
The problem was that I didn't see removed in the correct column.... I did
check there also.... Perhaps I missed it I bet the doctor's office but
either solution is fine
