### ISSUE TITLE
Course screen for students

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#71]
When I hit back it goes forward to a blank content screen without login. It should either go back to teacher selection (optimal) or do nothing

**Comment by andrewtackett** [comment]
What page are you on when this happens?  I am unable to replicate this.  Can you send me your console logs additionally?

**Comment by andrewtackett** [comment]
Error presents if you go to the signinsouthwest page, click on a teacher, then hit back, also if you get to the student signin page, then hit back

**Comment by andrewtackett** [comment]
Fixed with commit: b0d0cc5f3897467f19521b1e671d78cbb26b3fab
