### ISSUE TITLE
Progress report blank

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#711]
**Describe the bug**
I did more than 30 trials as Sally, I got no progress report. Top line status showed data was recorded, but database download shows not data... this is not safe, if we are not connected with the database we MUST fail!

I created "Johnny" and watched the console. It appears new participants fail on start...
![mofacts_app and 11 more pages - Personal - Microsoft​ Edge 2_24_2022 6_51_02 AM](https://user-images.githubusercontent.com/13023147/155527726-86ac143a-5b3a-450b-845d-fbd2fb3e531f.png)
![mofacts_app and 11 more pages - Personal - Microsoft​ Edge 2_24_2022 6_50_58 AM](https://user-images.githubusercontent.com/13023147/155527730-050b8eb2-f2ec-4b86-9827-4c097542f740.png)
.

**Comment by imrryr** [comment]
If we see these errors in the console we need to have the system stop.... This is the worst kind of bug. Gets us in trouble with the collaborators... This is the sort of bug if passed to teachers it could cause them to stop working with us.

**Comment by imrryr** [comment]
So, this is preventing me from doing further tests, please spend as much time as possible to get this corrected and test it please thoroughly also. We really need to get a working system today or tomorrow or people will be disappointed with us.

When checking, please check it runs 30 trials and produces a progress report, dropping trials doesn't change the time, and the progress report matches the student reports. Also confirm the appropriate columns are in the data. If we can pass these checks, everything else is meeting spec.

Finally try to make the system safer, by causing "template errors in reading properties of undefined" always crash the system completely.

**Comment by imrryr** [comment]
If I had to guess, this bug is caused by the new efficiency changes... We could roll back those to fix this if needed, but maybe it is easy to fix and make safe.

**Comment by JRustyHaner** [comment]
@imrryr good guess, but somewhat not. Part of the problem lies with some old code that returned all counts to 0. It's something I saw earlier but I thought it was in there for a reason, and that turned out to not be necessary. Basically, if the student performance was empty, it would set it to 0. That's correct behavior. There's another check though that does the same thing, except when its not empty. There are  || (or) symbols there that shouldn't ever be needed.

**Comment by JRustyHaner** [comment]
@imrryr I've removed them, but I'm going to leave this open for a bit to make sure.

**Comment by imrryr** [comment]
How does that explain the data loss? All the practice under Sally seems to have not even been recorded

**Comment by JRustyHaner** [comment]
@imrryr it was effecting the progress report, not the data loss. Sorry, hit the ground running without coffee this morning. We're looking into the data loss.

**Comment by imrryr** [comment]
Well I did check to make sure I was connected to the internet in this case we should also be sure that if the internet becomes disconnected from a client it stops giving practice. If we can't send those updates of the data to the server each round it should stop.

**Comment by MegaGeese** [comment]
@imrryr can you send me the chapter 5 stim and tdf? Ive found the problem and need to test the solution but the issue only happens on that tdf as far as I can see.

**Comment by MegaGeese** [comment]
Looks like the syllable data wasnt being loaded into mongo properly causing the hint level to be undefined which prevented the componentstate from saving. 

Deleting the syllable data and forcing the system to reload the syllables fixed this glitch. 

Im looking into what caused the syllable error and possible ways to detect that error.

**Comment by imrryr** [comment]
Well I did check to make sure I was connected to the internet in this case we should also be sure that if the internet becomes disconnected from a client it stops giving practice. If we can't send those updates of the data to the server each round it should stop.

**Comment by imrryr** [comment]
Rusty had it load the syllables earlier rather than later he changed that code...

**Comment by imrryr** [comment]
He changed that code very recently actually. I'll get you those files

**Comment by MegaGeese** [comment]
I dont think its an issue related to a specific file anymore. When I cleared the chapter 5 data from the syllable table and had it recreate the data it started working again. For whatever reason it didnt complete the syllable cache creation.
