### ISSUE TITLE
No hints

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#714]
**Describe the bug**
I got 0 hints this morning for the 30 trials as Sally... I also became convinced the hints were turned off. Please check that it gives hints.

I got so distracted by the data loss I forgot to report this

**Comment by MegaGeese** [comment]
![image](https://user-images.githubusercontent.com/50426711/155602041-c172c828-0fa4-458c-b8ee-fc3fb762046d.png)
System does give hints. This bug might be an extension of #711 glitch. Also many of the answers in chapter 5 are 1-2 syllables long at the start of the trial causing hints not to be displayed
