### ISSUE TITLE
Total introduced wrong in progress report

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#720]
**Describe the bug**
Item.ids are not unique for items, so when we count them it doesn't work...

Here I was looking at the clusters ids, then item ids within cluster (only 1) and then stimuli within cluster (multiple)

Since item ids are not unique for each item, counting them doesn't work.

![mofacts_pavlik@southwest tn edu_all_tdf_data txt_25_2_2022 (2) txt - Excel 2_25_2022 5_13_05 PM](https://user-images.githubusercontent.com/13023147/155815690-2f29e423-e127-4611-b298-95684e0dcdb9.png)

**Comment by imrryr** [comment]
I found this after doing about 240 trials as one user, and it really did get stuck on the cluster total out of the item total with enough practice...

**Comment by imrryr** [comment]
![mofacts_app and 10 more pages - Personal - Microsoft​ Edge 2_25_2022 2_22_31 PM](https://user-images.githubusercontent.com/13023147/156000700-ae4f1776-10f4-4483-be9d-66f62e9777d6.png)

**Comment by imrryr** [comment]
Also, can we research how Items mastered per minute: 0.56 is calculated? please send me the query in email or we can discuss it when I am in this morning

**Comment by MegaGeese** [comment]
![image](https://user-images.githubusercontent.com/50426711/156021624-df1fc5ef-e03e-42d4-ace8-419cfdaf5274.png)
It looks like the systems isnt calculating the probability for stims that arent the first in their cluster. This would explain why its only showing the first stims of each cluster and why it would be stuck on 32 when there are 32 clusters.

**Comment by imrryr** [comment]
OMG, well, better finding it today than later...

**Comment by MegaGeese** [comment]
```js
p.y  = intercept    + .68 * logitdec(
                        p.overallOutcomeHistory.slice(Math.max(p.overallOutcomeHistory.length-60,1),
                        p.overallOutcomeHistory.length), .96) +
                    .18 * logitdec(p.responseOutcomeHistory, .81) +
                    3.34 * recency(p.stimSecsSinceLastShown, .27) +
                    .95 *  recency(p.responseSecsSinceLastShown, .06) +
                    .31  * linediffcor(p.stimOutcomeHistory, p.stimPreviousCalculatedProbabilities) +
                    -.31 * quaddiffcor(p.stimOutcomeHistory, p.stimPreviousCalculatedProbabilities) +
                    -.20 * arrSum(errlist(p.stimOutcomeHistory)) +
                    -.61* Math.log(p.answerText.length);
```

This is the probability's y intercept calculation. This is where this error is coming from because `p.stimPreviousCalculatedProbabilities` is an empty array until the stim has been answered once. This is causing p.probability to become NaN which means it will never be selected for a trial.

I also ran some querys on the mofacts db and confirmed that the only stims that have been shown are ones that are first in their cluster.

**Comment by MegaGeese** [comment]
That last bit might have been a red herring. I need to do more debugging.

**Comment by imrryr** [comment]
This is how those functions expect to receive empty lists:
function mul(m1, m2) {  var result = 0;
var len = m1.length;
for (var i = 0; i < len; i++) {             result += m1[i] * m2[i]           }  return result     };


function quaddiffcor(seq, probs) {           return mul(seq, probs.map(function(value) {                return value * value         }))
}         

function quaddiffincor(seq, probs) {          return mul(Math.abs(seq-1), probs.map(function(value) {                return value * value        }))        }

function linediffincor(seq, probs) { return mul(seq.map(function(value) {                return Math.abs(value - 1)            }), probs)          };

console.log(linediffincor([],[]));

**Comment by MegaGeese** [comment]
It looks like the history is reporting wrong too. In history:
![image](https://user-images.githubusercontent.com/50426711/156045621-9420c59c-db34-45e4-85be-8c86d38010d8.png)

The KCID is being set to the stim that it first in this stim's cluster (30045 instead of 30048)

Here is the cluster for reference: 
![image](https://user-images.githubusercontent.com/50426711/156045851-5ee694db-710c-4fed-9a59-a9a9f59b6984.png)

**Comment by MegaGeese** [comment]
After fixing this and practicing 100 trials the dial seems to work again

![image](https://user-images.githubusercontent.com/50426711/156048102-75d9ce70-4d6c-403b-a70c-340cdd202301.png)

**Comment by imrryr** [comment]
OK, but 356 minutes is wrong, since it should be 0, right?

**Comment by imrryr** [comment]
Are you testing with an old version of the stim file? The .82 value should be .70 in the new files.

**Comment by MegaGeese** [comment]
Im using the stim and tdf files for chapter 5 that you sent on the 24th
