### ISSUE TITLE
Progress report values wrong

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#729]
**Describe the bug**
Note the learning rate is 0, but I got 16 introduced, and it is supposed  to be log(introduced + 1 ) in last 30 trials.... 

Also, note my % correct is low, but the speed of learning graph says that it is isn't too hard, but it should read about a third of the way into too hard..
![mofacts_app and 5 more pages - Personal - Microsoft​ Edge 3_1_2022 4_35_28 PM (1)](https://user-images.githubusercontent.com/13023147/156260787-40c2b15c-c760-4f80-9fb6-301b6f08cf8b.png)
![mofacts_app and 5 more pages - Personal - Microsoft​ Edge 3_1_2022 4_35_56 PM](https://user-images.githubusercontent.com/13023147/156260795-c86c1a4c-04b3-4e33-a3a3-7d3950e4b155.png)

**Comment by MegaGeese** [comment]
It looks like we're limiting the wrong thing on the sql querys. Limiting component state would only pick the last x number of stims in the list instead of limiting history which would get the last x trials.
