### ISSUE TITLE
Finish dockerizing mofacts

### ISSUE THREAD

**Issue by andrewtackett** [memphis-iis/mofacts-ies#73]
Ensure this works on docker for windows and mac as well as ubuntu

**Comment by andrewtackett** [comment]
Docker toolbox for Home versions of windows required (This installs virtual box under the hood).  Also required for MacOSX versions <= 10.12.

Docker toolbox doesn't exist for linux so the setup process for linux will be different.

By default Docker toolbox only exposes /Users (mac) and C:\Users (windows) subdirectories as mount volumes.  This means mofacts will need to be installed to those locations (or we can publish an image to dockerhub and have a setup script download the image for us).

Docker toolbox uses host-only networking for the guest vm that runs the docker containers.  This presents a problem for allowing users to access via localhost:3000.

Solution: 
-Make a script (one for windows, one for unix) to run:

```
VBoxManage = ""
if env_var VBOX_MSI_INSTALL_PATH exists:
  VBoxManage = %VBOX_MSI_INSTALL_PATH%\VBoxManage.exe
else:
  VBoxManage = %VBOX_INSTALL_PATH%\VBoxManage.exe

VBoxManage modifyvm "default" natpf1 "tcp-port3000,tcp,0.0.0.0,3000,,3000" (if the machine is powered down)
VBoxManage controlvm "default" natpf1 "tcp-port3000,tcp,0.0.0.0,3000,,3000" (if the machine is running)
```

**Comment by andrewtackett** [comment]
http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js/

https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

**Comment by andrewtackett** [comment]
Need to set up docker compose script with a mongo container that has a mount volume (only to the container vm level, not the host OS level) for nontechnical users.

Also configure host container vm in setup script to be larger than defaults.

**Comment by JRustyHaner** [comment]
@imrryr  this has been done with Meteor Up
