### ISSUE TITLE
Console error and Missing hints

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#734]
**Describe the bug**
After noticing the problem with progress reports, I went to continue chapter 5, I saw this in the console... looks importan
![mofacts_app and 12 more pages - Personal - Microsoft​ Edge 3_3_2022 9_09_47 AM](https://user-images.githubusercontent.com/13023147/156592910-6160eed7-8e01-463c-94cf-cfd7d94e8cc2.png)
t

**Comment by imrryr** [comment]
After continuing to practice I get this, and it seems to happen before every trial...
![mofacts_app and 12 more pages - Personal - Microsoft​ Edge 3_3_2022 9_11_51 AM](https://user-images.githubusercontent.com/13023147/156593085-e6c6532f-0c0d-4535-b543-5cdc7dad162d.png)
:

**Comment by MegaGeese** [comment]
For whatever reason #724 tries to reupload the stim syllables between each card instead of on re-upload of a stim file as the title suggests.

**Comment by MegaGeese** [comment]
this was happening because the stim syllable database hadnt updated causing the system to break. This is fixed.
