### ISSUE TITLE
Bad load on database or deploy

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#740]
**Describe the bug**
Logging in as Amanda I see no classes in instructor report... can't find students to test and continue.... can't verify teacher report

Classes do appear when logging in as student for Amanda, so something was loaded... just doesn't work

![mofacts_app and 10 more pages - Personal - Microsoft​ Edge 3_7_2022 8_03_55 AM](https://user-images.githubusercontent.com/13023147/157049015-78b38aec-56d4-4d0e-bdc0-241931d60780.png)

**Comment by MegaGeese** [comment]
updated the mongo db. Seems something went wrong when I did it Friday.
