### ISSUE TITLE
Small glitch in instructor report

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#742]
**Describe the bug**
One of these minute amounts is too high
![mofacts_app and 12 more pages - Personal - Microsoft​ Edge 3_8_2022 3_38_58 PM](https://user-images.githubusercontent.com/13023147/157329729-41110559-0692-47ea-8906-90ab4e9e9c3f.png)

**Comment by MegaGeese** [comment]
So I found out that this is because the user's start time stamp ended up being set to 0. Not sure how that was possible and I'm investigating what caused it.

**Comment by MegaGeese** [comment]
This is happening when a user will navigate from card to home and back to card after they answer. This is causing a timeout to fire that otherwise wouldn't.
