### ISSUE TITLE
Autologoff is worse....

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#748]
**Describe the bug**
Logs off automatically seems a bt worse... saw it twice in a row...

**Comment by imrryr** [comment]
This is on mofacts... observed it twice when working with Amy and Liz...

**Comment by imrryr** [comment]
well, that explains that. Please do that if it doesn't present any other risk than the downtime...

**Comment by MegaGeese** [comment]
fix was deployed.
