### ISSUE TITLE
TTS is reading 'nbsp;' instead of 'blank' for trials

### ISSUE THREAD

**Issue by MegaGeese** [memphis-iis/mofacts-ies#765]
**To Reproduce**
Enable TTS
Run a trial that has text responses

**Expected behavior**
System should not read "nbsp;" on TTS

**Comment by MegaGeese** [comment]
@imrryr on TTS should the system say "blank" for the blank regardless of hint, or should it try to pronounce the hint + "blank"?

**Comment by imrryr** [comment]
I don't think it should pronounce the hint I think it should just still say blank for the entire construction of hint plus blank

**Comment by imrryr** [comment]
On second thought if it pronounces the hint okay that actually might be better. I appreciate you noticing this edge case
