### ISSUE TITLE
Remove hardcoded values from code

### ISSUE THREAD

**Issue by andrewtackett** [memphis-iis/mofacts-ies#78]
Set up database collection and possibly new pages to select values to appear in content generation template dropdown, test logins, and teacher class redirects (blaudow to amanda)

**Comment by andrewtackett** [comment]
Set up tdf template selection for braintrust content generation instead of having json pasted into code.

**Comment by imrryr** [comment]
For example, any hardcoding of the probabilities in the selection functions, this is old legacy code

**Comment by imrryr** [comment]
Leftover issue here is making a plan for SSO and Southwest access

**Comment by imrryr** [comment]
For the SSO and southwest, lets just make all of the info configurable variables and not actually have southwest in the URL as well. Any Mofacts instance will be configurable for a signal SSO.
