### ISSUE TITLE
commas in stimuli buttons cause odd button multiplication

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#783]
**Describe the bug**
Screenshot shows it, 2 of the buttons "not sure, guess agree" and "not sure, guess disagree" got split..
![mofacts_app and 5 more pages - Personal - Microsoft​ Edge 4_12_2022 12_29_03 PM](https://user-images.githubusercontent.com/13023147/163589736-f3da787a-0461-497b-a080-57f483386e06.png)
.

**Comment by MegaGeese** [comment]
since the values in the tdf are assumed to be a comma-separated list the system will think that they're distinct options. 

Fixing this will require updating this tdf (and others that have commas in their button options) from a comma-separated list into an array.
