### ISSUE TITLE
Safari TTS bug

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#786]
**Describe the bug**
Reported by Liz: The participant was using Safari as their web browser. When they selected "The computer reads the questions out loud", the system did not read the questions out loud. He logged out, clicked on the link and logged in again. He selected "The computer reads the questions out loud" again, but the system again did not read the questions out loud. 

Possible solution (on Safari, gray out the option for reading, and note "not available on Safari"

**Comment by MegaGeese** [comment]
https://browserhow.com/how-to-allow-or-block-auto-play-sound-access-in-safari-mac/

Looks like this is "working as intended" according to apple's spec. We can add instructions on how safari users can enable TTS on their browser.
