### ISSUE TITLE
Best label for tags in stim file

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#790]
Andrew Olney is using identifiers in the current stim files that are named in a way that should be revised. He calls each clozeId and itemId, but I think they should be "itemId" (his clozeId) and "clusterId" (his itemId), however, I wanted to check in on that about what is most consistent with the code usage (just for semantic sake, even though the tag ids are not used in the code now I think).

It's possible "stimId" and "clusterId" is more consistent with the code usage... And yes, I understand his tag ids are not used by the main code (AFAIK).

What do you think is best for these labels for the Cluster/sentence and the Item/stimulus fill-in

**Comment by aolney** [comment]
@JRustyHaner @MegaGeese Any thoughts on the label I should use?

**Comment by MegaGeese** [comment]
stimulusId can be used to replace clozeId and clusterId to replace itemId. itemId is used to represent the id as it is in the database so I think stimulusId would be more accurate.
