### ISSUE TITLE
Ease of remote deployment

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#792]
Set up steps and components
Simple version (one-step) i.e. step minimization
Modular server organization
Meteor up docker image and tutorials

**Comment by JRustyHaner** [comment]
@imrryr @aolney 

Apartently, Meteor Up can automate creation of a docker image for us, and store it in a private docker repository for people to use. So It wouldn't be hard to support both methods of deployment.

**Comment by imrryr** [comment]
make sure Settings.json contains everything, including any keys in root folder of project

**Comment by JRustyHaner** [comment]
@imrryr the google key I saw in settings.json was the key for the sign in for google services. It seems that email is set using an environment variable on the server and is just the standard SMTP host, port, username, and password. This would imply that for new deployments, setting a requirement of having their own smtp server at their organization, or using a free one like google, is the most likely setup.  

As an interesting note, UofM doen't allow POP3/SMTP access to their mail server, so it wouldn't work if we wanted to use a @memphis.edu email.
