### ISSUE TITLE
Asset uploader fails

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#806]
**Describe the bug**
For an unknown reason. Was logged in as ppavlik@southwest... Here is the image and error...
![image001](https://user-images.githubusercontent.com/13023147/169825946-408b98d1-5447-4692-b888-827f55572cbb.gif)
![mofacts_app and 13 more pages - Personal - Microsoft​ Edge 5_23_2022 8_03_48 AM](https://user-images.githubusercontent.com/13023147/169826035-6ee4bf3a-070f-41a0-9a99-0a429e793826.png)

**Comment by imrryr** [comment]
It was a gif file

**Comment by JRustyHaner** [comment]
I'll look at it today, it might not be on the approved extension list.
