### ISSUE TITLE
Error Message About Hints

### ISSUE THREAD

**Issue by Brtelfer** [memphis-iis/mofacts-ies#823]
Something went wrong about generating hints

1. Go to Optimized Practice of Greek letter names in TDF + practice modules
2. Go through age, gender, education and select continue
3. Produces a blank screen

**Comment by imrryr** [comment]
![mofacts_app and 10 more pages - Personal - Microsoft​ Edge 6_7_2022 10_17_54 AM](https://user-images.githubusercontent.com/13023147/172653408-1abfe090-47a9-4fcb-8d23-456ac667bc9f.png)

**Comment by imrryr** [comment]
Example of the problem

**Comment by MegaGeese** [comment]
Should be fixed now. Leaving this open so that I can investigate what caused it @imrryr

**Comment by imrryr** [comment]
Well it seems I know what caused it it's that there aren't any hints in this system they cannot be generated... But you say that there's some sort of work around in place on staging now?

**Comment by MegaGeese** [comment]
Yeah the workaround is forcing the system to regenerate the syllables by deleting the stimuli syllables document from the database. This bug is a product of the postgres database being cleared but not mongodb. 

This is something that is fixed by the postgres reversion but that branch is not quite ready to be pulled.

**Comment by Brtelfer** [comment]
Here is an example of the problem in another Json TDF.

![image](https://user-images.githubusercontent.com/106611498/172659134-f7b69c4d-b915-48a0-97e6-e117aed9f7af.png)

**Comment by Brtelfer** [comment]
I have retested Optimized Practice of Greek letter names and the error message about hints appears to be resolved.
