### ISSUE TITLE
Chapter 10 and 12 fail on read the chapter questions (also some other higher chapters like 17 have this issue)

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#834]
**Describe the bug**
Some problem when it plays the question about whether they read the textbook. Can't figure out what it is; I'm doing pretty much everything the same in these tdfs and stim files... 
![mofacts_app and 7 more pages - Personal - Microsoft​ Edge 6_17_2022 4_13_11 PM](https://user-images.githubusercontent.com/13023147/174404655-c772c153-6f9d-4b2c-8a8a-d223e3842600.png)
 chapters... I double-checked the cluster assigned to the unit for this question, and it appears I did it correctly

**Comment by MegaGeese** [comment]
@imrryr can you send me a copy of the files that you uploaded for these chapters?

**Comment by imrryr** [comment]
@MegaGeese 
For Chapters 10, 12, 16, and 17 (which all fail) can we immediately point their stimulus files to the correct file path? Since no one can do practice in these units anyhow, this seems safe, and it also reduces the problem of it being fully broken.

Amanda is starting Chapter 10 tomorrow and Chapter 16 by the end of the week, but this fix will prevent the problem from affecting students in those chapters at all....

Additionally, this should be done for all chapters where there was no practice....

Let's just leave it alone in the other Chapters unless you turn up something simple.

**Comment by MegaGeese** [comment]
Ive gone ahead and done so for chapters 10, 12, 16, and 17. I've tested them and they are working. I'll go ahead and see if there are other chapters that I can fix this way.

**Comment by imrryr** [comment]
20 and 21 are not released to students so should only have test users 100% for sure

**Comment by MegaGeese** [comment]
These chapters have been fixed. I've also concluded that fixing the stims without clearing the experiment state will cause the system to crash due to the cluster mapping being different. I could potentially make the cluster mapping regenerate with a valid mapping for these chapters.

**Comment by imrryr** [comment]
"I've also concluded that fixing the stims without clearing the experiment state will cause the system to crash due to the cluster mapping being different." OK, so you cleared the state to get these other ones running... is what you are saying. I think it is probably best to leave the working ones alone then...

**Comment by MegaGeese** [comment]
Yes I had to clear the experiment states to get the modified ones working again.
