### ISSUE TITLE
Error Message About Package Uploading

### ISSUE THREAD

**Issue by Brtelfer** [memphis-iis/mofacts-ies#835]
Package upload failed.

From the media asset uploading, this message is displayed when I upload a zipped file with ArabicAlphOptim stims and TDF. The generated link still appears to work as intended.
![image](https://user-images.githubusercontent.com/106611498/174504382-13e90f00-dbe0-451b-abe5-0eaba32635d5.png)

**Comment by JRustyHaner** [comment]
@Brtelfer check now please, it was a missing node module on the server.

**Comment by Brtelfer** [comment]
@JRustyHaner still getting an error message upon upload:

![image](https://user-images.githubusercontent.com/106611498/174830560-fa82e318-00ad-4acd-8a31-53c7bd9f9b78.png)
