### ISSUE TITLE
Call back emails and lockout units

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#848]
We need to get this working again, first without Turk. To do that we will need to have a user account that saves an email when the user creates their account. Currently, we do not have access to the email so we need to add a user type that requires email. This will be a different login screen which will be provided when we need users to use this function.

The basic plan is to get this unit type working with the real email rather than the Turk email. Once and if we rebuild the Turk functions then we could send the email either way, but for now this issue is independent of the Turk issue.

The purpose of the lockout unit type is to create randomized long-term retention intervals during a research study. This unit will not let them pass (I think it shows a timer) until their randomized lockout period has elapses.

Here is an example:
          {
                "turkemailsubject": "Link for 3$ Bonus for Turk HIT",
                "turkemail": "\r\nDear Amazon Turk Worker,\r\nRecently you completed part 1 of a 2 part experiment called 'Memory for Statistics Experiment 3', which paid $2.00. Now we would appreciate it if you would please return do part 2. It is a bit less work than part 1, but we pay a $3.00 bonus for completion, since it is so important for us to get the part 2 data. This must be completed in the next 48 hours from when you get this email.\r\nPlease avoid typos in your Turk ID, since then we cannot identify you as a part 2 person and cannot pay your bonus. You know you have continued correctly if it says 'Thanks for continuing. You have 54 sentences remaining.'\r\nHere is the link to finish: http://mofacts.optimallearning.org/experiment/svo\r\nThanks for your help,\r\nPhil\r\n        ",
                "unitinstructions": "You have completed Session 1 of the experiment.\r\n<br><br>\r\n<strong>Please enter the code- Ferrets -into the Amazon Mechanical Turk website for this HIT and submit your response now.\r\n<br><br>\r\nWe will check your completion and approve your assignment for the $2 payment. If the countdown below is 2 minutes: Please wait for the countdown to finish and take the posttest for the $3 bonus now.\r\n<br><br>\r\nIf the countdown below is 1 day or 3 days, you will receive a private Turk message (delivered to your email inbox) for instructions on Session 2. Session 2 earns a $3 bonus.",
                "unitname": "Lockout unit",
                "deliveryparams": [
                    {
                        "lockoutminutes": "2"
                    },
                    {
                        "lockoutminutes": "1440"
                    },
                    {
                        "lockoutminutes": "4320"
                    }
                ]
            },

**Comment by JRustyHaner** [comment]
@imrryr  I'm going to work on this is stages, since it can be broken up

**Comment by JRustyHaner** [comment]
@imrryr technically, when you use the general signup page (not southwest or mTurk: staging.optimallearning.org/signup ), the form has a field for email as the user's account username.  

What I'm reading for action steps are:
- Set up email verification 
- Invitation to start a trial is sent at a calculated/random interval after signup
- Participant completes trial
- New calculated/random interval generated
- repeat ad infinitum
-

**Comment by imrryr** [comment]
First step is fine.

I'm not sure if I understand the invitation step. Usually start is immediately after logging in, but in theory, you could put one of these lockouts as the first unit, but why? Maybe you are realizing edge cases that are useful to cover.

What does a participant completing trial mean? This should occur as a unit in the tdf, so completion doesn't happen... Maybe you mean a unit

I not sure why you call it a "new" random interval, but in theory, we could have multiple lockout units in a tdf, each randomizing for different lockout durations. Again perhaps this is just a natural edge case, good thinking for considering it. Good to handle it.

Yes, the sequence of units continues after each lockout, until we run out of units.

**Comment by JRustyHaner** [comment]
@imrryr to require an email type specifically for that unit type, we would have to know the unit type before signing up for that class. I assume other unit types will require that we keep the participant anonymous. We will have to know if the participant is in a class/section that has a TDF that has that unit type before they sign up or, if they do not have an email address on file, then prompt for it at the beginning of the first trial. 

What I am reading:
-A unit can have a parameter that locks the participant for a predetermined time after their first time of running a unit. 
-If this unit is part of a class/section, then the signup form will include an email address field.
-If the participant is logged in and does not have an email on file, it will be prompted for when logging into a class/section that has a tdf with a unit lockout parameter set.
-Before the time has elapsed, the participant will be unable to access that unit.
-After the time is elapsed, an email will be sent to the participant indicating a lockout has passed and the unit will be accessible

Edge Cases:
-Units could have an initial lockout to where the unit is not available until a lockout period has elapsed since signup
-Units could have a array of timeouts possible, each participant's individual lockouts are randomly selected from this array
-Units could have a timeout calculation, similar to the probability function, which sets the lockout based on a custom function

**Comment by imrryr** [comment]
What I am reading:
-A unit can have a parameter that locks the participant for a predetermined time after their first time of running a unit.
Yes, locks them out of the next unit, this is a unit type in my mind, not an option for units

-If this unit is part of a class/section, then the signup form will include an email address field.
Part of a tdf you mean, then the tdf would not run for the student unless the account had an email associated. We could just prevent it from operating with a pop-up message to "add an email to their account to run the tdf, since it requires a callback email"

-If the participant is logged in and does not have an email on file, it will be prompted for when logging into a class/section that has a tdf with a unit lockout parameter set.
That makes sense and is a good feature

-Before the time has elapsed, the participant will be unable to access that unit.
The unit after the unit... If the lockout unit is unit 6, they can't move to unit 7. I believe then we had it set so that unit 6 would display the remaining time, and a continue button would be enabled after the time elapses

-After the time is elapsed, an email will be sent to the participant indicating a lockout has passed and the unit will be accessible
Right, the next unit is then accessible

Edge Cases:
-Units could have an initial lockout to where the unit is not available until a lockout period has elapsed since signup
Hypothetically, but that fits within the spec above

-Units could have a array of timeouts possible, each participant's individual lockouts are randomly selected from this array
Yes, allowing basic experimental test of duration of learning

-Units could have a timeout calculation, similar to the probability function, which sets the lockout based on a custom function
The idea is coherent, but I don't think I'd use this feature.
