### ISSUE TITLE
Zip File uploading doesn't generate practice button

### ISSUE THREAD

**Issue by MegaGeese** [memphis-iis/mofacts-ies#851]
**Describe the bug**
ZIP files uploaded sometimes doesn't create a practice button. If an individual file is uploaded through the original uploader then it generates two buttons. Deleting this file will delete both buttons

**Expected behavior**
ZIP uploader should create practice button.

**Comment by JRustyHaner** [comment]
@imrryr I am unable to reproduce this locally. Could you send me the zip file?

**Comment by Brtelfer** [comment]
[Countries Tutor.zip](https://github.com/memphis-iis/mofacts-ies/files/8996595/Countries.Tutor.zip)
[Countries Tutor.zip](https://github.com/memphis-iis/mofacts-ies/files/8996634/Countries.Tutor.zip)

I was able to replicate the behavior (generating two buttons) with the first listed zip file.
The behavior does not appear with the second listed zip file.

I believe the only difference is that the second zipped file has "userselect": "true", in WorldtestV2.json under "setspec"

**Comment by JRustyHaner** [comment]
@imrryr @Brtelfer This has been fixed, and folders are now supported. Although, looking through your stim, I am seeing that the images you are using are being inputed as clozeText and not imgSrc. This will make the urls display as the cloze, not the image itself.
