### ISSUE TITLE
Disabling help causing unneeded flashing

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#855]
**Describe the bug**
We are disabling the help screen during feedback (why was this necessary, since it is not a design feature? maybe we can just not do it to solve this issue), even when there is no feedback. This causes the help button to flash during no feedback trials. So at the least, lets not do it when there is no feedback.

**To Reproduce**
Do the IES survey

**Expected behavior**
Help button shows no effect

**Comment by JRustyHaner** [comment]
@imrryr the help button when used during refutation does not stop the refutation timer from finishing, the next card loaded anyways. The solution we discussed was to disable the help button during refutation.

**Comment by imrryr** [comment]
It is apparently doing it in a more general fashion however... Unless I somehow set refutation for the multiple choice questions in the survey and I don't think I did...
