### ISSUE TITLE
Stop using forever to run mofacts in production

### ISSUE THREAD

**Issue by andrewtackett** [memphis-iis/mofacts-ies#86]
Investigate pm2 and other alternatives for process management, hot deploys, log management, etc.

**Comment by aolney** [comment]
Please let me know what you come up with, because I've been using `forever` and similar methods myself.

**Comment by andrewtackett** [comment]
@aolney It seems there are two ways to go about this.  Either stick with deployments directly to the host machine and use something like pm2 to manage the node process that way, or use docker containers which do something like `node app.js` and then use a container orchestrator or something equivalent to manage uptime.

I think I'm going to opt for something equivalent as a full blown kubernetes install is overkill.  Meteor up and docker swarm don't allow for sticky sessions and zero downtime deployment at the same time so I'm going to roll my own in the following way:

-Set up app docker image in either a private repository or docker hub (I'm leaning towards docker hub because this will help with users running mofacts locally).
-Configure docker to expose two containers on given ports (say ports xxxx and yyyy) which use that docker image and have an auto restart policy (https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy)
-Configure HAProxy with four backend servers (two usually disabled) with sticky sessions (https://www.haproxy.com/blog/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/), frontend mofacts.optimallearning.org and one additional backend server for staging testing (redirecting from frontend something like staging.mofacts.optimallearning.org)

Then when a production update is triggered, run a script which does the following:

-Pull latest docker image from repository.
-Configure 2 new docker containers exposed on ports zzzz and aaaa
-Use HAProxy socket commands to update staging environment to the new container port (zzzz) and set the other backend server addresses to the new container ports (zzzz and aaaa).
-Wait for manual checkout of staging environment.  Upon successful checkout (which may involve unit tests if we're really optimistic) enter command to update production
-Use HAProxy socket commands to set the other backend servers to active and set the current backend servers for production to drain. (So new connections go to new code and old connections stick with the old code until the client closes the browser or times out)
-Poll HAProxy's socket command to figure out when the old service has drained all connections
-After this happens set the old backend servers in HAProxy to disabled and shut down the old docker containers.

**Comment by andrewtackett** [comment]
Also pm2 doesn't support sticky sessions and zero downtime deployment (which may or may not be an issue for you depending on how your app is written)

**Comment by andrewtackett** [comment]
Also to note: 

"At its basic form, a Node app runs over a single CPU core while all others remain idle. You have to replicate the Node process and utilize all CPUs. For small-medium apps, you could still use PM2 or Node Cluster. For a bigger app consider using some Docker cluster or deployment scripts that are based on the Linux init system to replicate the process. Else your application is likely to utilize barely thirty percent of its available resources or even less. A standard server has four or more CPU cores, native deployment of Node.JS uses only one, even with AWS beanstalk"

https://www.cognitiveclouds.com/insights/top-node-js-production-best-practices/

So running multiple instances of node is advisable to use the full server core.

**Comment by imrryr** [comment]
Is this a refactor item, or a special issue in progress?

**Comment by andrewtackett** [comment]
This isn't refactoring, that involves rewriting existing code to be cleaner/more performant.  This is more setting up a new deployment infrastructure which is better for the long term.

**Comment by imrryr** [comment]
Should this be rolled into dockerizing

**Comment by andrewtackett** [comment]
I think it's big enough that we might want them as separate issues.  That said dockerizing (#73) is a prerequisite of this

**Comment by andrewtackett** [comment]
> 
> 
> @aolney It seems there are two ways to go about this. Either stick with deployments directly to the host machine and use something like pm2 to manage the node process that way, or use docker containers which do something like `node app.js` and then use a container orchestrator or something equivalent to manage uptime.
> 
> I think I'm going to opt for something equivalent as a full blown kubernetes install is overkill. Meteor up and docker swarm don't allow for sticky sessions and zero downtime deployment at the same time so I'm going to roll my own in the following way:
> 
> -Set up app docker image in either a private repository or docker hub (I'm leaning towards docker hub because this will help with users running mofacts locally). -Configure docker to expose two containers on given ports (say ports xxxx and yyyy) which use that docker image and have an auto restart policy (https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy) -Configure HAProxy with four backend servers (two usually disabled) with sticky sessions (https://www.haproxy.com/blog/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/), frontend mofacts.optimallearning.org and one additional backend server for staging testing (redirecting from frontend something like staging.mofacts.optimallearning.org)
> 
> Then when a production update is triggered, run a script which does the following:
> 
> -Pull latest docker image from repository. -Configure 2 new docker containers exposed on ports zzzz and aaaa -Use HAProxy socket commands to update staging environment to the new container port (zzzz) and set the other backend server addresses to the new container ports (zzzz and aaaa). -Wait for manual checkout of staging environment. Upon successful checkout (which may involve unit tests if we're really optimistic) enter command to update production -Use HAProxy socket commands to set the other backend servers to active and set the current backend servers for production to drain. (So new connections go to new code and old connections stick with the old code until the client closes the browser or times out) -Poll HAProxy's socket command to figure out when the old service has drained all connections -After this happens set the old backend servers in HAProxy to disabled and shut down the old docker containers.

This setup is probably unneeded due to increased efficiency with postgres and the possibility of using javascript/node worker threads on the server side.
