### ISSUE TITLE
Space between testing buttons

### ISSUE THREAD

**Issue by Brtelfer** [memphis-iis/mofacts-ies#862]
On the TDF Practice + it would be nice to have spaces between the buttons on the practice modules. Currently, they are displayed as rectangular columns:

![image](https://user-images.githubusercontent.com/106611498/177403888-165ab1e1-4a1a-42b3-9890-ec44b0510ff9.png)

**Comment by imrryr** [comment]
We also discussed a folder system for buttons, which would be a more extensive enhancement clearly. I was wondering if a tagging system made sense? People could assign "content" tags in the tdfs, then there could be a filter button field on the tdf page. That way the folders are essentially defined at creation by the tags. What do @JRustyHaner and @MegaGeese think?

**Comment by JRustyHaner** [comment]
@imrryr that isn't that difficult of an idea.
