### ISSUE TITLE
Main tdf page tagging function

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#867]
Allow there to be a setspec value called "tags", which will be a comma delimited list of identifiers for the tdf. Also build a filter field above the buttons shown when userselect=TURE, that allows you to search for tags by entering them, at which point only those tdfs with the matching tags are shown.

**Comment by JRustyHaner** [comment]
@imrryr  I just put up a PR for this, but regarding the userselect...

userselect is defined by each tdf, you could have a case where some tdfs are userselect=FALSE and some are TRUE. Thou e filter currently appears regardless of userselect because of that case.

**Comment by imrryr** [comment]
Not sure what you are saying. TDFs are not eligible for the main page unless userselect = TRUE.... if is false the buttons are not shown unless you posted the tdf yourself, or it is posted to a class. Maybe this was never made clear, sorry. @JRustyHaner

**Comment by JRustyHaner** [comment]
Then the current solution works. The eligible tdfs (the ones with user select=true) are filtered by the tag search box.

**Comment by MegaGeese** [comment]
issue was merged into the wrong branch [here](https://github.com/memphis-iis/mofacts-ies/pull/869)
