### ISSUE TITLE
Write unit/integration tests

### ISSUE THREAD

**Issue by andrewtackett** [memphis-iis/mofacts-ies#89]
-Figure out good testing framework for meteor
-Research best practices for testing meteor apps
-Write tests for most important parts of mofacts

**Comment by andrewtackett** [comment]
Will add tests as spec gets fleshed out

**Comment by andrewtackett** [comment]
Write integration tests for key functionality flows such as: tdf/stim uploading, teacher class creation, teacher class tdf assignment, simple stripped down experiment working/recording any data (another test for correct data can be added later), turk functionality, user admin, etc.

**Comment by andrewtackett** [comment]
1. Login as admin and Upload stim/tdf pair
-does database now have that experiment?

2. Upload (southwest teacher) user csv
-does user with password now exist?

3. Toggle user as teacher via UI
-is user in teacher role now?

4. Login as created teacher from 2/3. Create class with 2 sections via UI.
-Does class with sections show in database?
-Does class show on signinsouthwest?

5.a. As teacher from 2/3/4 assign uploaded tdf from 1 to class from 4 via UI
-Does assignment show up in database?
5.b. Login as student via signinsouthwest to class/sec from 4.
-Does assigned tdf from 5.a. appear?

6. As logged in student from 5.b. try tdf experiment with simple feedback selected
-Does schedule unit work? (assumed tdf construction)
-Does learning unit work? (assumed tdf construction)

7. As student from 5.b. try tdf learning unit with refutational feedback, using matching cache incorrect answers.
-Is refutational feedback given?

8. As student from 5.b try tdf learning unit with dialogue feedback, using matching cache incorrect answers.
-Is dialogue feedback given?

9. As student from 5.b look at progress report.
-Does report match expected output for interaction so far (this might take some twiddling to make precisely correct and known)

10.a. Login as teacher from 2/3 and look at instructor reporting.
-Does class from 4 show up?
-Do reporting totals match expected values?
b. drill down to student from 5.b.
-Do reporting totals match expected values? (which should also match student progress report)

**Comment by andrewtackett** [comment]
Implement the above and go for tradeoffs in exact correctness, especially in the experiment verification, vs time/difficulty to implement.

Take a look at element/flood (we use it in the scripts/load-testing script) for a basic starter on browser automation.

Also maybe take a look at replay tools such as: https://news.ycombinator.com/item?id=28539247 for replicating user flows which might be helpful in defining test cases.

**Comment by JRustyHaner** [comment]
@MegaGeese This is being taken care of my Selenium, correct?
