### ISSUE TITLE
Works well on smartphones

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#9]
Chat type interface

**Comment by imrryr** [comment]
changed the item fontsize to 4 and it looks pretty good on my smartphone. Lower priority of a special interface now. However, can we make it so that it can automatically activate speech recognition from as a service from the phone for each trial? Automatically hitting enter after each response? I was doing this manually, and my phone's native speech recognition was quite fast.

**Comment by imrryr** [comment]
This will be an experimental feature this term. Are we recording the OS of each user to monitor the choices students make for clients.

**Comment by imrryr** [comment]
Please see question then close for now

**Comment by andrewtackett** [comment]
I've updated the code to capture the user agent (which includes OS and browser version) as well as the time of last login.  Relevant commit: 82a19163ed8ad1f76372c7a476fff0553b036d68
