### ISSUE TITLE
Hints not given on staging

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#900]
**Describe the bug**
Hints never given. Not sure why, but none of Liz's recent tests show hints. Maybe it is only running at the first hint level and not recognizes this content has hints. Chapter 6 Demo (Chapter 6.json) is where the hints were missing.

**Comment by MegaGeese** [comment]
Can you send the chapter 6 demo files that are causing this issue?

**Comment by imrryr** [comment]
Its still not giving hints. Class A&P 1 Intervention on Staging, both Chapters 5 and 6 were not giving hints

**Comment by MegaGeese** [comment]
It looks like no matter what the outcome was, every hint level for an item is getting the same probability which is causing the hints to not show.

**Comment by imrryr** [comment]
I'd assume p.hintLevel is not set when the function is called. You can see if it is set, the function must return different values...


"calculateProbability": "var intercept;\n if (p.hintLevel==0) {intercept=1.08} else if (p.hintLevel==1) {intercept=1.57} else {intercept=2.09}\n var clozeProbability =p.stim.tags ? (p.stim.tags.clozeProbability || 0) : 0;\n var sentenceWeight =p.stim.tags ? (p.stim.tags.sentenceWeight || 0) : 0;\n p.y = intercept +\n .90 * pFunc.logitdec(\n p.overallOutcomeHistory.slice(Math.max(p.overallOutcomeHistory.length-60,1),\n p.overallOutcomeHistory.length), .951) +\n 1.63 * pFunc.recency(p.stimSecsSinceLastShown, .179) +\n 1.53 * pFunc.recency(p.responseSecsSinceLastShown, .017) +\n .241 * pFunc.linediffcor(p.stimOutcomeHistory, p.stimPreviousCalculatedProbabilities) +\n -.241 * pFunc.quaddiffcor(p.stimOutcomeHistory, p.stimPreviousCalculatedProbabilities) +\n .122*Math.log(parseFloat(clozeProbability))+\n -.0825*Math.log(parseFloat(sentenceWeight))+\n -.40* Math.log(p.answerText.length);\n p.probability = 1.0 / (1.0 + Math.exp(-p.y)); \n return p\n"

**Comment by imrryr** [comment]
It seems like it should be easy to download from the server however. Also
then you don't have to rename the file and I don't have to rename the file
because it won't let me upload to Json here. Is it more difficult to
download the file from staging than I realize? I will send it then It would
be good to figure out a way for us to have the developers have easier
access here, if that's possible it will speed up the process of submitting
issues.
