### ISSUE TITLE
download data specificity 

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#902]
**Describe the bug**
I download Chapter 6 Demo (Chapter 6.json) and it gives me old data from when it was Chapter 6 (Chapter 6.json).

In other words, it ignores the uniqueness of the title in the query, relying on the filename and giving things that don't match the title listed.

We may need to talk about this since I had expected when I overwrote the json, the data would become inaccessible from prior versions, or the data download should list the old and new versions simultaneously.

**Comment by imrryr** [comment]
To be further defined.

**Comment by imrryr** [comment]
We need some sort of ownership/access system for tdfs and stim files (which should not be linked to each other)
Owner can overwrite (both), assign to classes (tdfs), access data (tdfs), assign accessors (tdfs), and transfer ownership (both)
Accessors can access data (tdfs), assign to classes (tdfs), get progress reports (tdfs)

only 1 owner for any tdf or stim file
unlimited accessors
owner can assign ownership to any accessor
Any user can be added as accessor

Thoughts?

**Comment by JRustyHaner** [comment]
For more specificity: 
Accessors should only be able to view data of their own classes, not all classes that have that tdf, correct?
Owners should not be able to view progress reports?

To summarize:
The stim and tdf inside the database would have an added key string of the user id of the owner, and an array string of accessor's user ids. The Content page would have added functionality to transfer to ownership to another user by an identifier (name lookup or give each user a 6 digit code or similar) and a list of accessors that can be added to by an identifier (name lookup or code) when an owned tdf or stim is selected from a dropdown. The data downloads, assignments, and progress reports will have access control by checking the appropriate string or if that string is in the accessors array.

**Comment by imrryr** [comment]
Excellent. Clarifications to the good questions:

Accessors should only be able to view data of their own classes, not all classes that have that tdf, correct?
Yes! good point.  Also only see progress reports for their own classes. Since the admin can login aliasing anyone, they can bypass this as needed.  If data was not from a class, everyone has access (ownersand accessors).

In other words, when a teacher assigns a tdf to a class they get fenced access to all new data for that class, but all unfenced data for that tdf is available to all accessors and the owner. We will need to have options for downloading all data accessible, or all data for my classes.

Owners should not be able to view progress reports?
Yes, block owners from data download or progress IF the practice originated from another class. If data was not from a class, everyone has access (owner and accessors). Owners will be able to see the progress reports/ data for their classes of course.
