### ISSUE TITLE
Is this error for probParamDisplay a problem

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#909]
**Describe the bug**
Seen in console, looks suspicious
![2022-08-21 (3)](https://user-images.githubusercontent.com/13023147/185811031-fb54009e-fa3b-4bd5-8ad9-c4bc2a6208d9.png)

**Comment by JRustyHaner** [comment]
Nope, it's saying a variable that displays the debug menu is unset. Nothing to be concerned about.
