### ISSUE TITLE
Website reads as not secure in address bar

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#911]
**Describe the bug**
![2022-08-21](https://user-images.githubusercontent.com/13023147/185811420-2303ed36-7e1d-4f77-9697-29e6b0146887.png)

**Comment by JRustyHaner** [comment]
I only get this if I force it to http://staging.optimallearning.org  and not staging.optimallearning.org. We can detect the http connection and redirect it to https in this case.
