### ISSUE TITLE
Symspell version not compatible with Node on Staging

### ISSUE THREAD

**Issue by MegaGeese** [memphis-iis/mofacts-ies#916]
Staging is running on Node v12. Need to find a symspell that is compatible with node 12

**Comment by MegaGeese** [comment]
The problem was not with node, the problem is with NPM/node-symspell. 

node-symspell requires "node: '12.x', npm: '6.5.x'", mofacts uses npm version 6.14.16. Installing node-sympell would lock us into an unsupported version of node.

**Comment by imrryr** [comment]
So that sounds real bad. I added Andrew here, but it sounds like we can't use symspell? Thoughts?

**Comment by MegaGeese** [comment]
We should be able to use symspell as long as the version I found that doesnt use node works. I was planning on trying to implement that today.

**Comment by imrryr** [comment]
Works on staging not yet on Mofacts

**Comment by MegaGeese** [comment]
working now on mofacts and staging.
