### ISSUE TITLE
Upcoming format change in stim files

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#921]
Currently, it is
							"stimulusId": 1127875236,
							"clusterId": 543550611,

We need to switch to:
							"clozeId": -173298147,
							"itemId": -1537954220,

need to handle database storage and reporting in data downloads

**Comment by MegaGeese** [comment]
It looks like this is already the case. Are there specific files that you notice that don't follow this naming convention?

**Comment by imrryr** [comment]
I don't know what you mean because I've never uploaded files in the new
format. They've only been in the first format which is going to be changed
so if the code handles the first format it seems like it won't handle the
new format.

**Comment by MegaGeese** [comment]
Did you mean
> Currently, it is
"clozeId": -173298147,
"itemId": -1537954220,
We need to switch to:
"stimulusId": 1127875236,
"clusterId": 543550611,

Every file that has been uploaded to the servers have been using the clozeId/itemId notation.

**Comment by imrryr** [comment]
Yes, I was just seeing my error, I had it totally backwards; thanks for helping figure that out!

**Comment by MegaGeese** [comment]
A change like this doesn't require a code change. I have a script ready to run to do this change on the database.
