### ISSUE TITLE
Info on progress report dials

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#924]
Can you please cut and paste the exact formula for calculating the bottom dial during practice, the one that judges the algorithms effectiveness and choosing items. It seems to be oversensitive and I'd like to think about whether it is calculating a useful value. Also provide a little context for the variables if necessary to understand the code.

**Comment by JRustyHaner** [comment]
the bottom 'odometer' graph is calculted like this (line 238 of studentReporting.js):
  displayDifficulty =  (Math.min(Math.max(difficultyCorrectProportion - optimumDifficulty, -0.3) , 0.3) + 0.3) * 100; //Add .3 and Multiply by 100 for graph scale

the dependent variables (line 217 of studentReporting.js):

difficultyCorrectProportion = parseFloat(difficultyData.numCorrect) / (parseFloat(difficultyData.numCorrect) + parseFloat(difficultyData.numIncorrect));

 const difficultyData = await meteorCallAsync('getStudentPerformanceByIdAndTDFIdFromHistory', studentId, selectedTdfId, difficultyHistory); where difficultyHistory is the last x entries to history matching studentId and TdfId, set by  selectedTdf.content.tdfs.tutor.setspec.progressReporterParams or defaulted to 30.

**Comment by imrryr** [comment]
Thanks, I analyzed it thoroughly and it was working fine.
