### ISSUE TITLE
Old assets remain

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#930]
**Describe the bug**
Old assets were not cleaned out. Many of these were caused by a bug and definitely need cleaning
![2022-08-27 (1)](https://user-images.githubusercontent.com/13023147/187047968-bfb4423a-3f65-402e-84bf-87f27b7c8204.png)
.

**Comment by imrryr** [comment]
Problem is mostly fixed, but note two versions of "cropped" png files were uploaded despite being identical... not sure why

**Comment by JRustyHaner** [comment]
@imrryr it is showing what is currently in assets, some might display twice. This is counterintuitive, and I've found a way to just report what was processed, if that is what you want
