### ISSUE TITLE
assests are not processed or displayed right away

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#932]
**Describe the bug**
Despite indicating the upload was complete, I needed to refresh twice before my new tdfs showed on the content list in the Content and File Uploading section... they should show immediately, or the user needs to be told when they will appear...

**Comment by imrryr** [comment]
Sorry, the upload was of this pack through the Asset uploading screen
[Test2IESPack.zip](https://github.com/memphis-iis/mofacts-ies/files/9440415/Test2IESPack.zip)

**Comment by JRustyHaner** [comment]
@imrryr this shouldn't happen anymore, given feedback from issue #942, since you'll get 
-any upload errors
-any json formatting errors, stating the name of the file that is problematic
-a alert when the process is finished
