### ISSUE TITLE
Stim generation error

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#946]
**Describe the bug**
Error in stim generation, 

"correctResponse": "."

will need new fixed files that don't allow "." as a response

"stims": [
					{
						"response": {
							"correctResponse": "."
						},
						"display": {
							"clozeStimulus": "From__________there__________they__________pass__________into__________the__________auditory__________cortices__________of__________the__________temporal__________lobes__________of__________the__________cerebrum, where__________they__________are__________interpreted."
						},
						"parameter": "0,.80",
						"tags": {
							"weightGroup": 3,
							"orderGroup": 4,
							"sentenceWeight": 30,
							"clozeProbability": 1,
							"corefClusters": 2,
							"corefClusterTotalWeight": 30,
							"corefClusterBackwardWeight": 3,
							"corefClusterForwardWeight": 23,
							"rootDistance": 1,
							"startDistance": 20,
							"stimulusId": 536985279,
							"clusterId": -497599541,
							"transformation": "none"
						}
					},
					{
						"response": {
							"correctResponse": "."
						},
						"display": {
							"clozeStimulus": "From__________there, they__________pass__________into__________the__________auditory__________cortex__________of__________the__________early__________lobes__________of__________the__________brain, where__________they__________are__________interpreted."
						},
						"parameter": "0,.80",
						"tags": {
							"weightGroup": 3,
							"orderGroup": 4,
							"sentenceWeight": 30,
							"clozeProbability": 1,
							"corefClusters": 2,
							"corefClusterTotalWeight": 30,
							"corefClusterBackwardWeight": 3,
							"corefClusterForwardWeight": 23,
							"rootDistance": 1,
							"startDistance": 20,
							"stimulusId": -847164254,
							"clusterId": -497599541,
							"transformation": "paraphrase"
						}
					}
				]
			},

**Comment by aolney** [comment]
This only occurs in this one file (I just searched all stim files), specifically two items off the same sentence in chapter 12

I don't fully understand what's happening with the blanks, but the problem seems to be driven by the parser assigning a weird structure to the sentence.

Rather than fiddle with the parser, which could cause unintended consequences for other items, I suggest we manually edit out the items involved.

**Comment by aolney** [comment]
I've got a patch in that prevents this from happening; I can either re-run the stim files or we can manually edit the 2 items out, just let me know
