### ISSUE TITLE
Investigate why some tdfs generated correctly when not deleting stims in content generation

### ISSUE THREAD

**Issue by andrewtackett** [memphis-iis/mofacts-ies#95]
Chapter_10_Online_ambanker_2019_11_13T00_59_56_284Z_TDF.xml generated correctly whereas Chapter_10_Traditional_ambanker_2019_11_13T01_03_38_784Z_TDF.xml did not despite the code not appearing to allow the assessment item to be captured if no stim items were deleted.

Look at code prior to commit: 818657d9860bcfea87a3a0a44ef7492e78be2780

**Comment by wscarter** [comment]
Issue fixed with commit:

818657d9860bcfea87a3a0a44ef7492e78be2780
