### ISSUE TITLE
Broken capitalization in summary of tutorial dialogue

### ISSUE THREAD

**Issue by aolney** [memphis-iis/mofacts-ies#952]
Rusty & Rhodes-

I'm trying to track down a formatting bug I noticed today in the
tutorial dialogue.

When the final summary is generated, a word in the middle of the
sentence is capitalized. Here's an example:

"It's important to remember that The cerebrum is a part of the brain in
the upper part of your cranial cavity that provides higher mental
functions."

However, in my current version of the code, the display field on the
object you should be getting looks like this:

"Display": "It's important to remember that the cerebrum is a part of
the brain in the upper part of your cranial cavity that provides higher
mental functions. Moving on."

Some reasons for the discrepancy that I can think of:

- An old version of the code is deployed
- The current version is deployed, but the wrong field is being displayed
- There's some weird edge case involved

Any thoughts would be appreciated

**Comment by MegaGeese** [comment]
Can you send me the TutorialDialogue file that you have? I'm seeing the same issue through the database, but appears to only be an issue for a certain string (see the picture). Granted its a small sample size but the second entry doesn't have that capitalization issue. 

![MongoDBCompass_TdPFv0cyY1](https://user-images.githubusercontent.com/50426711/191560745-66048651-3d5c-42a1-a3b3-543081070643.png)

**Comment by imrryr** [comment]
This issue is not a priority and should not get in the way of deploy.

**Comment by aolney** [comment]
> Can you send me the TutorialDialogue file that you have? I'm seeing the same issue through the database, but appears to only be an issue for a certain string (see the picture). Granted its a small sample size but the second entry doesn't have that capitalization issue.
> 
> ![MongoDBCompass_TdPFv0cyY1](https://user-images.githubusercontent.com/50426711/191560745-66048651-3d5c-42a1-a3b3-543081070643.png)

Great example - it looks like there is an extra space when it fails, so I think this could be fixed by trimming whitespace before the lowercase transformation.

Let me know when/if you want this, and I'll do a new code drop.

**Comment by imrryr** [comment]
Please send the new code Andrew.

**Comment by aolney** [comment]
Please find the updated code here

https://drive.google.com/file/d/14ExaCCHhQxpOtWR9HU9GREe2jwvSDsbi/view?usp=sharing
