### ISSUE TITLE
Logged in after not using for a day

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#976]
**Describe the bug**
So, it seems like it keeps me logged in overnight, even when I am off the page. This doesn't seem right, what is standard for logoff when you navigate away?

**Comment by JRustyHaner** [comment]
@imrryr we've been relying on a node plugin for this that we should refactor into our own system. Basically, log the last time the user interacted with mofacts, and if it has been over x amount of time, log them out.
