### ISSUE TITLE
Content creation interface

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#982]
[2022-07-09-content-creation-interface (1).pdf](https://github.com/memphis-iis/mofacts-ies/files/9718487/2022-07-09-content-creation-interface.1.pdf)

**Comment by MegaGeese** [comment]
Should we allow a user to specify an email they would like to receive the file too?

**Comment by aolney** [comment]
@MegaGeese If they have an email connected to their user account, that would make sense. If not, I can see asking them for an email address in the interface

**Comment by MegaGeese** [comment]
closed by https://github.com/memphis-iis/mofacts-ies/pull/1022
